# a52dec
# Autogenerated from man page /usr/share/man/man1/a52dec.1.gz
# using Deroffing man parser
complete -c a52dec -s h --description 'display help and available audio modes.'
complete -c a52dec -s s --description 'use program stream demultiplexer, track 0-7 or 0x80-0x87.'
complete -c a52dec -s t --description 'use transport stream demultiplexer, pid 0x10-0x1ffe.'
complete -c a52dec -s c --description 'use c implementation, disables all accelerations.'
complete -c a52dec -s r --description 'disable dynamic range compression.'
complete -c a52dec -s o --description 'use audio output driver `mode\'.'

