# admin
# Autogenerated from man page /usr/share/man/man1/admin.1p.gz
# using Deroffing man parser
complete -c admin -s i --description '.'
complete -c admin -s t --description 'and.'
complete -c admin -s y --description 'options have optional option-arguments.'
complete -c admin -s n --description 'Create a new SCCS file.  When.'
complete -c admin -o 'i[name]' --description 'Specify the name of a file from which the text … [See Man Page]'
complete -c admin -s r --description 'option for the delta numbering scheme).  If the.'
complete -c admin -o 't[name]' --description 'Specify the name of a file from which descripti… [See Man Page]'
complete -c admin -s f --description 'Specify a flag , and, possibly, a value for the… [See Man Page]'
complete -c admin -s b --description 'option on a get command to create branch deltas.'
complete -c admin -s e --description 'against one of these locked releases fails).'
complete -c admin -s d --description 'Remove (delete) the specified flag from an SCCS file.  Several.'
complete -c admin -s a --description 'Specify a login name, or numerical group ID, to… [See Man Page]'
complete -c admin -o 'y[comment]' --description 'Insert the comment text into the SCCS file as a… [See Man Page]'
complete -c admin -s m --description 'Insert the list of modification request (MR) nu… [See Man Page]'
complete -c admin -s h --description 'Check the structure of the SCCS file and compar… [See Man Page]'
complete -c admin -s z --description 'Recompute the SCCS file checksum and store it i… [See Man Page]'

