# affcat
# Autogenerated from man page /usr/share/man/man1/affcat.1.gz
# using Deroffing man parser
complete -c affcat -s s --description 'Output the named segment, instead of the image data.'
complete -c affcat -s p --description 'Just output page number  nnn.'
complete -c affcat -s S --description 'Just output data sector number  nnn.'
complete -c affcat -s q --description 'Quiet mode.'
complete -c affcat -s n --description 'Noisy mode.  Tell when pages are skipped.'
complete -c affcat -s l --description 'List all the segment names, rather than outputing data.'
complete -c affcat -s L --description 'List Long.  Prints segment names, lengths, and args.'
complete -c affcat -s d --description 'Debug mode.'
complete -c affcat -s b --description 'Output BADFALG for bad blocks (default is to output NULLs).'
complete -c affcat -s v --description 'Just print the version number and exit.'
complete -c affcat -s r --description 'Seek to the given byte offset and output count … [See Man Page]'

