# airdecap-ng
# Autogenerated from man page /usr/share/man/man1/airdecap-ng.1.gz
# using Deroffing man parser
complete -c airdecap-ng -s H -l help --description 'Shows the help screen.'
complete -c airdecap-ng -s l --description 'Do not remove the 802. 11 header.'
complete -c airdecap-ng -s b --description 'Access point MAC address filter.'
complete -c airdecap-ng -s k --description 'WPA Pairwise Master Key in hex.'
complete -c airdecap-ng -s e --description 'Target network SSID.'
complete -c airdecap-ng -s p --description 'Target network WPA passphrase.'
complete -c airdecap-ng -s w --description 'Target network WEP key in hex.'

