# airdecloak-ng
# Autogenerated from man page /usr/share/man/man1/airdecloak-ng.1.gz
# using Deroffing man parser
complete -c airdecloak-ng -s h -l help --description 'Shows the help screen.'
complete -c airdecloak-ng -s i --description 'Path to the capture file.'
complete -c airdecloak-ng -l ssid --description 'Essid of the network (not yet implemented) to filter.'
complete -c airdecloak-ng -l bssid --description 'BSSID of the network to filter.'
complete -c airdecloak-ng -l null-packets --description 'Assume that null packets can be cloaked.'
complete -c airdecloak-ng -l disable-base-filter --description 'Do not apply base filter.'
complete -c airdecloak-ng -l drop-frag --description 'Drop fragmented packets.'
complete -c airdecloak-ng -l filters --description 'Apply different filters (separated by a comma).  See below.'

