# airodump-ng
# Autogenerated from man page /usr/share/man/man1/airodump-ng.1.gz
# using Deroffing man parser
complete -c airodump-ng -s H -l help --description 'Shows the help screen.'
complete -c airodump-ng -s i -l ivs --description 'It only saves IVs (only useful for cracking).'
complete -c airodump-ng -s g -l gpsd --description 'Indicate that airodump-ng should try to use GPS… [See Man Page]'
complete -c airodump-ng -s w -l write --description 'Is the dump file prefix to use.'
complete -c airodump-ng -s e -l beacons --description 'It will record all beacons into the cap file.'
complete -c airodump-ng -s u -l update --description 'Delay <secs> seconds delay between display upda… [See Man Page]'
complete -c airodump-ng -l showack --description 'Prints ACK/CTS/RTS statistics.'
complete -c airodump-ng -s h --description 'Hides known stations for --showack.'
complete -c airodump-ng -l berlin --description 'Time before removing the AP/client from the scr… [See Man Page]'
complete -c airodump-ng -s c -l channel --description 'Indicate the channel(s) to listen to.'
complete -c airodump-ng -s b -l band --description 'Indicate the band on which airodump-ng should hop.'
complete -c airodump-ng -s s -l cswitch --description 'Defines the way airodump-ng sets the channels w… [See Man Page]'
complete -c airodump-ng -s r --description 'Reads packet from a file.'
complete -c airodump-ng -s x --description 'Active Scanning Simulation (send probe requests… [See Man Page]'
complete -c airodump-ng -l output-format --description 'Define the formats to use (separated by a comma).'
complete -c airodump-ng -s t -l encrypt --description 'It will only show networks matching the given encryption.'
complete -c airodump-ng -s d -l bssid --description 'It will only show networks, matching the given bssid.'
complete -c airodump-ng -s m -l netmask --description 'It will only show networks, matching the given … [See Man Page]'
complete -c airodump-ng -s a --description 'It will only show associated clients.  INTERACTION.'
complete -c airodump-ng -l --------------------------------------------------------------------- --description '.'

