# airolib-ng
# Autogenerated from man page /usr/share/man/man1/airolib-ng.1.gz
# using Deroffing man parser
complete -c airolib-ng -l stats --description 'Output information about the database.'
complete -c airolib-ng -l sql --description 'Execute specified SQL statement.'
complete -c airolib-ng -l clean --description 'Clean the database from old junk.'
complete -c airolib-ng -l batch --description 'Start batch-processing all combinations of ESSI… [See Man Page]'
complete -c airolib-ng -l verify --description 'Verify a set of randomly chosen PMKs.'
complete -c airolib-ng -l import --description 'Import a flat file as a list of ESSIDs or passwords.'
complete -c airolib-ng -l export --description 'Export to a cowpatty file.'

