# airserv-ng
# Autogenerated from man page /usr/share/man/man1/airserv-ng.1.gz
# using Deroffing man parser
complete -c airserv-ng -s h --description 'Shows the help screen.'
complete -c airserv-ng -s p --description 'TCP port to listen on (by default: 666).'
complete -c airserv-ng -s d --description 'Wifi interface to use.'
complete -c airserv-ng -s c --description 'Lock interface to this channel.'
complete -c airserv-ng -s v --description 'Debug level.  There are 3 debug levels.'

