# airtun-ng
# Autogenerated from man page /usr/share/man/man1/airtun-ng.1.gz
# using Deroffing man parser
complete -c airtun-ng -s H -l help --description 'Shows the help screen.'
complete -c airtun-ng -s x --description 'Sets maximum number of packets per second.'
complete -c airtun-ng -s a --description 'Specifies the BSSID for the iee802. 11 header.'
complete -c airtun-ng -s h --description 'Specifies the source MAC for the iee802. 11 header.'
complete -c airtun-ng -s i --description 'Sets the capture interface.'
complete -c airtun-ng -s r --description 'Specifies a file to read 802. 11 frames.'
complete -c airtun-ng -s y --description 'Is the name of the file, which provides the key… [See Man Page]'
complete -c airtun-ng -s w --description 'This is the WEP key to en-/decrypt all traffic … [See Man Page]'
complete -c airtun-ng -s t --description 'Defines the ToDS and FromDS bit in the ieee802. 11 header.'
complete -c airtun-ng -s m -l netmask --description 'Filters networks based on bssid ^ netmask combination.'
complete -c airtun-ng -s d -l bssid --description 'Filters networks based on the <BSSID>.  Used in replay mode.'
complete -c airtun-ng -s f -l repeat --description 'Enables replay mode.'
complete -c airtun-ng -s s --description 'Set Transmitter MAC address for WDS Mode.'
complete -c airtun-ng -s b --description 'Bidirectional mode.'

