# alltray
# Autogenerated from man page /usr/share/man/man1/alltray.1.gz
# using Deroffing man parser
complete -c alltray -s '?' -l help --description 'Show the help (usage) screen.'
complete -c alltray -s a -l attach --description 'Attaches to an already-running application.'
complete -c alltray -s L -l list-debug-opts --description 'Lists the debug \\(lqflags\\(rq that AllTray supports.'
complete -c alltray -s C -l enable-ctt --description 'Enable the Close-To-Tray support in AllTray.'
complete -c alltray -s D -l debug --description 'Enable the debug message printing mechanism of AllTray.'
complete -c alltray -s H -l hide --description 'Hide the target application when AllTray is sta… [See Man Page]'
complete -c alltray -s p -l process --description 'Specifies the process ID of the application to … [See Man Page]'
complete -c alltray -s v -l version --description 'Show the program version, copyright, and license, then exit.'
complete -c alltray -l 'attach);' --description '# OPTIONS #.'
complete -c alltray -l 'attach.' --description '.'
complete -c alltray -s V -l extended-version --description 'Show the program version, copyright, license, a… [See Man Page]'

