# amixer
# Autogenerated from man page /usr/share/man/man1/amixer.1.gz
# using Deroffing man parser
complete -c amixer -s c --description 'Select the card number to control.'
complete -c amixer -s D --description 'Select the device name to control.'
complete -c amixer -s s -l stdin --description 'Read from stdin and execute the command on each… [See Man Page]'
complete -c amixer -s h --description 'Help: show syntax.'
complete -c amixer -s q --description 'Quiet mode.  Do not show results of changes.'
complete -c amixer -s R --description 'Use the raw value for evaluating the percentage representation.'
complete -c amixer -s M --description 'Use the mapped volume for evaluating the percen… [See Man Page]'

