# apt
# Autogenerated from man page /usr/share/man/man1/apt.1.gz
# using Type1
complete -c apt -s s --description 'Specify the directory root under which processo… [See Man Page]'
complete -c apt -o nocompile --description 'Do not compile source files to class files.'
complete -c apt -o print --description 'Print out textual representation of specified t… [See Man Page]'
complete -c apt -o 'A[key[' --description 'Options to pass to annotation processors -- the… [See Man Page]'
complete -c apt -o factorypath --description 'Specify where to find annotation processor fact… [See Man Page]'
complete -c apt -o factory --description 'Name of annotation processor factory to use; by… [See Man Page]'
complete -c apt -o version --description 'Print version information.'
complete -c apt -s X --description 'Display information about non-standard options. RE  . LP .'
complete -c apt -s d --description 'Specify where to place processor and javac gene… [See Man Page]'
complete -c apt -o cp -o classpath --description 'Specify where to find user class files and anno… [See Man Page]'
complete -c apt -o XListAnnotationTypes --description 'List found annotation types.'
complete -c apt -o XListDeclarations --description 'List specified and included declarations.'
complete -c apt -o XPrintAptRounds --description 'Print information about initial and recursive \\f2apt rounds.'
complete -c apt -o XPrintFactoryInfo --description 'Print information about which annotations a fac… [See Man Page]'

