# arp-fingerprint
# Autogenerated from man page /usr/share/man/man1/arp-fingerprint.1.gz
# using Deroffing man parser
complete -c arp-fingerprint -s h --description 'Display a brief usage message and exit.'
complete -c arp-fingerprint -s v --description 'Display verbose progress messages.'
complete -c arp-fingerprint -s o --description 'Pass specified options to arp-scan.'
complete -c arp-fingerprint -s I -l interface -l numeric --description '(-N).  EXAMPLES.'

