# at
# Autogenerated from man page /usr/share/man/man1/at.1p.gz
# using Deroffing man parser
complete -c at -s m --description 'option.'
complete -c at -s f --description 'Specify the pathname of a file to be used as th… [See Man Page]'
complete -c at -s l --description '(The letter ell.'
complete -c at -s q --description '.'
complete -c at -s t --description 'time_arg or timespec arguments, the results are unspecified.'
complete -c at -s r --description 'Remove the jobs with the specified at_job_id op… [See Man Page]'
complete -c at -s u --description 'user option has allowed those with appropriate … [See Man Page]'

