# attr
# Autogenerated from man page /usr/share/man/man1/attr.1.gz
# using Deroffing man parser
complete -c attr -s g --description 'option tells attr to search the named object an… [See Man Page]'
complete -c attr -s q --description 'flag, stdout will be exactly and only the value… [See Man Page]'
complete -c attr -s l --description 'option tells attr to list the names of all the … [See Man Page]'
complete -c attr -s r --description 'option tells attr to remove an attribute with t… [See Man Page]'
complete -c attr -s s --description 'option tells attr to set the named attribute of… [See Man Page]'
complete -c attr -s V --description 'flag, the attribute will be set to have a value… [See Man Page]'
complete -c attr -s L --description 'option is given and the named object is a symbo… [See Man Page]'
complete -c attr -s R --description 'option is given and the process has appropriate… [See Man Page]'
complete -c attr -s S --description 'option is similar, except it specifies use of t… [See Man Page]'

