# auditd
# Autogenerated from man page /usr/share/man/man8/auditd.8.gz
# using Deroffing man parser
complete -c auditd -s f --description 'leave the audit daemon in the foreground for debugging.'
complete -c auditd -s l --description 'allow the audit daemon to follow symlinks for config files.'
complete -c auditd -s n --description 'no fork.  This is useful for running off of inittab or systemd.'
complete -c auditd -s s --description 'specify when starting if auditd should change t… [See Man Page]'

