# augenrules
# Autogenerated from man page /usr/share/man/man8/augenrules.8.gz
# using Deroffing man parser
complete -c augenrules -l check --description 'test if rules have changed and need updating wi… [See Man Page]'
complete -c augenrules -l load --description 'load old or newly built rules into the kernel.'

