# aulast
# Autogenerated from man page /usr/share/man/man8/aulast.8.gz
# using Deroffing man parser
complete -c aulast -l bad --description 'Report on the bad logins.'
complete -c aulast -l extract --description 'Write raw audit records used to create the disp… [See Man Page]'
complete -c aulast -s f --description 'Use the file instead of the audit logs for input.'
complete -c aulast -l proof --description 'Print out the audit event serial numbers used t… [See Man Page]'
complete -c aulast -l stdin --description 'Take audit records from stdin.'

