# autrace
# Autogenerated from man page /usr/share/man/man8/autrace.8.gz
# using Deroffing man parser
complete -c autrace -s r --description 'Limit syscalls collected to ones needed for ana… [See Man Page]'

