# avahi-bookmarks
# Autogenerated from man page /usr/share/man/man1/avahi-bookmarks.1.gz
# using Deroffing man parser
complete -c avahi-bookmarks -s p -l port --description 'Specify a TCP port number to listen on.'
complete -c avahi-bookmarks -s a -l address --description 'Specify an IP address to listen on.'
complete -c avahi-bookmarks -s H -l host-names --description 'Create links pointing to mDNS host names instea… [See Man Page]'
complete -c avahi-bookmarks -s A -l addresses --description 'Create links pointing to numeric IP addresses i… [See Man Page]'
complete -c avahi-bookmarks -s d -l domain --description 'The domain to browse for services in.'
complete -c avahi-bookmarks -s h -l help --description 'Show help AUTHORS The Avahi Developers <avahi (… [See Man Page]'

