# awesome
# Autogenerated from man page /usr/share/man/man1/awesome.1.gz
# using Deroffing man parser
complete -c awesome -s v -l version --description 'Print version information to standard output, then exit.'
complete -c awesome -s h -l help --description 'Print help information, then exit.'
complete -c awesome -s c -l config --description 'Use an alternate configuration file instead of … [See Man Page]'
complete -c awesome -s k -l check --description 'Check configuration file syntax.'
complete -c awesome -s a -l no-argb --description 'Don\\(cqt use ARGB visuals.'

