# blkcalc
# Autogenerated from man page /usr/share/man/man1/blkcalc.1.gz
# using Deroffing man parser
complete -c blkcalc -s d -s s --description 'or .'
complete -c blkcalc -s u --description 'options must be given.   If the .'
complete -c blkcalc -s f --description 'Identify the File System type of the image.'
complete -c blkcalc -s i --description 'Identify the type of image file, such as raw.'
complete -c blkcalc -s o --description 'The sector offset where the file system starts in the image.'
complete -c blkcalc -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c blkcalc -s v --description 'Verbose output to STDERR.'
complete -c blkcalc -s V --description 'Display version.'

