# blkcat
# Autogenerated from man page /usr/share/man/man1/blkcat.1.gz
# using Deroffing man parser
complete -c blkcat -s a --description 'Display the contents in ASCII.'
complete -c blkcat -s f --description 'Specify image as a specific file type.'
complete -c blkcat -s h --description 'Display the contents in hexdump .'
complete -c blkcat -s s --description 'Display statistics on the image (unit size, fil… [See Man Page]'
complete -c blkcat -s u --description 'Specify the size of the default data unit for r… [See Man Page]'
complete -c blkcat -s i --description 'Identify the type of image file, such as raw.'
complete -c blkcat -s o --description 'The sector offset where the file system starts in the image.'
complete -c blkcat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c blkcat -s v --description 'Verbose output to stderr.'
complete -c blkcat -s V --description 'Display version.'
complete -c blkcat -s w --description 'Display the contents in an HTML table format.'

