# blkdiscard
# Autogenerated from man page /usr/share/man/man8/blkdiscard.8.gz
# using Deroffing man parser
complete -c blkdiscard -s h -l help --description 'Display help text and exit.'
complete -c blkdiscard -s o -l offset --description 'Byte offset in the device from which to discard.'
complete -c blkdiscard -s l -l length --description 'Number of bytes after starting point to discard.'
complete -c blkdiscard -s s -l secure --description 'Perform secure discard.'
complete -c blkdiscard -s v -l verbose --description 'Print aligned offset and length arguments.  AUTHOR.'

