# blkdeactivate
# Autogenerated from man page /usr/share/man/man8/blkdeactivate.8.gz
# using Deroffing man parser
complete -c blkdeactivate -s e -l errors --description 'Show errors reported from tools called by blkdeactivate.'
complete -c blkdeactivate -s h -l help --description 'Display the help text.'
complete -c blkdeactivate -s u -l umount --description 'Unmount a mounted device before trying to deactivate it.'
complete -c blkdeactivate -s v -l verbose --description 'Run in verbose mode.'
complete -c blkdeactivate -s d -l dmoption --description 'Comma separated list of device-mapper specific options.'
complete -c blkdeactivate -s l -l lvmoption --description 'Comma separated list of LVM specific options.'

