# blkls
# Autogenerated from man page /usr/share/man/man1/blkls.1.gz
# using Deroffing man parser
complete -c blkls -s e --description 'Copy every block, including file system metadata blocks.'
complete -c blkls -s a --description 'Display all allocated blocks (same as -e if -A is also given).'
complete -c blkls -s A --description 'Display all unallocated blocks (same as -e if -… [See Man Page]'
complete -c blkls -s f --description 'Specifies the file system type.'
complete -c blkls -s i --description 'Identify the type of image file, such as raw.'
complete -c blkls -s o --description 'The sector offset where the file system starts in the image.'
complete -c blkls -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c blkls -s l --description 'List the data information in time machine format.'
complete -c blkls -s s --description 'Copy only the slack space of the image.'
complete -c blkls -s v --description 'Turn on verbose mode, output to stderr.'
complete -c blkls -s V --description 'Display version.'

