# blkstat
# Autogenerated from man page /usr/share/man/man1/blkstat.1.gz
# using Deroffing man parser
complete -c blkstat -s f --description 'Specify the file system type.'
complete -c blkstat -s i --description 'Identify the type of image file, such as raw.'
complete -c blkstat -s o --description 'The sector offset where the file system starts in the image.'
complete -c blkstat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c blkstat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c blkstat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

