# bootctl
# Autogenerated from man page /usr/share/man/man1/bootctl.1.gz
# using Deroffing man parser
complete -c bootctl -s h -l help --description 'Print a short help text and exit.'
complete -c bootctl -l version --description 'Print a short version string and exit.'

