# bridge
# Autogenerated from man page /usr/share/man/man8/bridge.8.gz
# using Deroffing man parser
complete -c bridge -s V -o Version --description 'print the version of the  bridge utility and exit.'
complete -c bridge -o 'V[ersion]' --description '.'
complete -c bridge -o 's[tatistics]' --description 'bridge link set dev DEV  [  cost COST  ] [  pri… [See Man Page]'
complete -c bridge -s s -o stats -o statistics --description 'output more information.'
complete -c bridge -o details --description 'option, the command becomes verbose.'

