# broadwayd
# Autogenerated from man page /usr/share/man/man1/broadwayd.1.gz
# using Deroffing man parser
complete -c broadwayd -l port --description 'Use PORT as the HTTP port, instead of the defau… [See Man Page]'
complete -c broadwayd -l address --description 'Use ADDRESS as the HTTP address, instead of the… [See Man Page]'

