# bssh
# Autogenerated from man page /usr/share/man/man1/bssh.1.gz
# using Deroffing man parser
complete -c bssh -s s -l ssh --description 'Browse for SSH servers (and only SSH servers) r… [See Man Page]'
complete -c bssh -s v -l vnc --description 'Browse for VNC servers (and only VNC servers) r… [See Man Page]'
complete -c bssh -s S -l shell --description 'Browse for both VNC and SSH servers regardless … [See Man Page]'
complete -c bssh -s d -l domain --description 'Browse in the specified domain.'
complete -c bssh -s h -l help --description 'Show help.'

