# busctl
# Autogenerated from man page /usr/share/man/man1/busctl.1.gz
# using Deroffing man parser
complete -c busctl -l address --description 'Connect to the bus specified by ADDRESS instead… [See Man Page]'
complete -c busctl -l show-machine --description 'When showing the list of endpoints, show a colu… [See Man Page]'
complete -c busctl -l unique --description 'When showing the list of endpoints, show only "… [See Man Page]'
complete -c busctl -l acquired --description 'The opposite of --unique \\(em only "well-known"… [See Man Page]'
complete -c busctl -l activatable --description 'When showing the list of endpoints, show only e… [See Man Page]'
complete -c busctl -l match --description 'When showing messages being exchanged, show onl… [See Man Page]'
complete -c busctl -l no-legend --description 'Do not print the legend, i. e.'
complete -c busctl -l user --description 'Talk to the service manager of the calling user… [See Man Page]'
complete -c busctl -l system --description 'Talk to the service manager of the system.'
complete -c busctl -s H -l host --description 'Execute the operation remotely.'
complete -c busctl -s M -l machine --description 'Execute operation on a local container.'
complete -c busctl -s h -l help --description 'Print a short help text and exit.'
complete -c busctl -l version --description 'Print a short version string and exit.'
complete -c busctl -l no-pager --description 'Do not pipe output into a pager.'

