# bvnc
# Autogenerated from man page /usr/share/man/man1/bvnc.1.gz
# using Deroffing man parser
complete -c bvnc -s s -l ssh --description 'Browse for SSH servers (and only SSH servers) r… [See Man Page]'
complete -c bvnc -s v -l vnc --description 'Browse for VNC servers (and only VNC servers) r… [See Man Page]'
complete -c bvnc -s S -l shell --description 'Browse for both VNC and SSH servers regardless … [See Man Page]'
complete -c bvnc -s d -l domain --description 'Browse in the specified domain.'
complete -c bvnc -s h -l help --description 'Show help.'

