# bzz
# Autogenerated from man page /usr/share/man/man1/bzz.1.gz
# using Deroffing man parser
complete -c bzz -s d --description 'Decoding mode.'
complete -c bzz -s e --description 'compresses the data from file inputfile  and wr… [See Man Page]'

