# c99
# Autogenerated from man page /usr/share/man/man1/c99.1p.gz
# using Deroffing man parser
complete -c c99 -s l --description 'option-arguments shall be compiled and linked t… [See Man Page]'
complete -c c99 -s c --description 'option is specified, for all pathname operands … [See Man Page]'
complete -c c99 -s E --description 'and all input files compile and link without er… [See Man Page]'
complete -c c99 -s o --description 'outfile option (if present) or to the file a. out .'
complete -c c99 -s L --description 'and.'
complete -c c99 -o cO --description 'need not be recognized by all implementations.'
complete -c c99 -s D --description '.'
complete -c c99 -s U --description 'option.  That is, if name is used in both a.'
complete -c c99 -s g --description 'Produce symbolic information in the object or e… [See Man Page]'
complete -c c99 -s I --description 'Change the algorithm for searching for headers … [See Man Page]'
complete -c c99 -s O --description 'Specify the level of code optimization.'
complete -c c99 -s s --description 'Produce object or executable files, or both, fr… [See Man Page]'
complete -c c99 -s v --description 'option.'
complete -c c99 -o D_REENTRANT --description 'being common).'

