# captest
# Autogenerated from man page /usr/share/man/man8/captest.8.gz
# using Deroffing man parser
complete -c captest -l drop-all --description 'This drops all capabilities and clears the bounding set.'
complete -c captest -l drop-caps --description 'This drops just traditional capabilities.'
complete -c captest -l id --description 'This changes to uid and gid 99, drops supplemen… [See Man Page]'
complete -c captest -l text --description 'This option outputs the effective capabilities … [See Man Page]'
complete -c captest -l lock --description 'This prevents the ability for child processes t… [See Man Page]'

