# ccache
# Autogenerated from man page /usr/share/man/man1/ccache.1.gz
# using Deroffing man parser
complete -c ccache -s c -l cleanup --description 'Clean up the cache by removing old cached files… [See Man Page]'
complete -c ccache -s C -l clear --description 'Clear the entire cache, removing all cached files.'
complete -c ccache -s F -l max-files --description 'Set the maximum number of files allowed in the cache.'
complete -c ccache -s h -l help --description 'Print an options summary page.'
complete -c ccache -s M -l max-size --description 'Set the maximum size of the files stored in the cache.'
complete -c ccache -s s -l show-stats --description 'Print the current statistics summary for the cache.'
complete -c ccache -s V -l version --description 'Print version and copyright information.'
complete -c ccache -s z -l zero-stats --description 'Zero the cache statistics (but not the configured limits).'
complete -c ccache -s g --description 'option is not used.'
complete -c ccache -o Wp --description 'compiler option other than.'
complete -c ccache -o MD --description 'and.'
complete -c ccache -o MMD --description 'oc o 2. 3.'
complete -c ccache -o Xpreprocessor --description 'oc o 2. 3.'
complete -c ccache -s E --description 'oc o 2. 3.'
complete -c ccache -o include --description '.'
complete -c ccache -s D --description 'oc o 2. 3.'
complete -c ccache -s I --description 'and similar compiler options.  oc o 2. 3.'
complete -c ccache -o MF --description 'oc o 2. 3.'
complete -c ccache -o fpch-preprocess --description 'compiler option when compiling.'

