# cfdisk
# Autogenerated from man page /usr/share/man/man8/cfdisk.8.gz
# using Deroffing man parser
complete -c cfdisk -s a -l arrow --description 'Use an arrow cursor instead of reverse video fo… [See Man Page]'
complete -c cfdisk -s g -l guess --description 'Do not use the geometry given by the disk drive… [See Man Page]'
complete -c cfdisk -s v -s V -l version --description 'Display version information and exit.'
complete -c cfdisk -s z -l zero --description 'Start with a zeroed partition table.'
complete -c cfdisk -s s -l sectors --description 'Override the number of cylinders, heads and sec… [See Man Page]'
complete -c cfdisk -s c -l cylinders --description '.'
complete -c cfdisk -s h -l heads --description '.'
complete -c cfdisk -s P -l print --description 'Print the partition table in the specified format(s).'

