# cg_diff
# Autogenerated from man page /usr/share/man/man1/cg_diff.1.gz
# using Deroffing man parser
complete -c cg_diff -s h -l help --description 'Show the help message.'
complete -c cg_diff -l version --description 'Show the version number.'
complete -c cg_diff -l mod-filename --description 'Specifies a Perl search-and-replace expression … [See Man Page]'
complete -c cg_diff -l mod-funcname --description 'Like --mod-filename, but for filenames.'

