# cg_merge
# Autogenerated from man page /usr/share/man/man1/cg_merge.1.gz
# using Deroffing man parser
complete -c cg_merge -s o --description 'Write the profile data to outfile rather than t… [See Man Page]'

