# chcpu
# Autogenerated from man page /usr/share/man/man8/chcpu.8.gz
# using Deroffing man parser
complete -c chcpu -s r -l rescan --description 'Trigger a rescan of CPUs.'
complete -c chcpu -s c -l configure --description 'Configure all specified CPUs.'
complete -c chcpu -s e -l enable --description 'Enable all specified CPUs.'
complete -c chcpu -s p -l dispatch --description 'Set the CPU dispatching  mode (polarization).'
complete -c chcpu -s d -l disable --description 'Disable all specified CPUs.'
complete -c chcpu -s g -l deconfigure --description 'Deconfigure all specified CPUs.'
complete -c chcpu -s h -l help --description 'Display help text and exit.'
complete -c chcpu -s V -l version --description 'Display version information and exit.  AUTHOR.'

