# checkmk
# Autogenerated from man page /usr/share/man/man1/checkmk.1.gz
# using Deroffing man parser
complete -c checkmk -l ------------------------------------------------ --description '/* A complete test example */.'

