# chmod
# Autogenerated from man page /usr/share/man/man1/chmod.1p.gz
# using Deroffing man parser
complete -c chmod -s l --description 'file writes an s in the position indicating tha… [See Man Page]'
complete -c chmod -s g --description '(that is, set the ``other\'\' permissions to the … [See Man Page]'

