# chronyd
# Autogenerated from man page /usr/share/man/man8/chronyd.8.gz
# using Deroffing man parser
complete -c chronyd -s P --description 'This option will select the SCHED_FIFO real-tim… [See Man Page]'
complete -c chronyd -s m --description 'This option will lock chronyd into RAM so that … [See Man Page]'
complete -c chronyd -s n --description 'When run in this mode, the program will not det… [See Man Page]'
complete -c chronyd -s d --description 'When run in this mode, the program will not det… [See Man Page]'
complete -c chronyd -s f --description 'This option can be used to specify an alternate… [See Man Page]'
complete -c chronyd -s r --description 'This option will reload sample histories for ea… [See Man Page]'
complete -c chronyd -s R --description 'When this option is used, the initstepslew dire… [See Man Page]'
complete -c chronyd -s s --description 'This option will set the system clock from the … [See Man Page]'
complete -c chronyd -s u --description 'When this option is used, chronyd will drop roo… [See Man Page]'
complete -c chronyd -s v --description 'This option displays chronyd\'s version number t… [See Man Page]'
complete -c chronyd -s 4 --description 'Resolve hostnames only to IPv4 addresses and cr… [See Man Page]'
complete -c chronyd -s 6 --description 'Resolve hostnames only to IPv6 addresses and cr… [See Man Page]'

