# chronyc
# Autogenerated from man page /usr/share/man/man1/chronyc.1.gz
# using Deroffing man parser
complete -c chronyc -s h --description 'specify hostname.'
complete -c chronyc -s p --description 'specify port-number.'
complete -c chronyc -s n --description 'display raw IP addresses (don\'t attempt to look up hostnames).'
complete -c chronyc -s 4 --description 'resolve hostnames only to IPv4 addresses.'
complete -c chronyc -s 6 --description 'resolve hostnames only to IPv6 addresses.'
complete -c chronyc -s m --description 'allow multiple commands to be specified on the command line.'
complete -c chronyc -s f --description 'This option can be used to specify an alternate… [See Man Page]'
complete -c chronyc -s a --description 'With this option chronyc will try to authentica… [See Man Page]'

