# cifs
# Autogenerated from man page /usr/share/man/man8/cifs.upcall.8.gz
# using Deroffing man parser
complete -c cifs -s c --description 'This option is deprecated and is currently ignored.'
complete -c cifs -l krb5conf -s k --description 'This option allows administrators to set an alt… [See Man Page]'
complete -c cifs -l keytab -s K --description 'This option allows administrators to specify a … [See Man Page]'
complete -c cifs -l trust-dns --description 'With krb5 upcalls, the name used as the host po… [See Man Page]'
complete -c cifs -l legacy-uid -s l --description 'Traditionally, the kernel has sent only a singl… [See Man Page]'

