# cmake-gui
# Autogenerated from man page /usr/share/man/man1/cmake-gui.1.gz
# using Deroffing man parser
complete -c cmake-gui -l copyright --description 'Print the CMake copyright and exit.'
complete -c cmake-gui -l help -o help -o usage -s h -s H --description 'Print usage information and exit.'
complete -c cmake-gui -l help-full --description 'Print full help and exit.'
complete -c cmake-gui -l help-html --description 'Print full help in HTML format.'
complete -c cmake-gui -l help-man --description 'Print full help as a UNIX man page and exit.'
complete -c cmake-gui -l version -o version --description 'Show program name/version banner and exit.'
complete -c cmake-gui -l ------------------ --description '.'
complete -c cmake-gui -l ------------------------------------------------- --description 'This convenience include finds if wxWindows is … [See Man Page]'

