# col
# Autogenerated from man page /usr/share/man/man1/col.1.gz
# using Darwin man parser
complete -c col -s b -l no-backspaces --description 'Do not output any backspaces, printing only the… [See Man Page]'
complete -c col -s f -l fine --description 'Forward half line feeds are permitted  fine mode.'
complete -c col -s p -l pass --description 'Force unknown control sequences to be passed through unchanged.'
complete -c col -s h -l tabs --description 'Output tabs instead of multiple spaces.'
complete -c col -s x -l spaces --description 'Output multiple spaces instead of tabs.'
complete -c col -s l -l lines --description 'Buffer at least  number lines in memory.'
complete -c col -s V -l version --description 'Display version information and exit.'

