# colcrt
# Autogenerated from man page /usr/share/man/man1/colcrt.1.gz
# using Deroffing man parser
complete -c colcrt -l no-underlining --description 'Suppress all underlining.'
complete -c colcrt -s 2 -l half-lines --description 'Causes all half-lines to be printed, effectivel… [See Man Page]'
complete -c colcrt -s V -l version --description 'Display version information and exit.'
complete -c colcrt -s h -l help --description 'Display help text and exit.'

