# columns
# Autogenerated from man page /usr/share/man/man1/columns.1.gz
# using Type1
complete -c columns -s W -l width --description 'Maximum Line Width.'
complete -c columns -s c -l columns --description 'Desired number of columns.'
complete -c columns -s w -l col-width --description 'Set width of each column.'
complete -c columns -l tab-width --description 'tab width.'
complete -c columns -l spread --description 'maximum spread added to column width.'
complete -c columns -l fill --description 'Fill lines with input.'
complete -c columns -s I -l indent --description 'Line prefix or indentation.'
complete -c columns -l first-indent --description 'First line prefix.'
complete -c columns -s f -l format --description 'Formatting string for each input.'
complete -c columns -s S -l separation --description 'Separation string - follows all but last.'
complete -c columns -l line-separation --description 'string at end of all lines but last.'
complete -c columns -l ending --description 'string at end of last line.'
complete -c columns -l by-columns --description 'Print entries in column order.'
complete -c columns -s s -l sort --description 'Sort input text. sp Causes the input text to be sorted.'
complete -c columns -s i -l input --description 'Input file (if not stdin).'
complete -c columns -s '?' -l help --description 'Display usage information and exit.'
complete -c columns -s '!' -l more-help --description 'Pass the extended usage information through a pager.'
complete -c columns -s '>' -l save-opts --description 'Save the option state to cfgfile.'
complete -c columns -s '<' -l load-opts -l no-load-opts --description 'Load options from cfgfile.'

