# command
# Autogenerated from man page /usr/share/man/man1/command.1p.gz
# using Deroffing man parser
complete -c command -s v --description 'or.'
complete -c command -s V --description 'option is used, the command utility shall provi… [See Man Page]'
complete -c command -s p --description 'Perform the command search using a default valu… [See Man Page]'

