# conky
# Autogenerated from man page /usr/share/man/man1/conky.1.gz
# using Deroffing man parser
complete -c conky -s V -l 'version\\*(T>' --description 'Prints version and exits.'
complete -c conky -l 'quiet\\*(T>' --description 'Run Conky in \'quiet mode\' (ie.  no output).'
complete -c conky -l 'debug\\*(T>' --description 'Increase debugging output, ie.  -DD for more debugging.'
complete -c conky -l alignment --description 'Text alignment on screen, {top,bottom,middle}_{… [See Man Page]'
complete -c conky -l 'double-buffer\\*(T>' --description 'Use double buffering (eliminates "flicker").'
complete -c conky -l config --description 'Config file to load instead of $HOME/. conkyrc.'
complete -c conky -l 'print-config\\*(T>' --description 'Print builtin default config to stdout.'
complete -c conky -l 'daemonize\\*(T>' --description 'Daemonize Conky, aka fork to background.'
complete -c conky -l font --description 'Font to use.'
complete -c conky -l 'help\\*(T>' --description 'Prints command line help and exits.'
complete -c conky -l 'own-window\\*(T>' --description 'Create own window to draw.'
complete -c conky -l text --description 'Text to render, remember single quotes, like -t \' $uptime \'.'
complete -c conky -l pause --description 'Time to pause before actually starting Conky.'
complete -c conky -l interval --description 'Update interval.'
complete -c conky -l window-id --description 'Window id to draw.'
complete -c conky -l display --description 'X11 display to use.'
complete -c conky -s l --description 'gradient, which makes the gradient values chang… [See Man Page]'

