# copydatabase
# Autogenerated from man page /usr/share/man/man1/copydatabase.1.gz
# using Deroffing man parser
complete -c copydatabase -l no-renumber --description 'Preserve the numbering of document ids (useful … [See Man Page]'
complete -c copydatabase -l help --description 'display this help and exit.'
complete -c copydatabase -l version --description 'output version information and exit.'

