# cpaldjvu
# Autogenerated from man page /usr/share/man/man1/cpaldjvu.1.gz
# using Deroffing man parser
complete -c cpaldjvu -o dpi --description 'Specify the resolution information encoded into… [See Man Page]'
complete -c cpaldjvu -o colors --description 'Specify a maximum number of distinct colors for… [See Man Page]'
complete -c cpaldjvu -o bgwhite --description 'Cause the background layer to use the lightest … [See Man Page]'
complete -c cpaldjvu -o verbose --description 'Display informational messages while running.'

