# cpupower-set
# Autogenerated from man page /usr/share/man/man1/cpupower-set.1.gz
# using Deroffing man parser
complete -c cpupower-set -l perf-bias -s b --description '.'
complete -c cpupower-set -l sched-mc -s m --description '.'
complete -c cpupower-set -l sched-smt -s s --description '.'

