# cpupower-frequency-info
# Autogenerated from man page /usr/share/man/man1/cpupower-frequency-info.1.gz
# using Type1
complete -c cpupower-frequency-info -s e -l debug --description 'Prints out debug information.'
complete -c cpupower-frequency-info -s f -l freq --description 'Get frequency the CPU currently runs at, accord… [See Man Page]'
complete -c cpupower-frequency-info -s w -l hwfreq --description 'Get frequency the CPU currently runs at, by rea… [See Man Page]'
complete -c cpupower-frequency-info -s l -l hwlimits --description 'Determine the minimum and maximum CPU frequency allowed.'
complete -c cpupower-frequency-info -s d -l driver --description 'Determines the used cpufreq kernel driver.'
complete -c cpupower-frequency-info -s p -l policy --description 'Gets the currently used cpufreq policy.'
complete -c cpupower-frequency-info -s g -l governors --description 'Determines available cpufreq governors.'
complete -c cpupower-frequency-info -s a -l related-cpus --description 'Determines which CPUs run at the same hardware frequency.'
complete -c cpupower-frequency-info -l affected-cpus --description 'Determines which CPUs need to have their freque… [See Man Page]'
complete -c cpupower-frequency-info -s s -l stats --description 'Shows cpufreq statistics if available.'
complete -c cpupower-frequency-info -s y -l latency --description 'Determines the maximum latency on CPU frequency changes.'
complete -c cpupower-frequency-info -s o -l proc --description 'Prints out information like provided by the /pr… [See Man Page]'
complete -c cpupower-frequency-info -s m -l human --description 'human-readable output for the -f, -w, -s and -y parameters.'

