# cron
# Autogenerated from man page /usr/share/man/man8/cron.8.gz
# using Type1
complete -c cron -s h --description 'Prints a help message and exits.'
complete -c cron -s i --description 'Disables inotify support.'
complete -c cron -s m --description 'This option allows you to specify a shell comma… [See Man Page]'
complete -c cron -s n --description 'Tells the daemon to run in the foreground.'
complete -c cron -s p --description 'Allows  Cron to accept any user set crontables.'
complete -c cron -s P --description 'Don\'t set PATH.'
complete -c cron -s c --description 'This option enables clustering support, as described below.'
complete -c cron -s s --description 'This option will direct  Cron to send the job o… [See Man Page]'

