# csepdjvu
# Autogenerated from man page /usr/share/man/man1/csepdjvu.1.gz
# using Deroffing man parser
complete -c csepdjvu -s d --description 'Specify the resolution information encoded into… [See Man Page]'
complete -c csepdjvu -s q --description 'Specify the encoding quality of the IW44 encode… [See Man Page]'
complete -c csepdjvu -s t --description 'Program   csepdjvu interprets certain comments … [See Man Page]'
complete -c csepdjvu -s v --description 'Display a brief message describing each page.'
complete -c csepdjvu -o slice --description 'of program c44 .'
complete -c csepdjvu -o vv --description 'Display extensive informational messages during encoding.'

