# csplit
# Autogenerated from man page /usr/share/man/man1/csplit.1p.gz
# using Deroffing man parser
complete -c csplit -s a --description 'flag to use the alphabetic filename generation … [See Man Page]'

