# cssh
# Autogenerated from man page /usr/share/man/man1/cssh.1.gz
# using Type1
complete -c cssh -l action -s a --description 'Run the command in each session, i. e.'
complete -c cssh -l cluster-file -s c --description 'Use supplied file as additional cluster file (s… [See Man Page]'
complete -c cssh -l config-file -s C --description 'Use supplied file as additional configuration f… [See Man Page]'
complete -c cssh -s d --description '\\s-1DEPRECATED.  \\s0 See \'--debug\'.'
complete -c cssh -s D --description '\\s-1DEPRECATED.  \\s0 See \'--debug\'.'
complete -c cssh -l debug --description 'Enable debugging.'
complete -c cssh -l evaluate -s e --description 'Display and evaluate the terminal and connectio… [See Man Page]'
complete -c cssh -l tile -s g -l no-tile -s G --description 'Enable|Disable window tiling (overriding the config file).'
complete -c cssh -l help -s h -s '?' --description 'Show basic help text, and exit.'
complete -c cssh -l man -s H --description 'Show full help test (the man page), and exit . ie n.'
complete -c cssh -l username -s l --description 'el.'
complete -c cssh -l options -s o -s x -s o --description 'el.'
complete -c cssh -l port -s p --description 'Specify an alternate port for connections.'
complete -c cssh -l autoquit -s q -l no-autoquit -s Q --description 'Enable|Disable automatically quiting after the … [See Man Page]'
complete -c cssh -l show-history -s s --description '\\s-1IN BETA:\\s0 Show history within console window.'
complete -c cssh -l term-args -s t --description 'el.'
complete -c cssh -l title -s T --description 'el.'
complete -c cssh -l output-config -s u --description 'Output the current configuration in the same fo… [See Man Page]'

