# ctags
# Autogenerated from man page /usr/share/man/man1/ctags.1p.gz
# using Deroffing man parser
complete -c ctags -s t --description 'option was omitted since the recognition of typ… [See Man Page]'
complete -c ctags -s v --description 'If the.'

