# ctrlaltdel
# Autogenerated from man page /usr/share/man/man8/ctrlaltdel.8.gz
# using Deroffing man parser
complete -c ctrlaltdel -s V -l version --description 'Display version information and exit.'
complete -c ctrlaltdel -s h -l help --description 'Display help text and exit.  FILES /etc/rc.'

