# cupsfilter
# Autogenerated from man page /usr/share/man/man8/cupsfilter.8.gz
# using Deroffing man parser
complete -c cupsfilter -s D --description 'br Delete the input file after conversion.'
complete -c cupsfilter -s U --description 'br Specifies the username passed to the filters.'
complete -c cupsfilter -s c --description 'br Uses the named cupsd. conf configuration file.'
complete -c cupsfilter -s d --description 'Uses information from the named printer.'
complete -c cupsfilter -s e --description 'br Use every filter from the PPD file.'
complete -c cupsfilter -s i --description 'br Specifies the source file type.'
complete -c cupsfilter -s j --description 'br Converts document N from the specified job.'
complete -c cupsfilter -s m --description 'br Specifies the destination file type.'
complete -c cupsfilter -s n --description 'br Specifies the number of copies to generate.'
complete -c cupsfilter -s o --description 'br Specifies options to pass to the CUPS filters.'
complete -c cupsfilter -s p --description 'br Specifies the PPD file to use.'
complete -c cupsfilter -s t --description 'br Specifies the document title.'
complete -c cupsfilter -s u --description '.'

