# cups-browsed
# Autogenerated from man page /usr/share/man/man8/cups-browsed.8.gz
# using Deroffing man parser
complete -c cups-browsed -s v -s d -l debug --description 'Debug mode.'
complete -c cups-browsed -l autoshutdown --description 'Auto shutdown mode, mode is off for no auto shu… [See Man Page]'
complete -c cups-browsed -l autoshutdown-timeout --description 'timeout tells after how many seconds cups-brows… [See Man Page]'

