# cut
# Autogenerated from man page /usr/share/man/man1/cut.1p.gz
# using Deroffing man parser
complete -c cut -s 5 --description 'Equivalent to 1,2,3,4,5,10.'
complete -c cut -s o --description 'Preserve the selected field order.'

