# cytune
# Autogenerated from man page /usr/share/man/man8/cytune.8.gz
# using Deroffing man parser
complete -c cytune -s s -l set-threshold --description 'Set the current threshold to  value characters.'
complete -c cytune -s t -l set-flush --description 'Set the current flush timeout to  value units.'
complete -c cytune -s g -l get-threshold --description 'Get the current threshold and timeout.'
complete -c cytune -s S -l set-default-threshold --description 'Set the default threshold to  value characters.'
complete -c cytune -s T -l set-default-flush --description 'Set the default flush timeout to  value units.'
complete -c cytune -s G -l get-glush --description 'Get the default threshold and flush timeout values.'
complete -c cytune -s q -l stats --description 'Gather statistics about the R tty .'
complete -c cytune -s i -l interval --description 'Statistics will be gathered every interval seconds.'

