# dbus-binding-tool
# Autogenerated from man page /usr/share/man/man1/dbus-binding-tool.1.gz
# using Deroffing man parser
complete -c dbus-binding-tool -l force --description 'Overwrite the output file if it already exists … [See Man Page]'
complete -c dbus-binding-tool -l help --description 'Display usage information.'
complete -c dbus-binding-tool -l ignore-unsupported --description 'If set, then unsupported signatures for <method… [See Man Page]'
complete -c dbus-binding-tool -l mode --description 'If the value is "glib-client", then client bind… [See Man Page]'
complete -c dbus-binding-tool -l output --description 'Specify the output file.'
complete -c dbus-binding-tool -l prefix --description 'Functions in the generated output are prefixed … [See Man Page]'
complete -c dbus-binding-tool -l version --description 'Display the version number of the dbus-binding-tool command.'

