# ddjvu
# Autogenerated from man page /usr/share/man/man1/ddjvu.1.gz
# using Deroffing man parser
complete -c ddjvu -o format --description 'Specify the output file formats.'
complete -c ddjvu -o quality --description 'below) often produces much smaller files.'
complete -c ddjvu -o page --description 'Specify which pages should be decoded.'
complete -c ddjvu -o mode --description 'Selects which layers of the DjVu image should be rendered.'
complete -c ddjvu -o skip --description 'Instead of aborting when encountering a corrupt… [See Man Page]'
complete -c ddjvu -s 1 --description '.'
complete -c ddjvu -o subsample --description 'This is equivalent to option.'
complete -c ddjvu -s n --description '.'
complete -c ddjvu -o scale --description 'Specify a magnification factor relative to the … [See Man Page]'
complete -c ddjvu -o size --description 'Specify the size of the full output image.'
complete -c ddjvu -o aspect --description '.'
complete -c ddjvu -o verbose --description 'Display informational messages describing the  … [See Man Page]'
complete -c ddjvu -o segment --description 'Specify an image segment to render.'
complete -c ddjvu -o foreground --description '.'
complete -c ddjvu -o background --description 'and.'
complete -c ddjvu -o black --description 'are shorthands for the .'

