# debugfs
# Autogenerated from man page /usr/share/man/man8/debugfs.reiserfs.8.gz
# using Deroffing man parser
complete -c debugfs -s j --description 'prints the contents of the journal.'
complete -c debugfs -s J --description 'prints the journal header.'
complete -c debugfs -s m --description 'prints the contents of the bitmap (slightly useful).'
complete -c debugfs -s B --description 'takes the list of bad blocks stored in the inte… [See Man Page]'
complete -c debugfs -s 1 --description 'prints the specified block of the filesystem.'
complete -c debugfs -s u --description 'builds the ReiserFS filesystem image with gunzip -c xxx.'
complete -c debugfs -s S --description 'When -S is not specified -p  .'
complete -c debugfs -o 'p.' --description 'result image is not the same as the original fi… [See Man Page]'
complete -c debugfs -s q --description 'When .'

