# debugreiserfs
# Autogenerated from man page /usr/share/man/man8/debugreiserfs.8.gz
# using Deroffing man parser
complete -c debugreiserfs -s j --description 'prints the contents of the journal.'
complete -c debugreiserfs -s J --description 'prints the journal header.'
complete -c debugreiserfs -s d --description 'prints the formatted nodes of the internal tree… [See Man Page]'
complete -c debugreiserfs -s D --description 'prints the formatted nodes of all used blocks o… [See Man Page]'
complete -c debugreiserfs -s m --description 'prints the contents of the bitmap (slightly useful).'
complete -c debugreiserfs -s o --description 'prints the objectid map (slightly useful).'
complete -c debugreiserfs -s B --description 'takes the list of bad blocks stored in the inte… [See Man Page]'
complete -c debugreiserfs -s 1 --description 'prints the specified block of the filesystem.'
complete -c debugreiserfs -s s --description '\\" scans the partition and prints a line when a… [See Man Page]'
complete -c debugreiserfs -s p --description 'extracts the filesystem\'s metadata with debugre… [See Man Page]'
complete -c debugreiserfs -s u --description 'builds the ReiserFS filesystem image with gunzip -c xxx.'
complete -c debugreiserfs -s S --description 'When -S is not specified -p  .'
complete -c debugreiserfs -o 'p.' --description 'result image is not the same as the original fi… [See Man Page]'
complete -c debugreiserfs -s q --description 'When .'

