# delta
# Autogenerated from man page /usr/share/man/man1/delta.1p.gz
# using Deroffing man parser
complete -c delta -s y --description 'option has an optional option-argument.'
complete -c delta -s r --description 'Uniquely identify which delta is to be made to the SCCS file.'
complete -c delta -s e --description 'on the same SCCS file were done by the same per… [See Man Page]'
complete -c delta -s s --description 'Suppress the report to standard output of the a… [See Man Page]'
complete -c delta -s n --description 'Specify retention of the edited g-file (normall… [See Man Page]'
complete -c delta -s g --description 'Specify a list (see get for the definition of l… [See Man Page]'
complete -c delta -s m --description 'Specify a modification request (MR) number that… [See Man Page]'
complete -c delta -o 'y[comment]' --description 'Describe the reason for making the delta.'
complete -c delta -s p --description 'Write (to standard output) the SCCS file differ… [See Man Page]'

