# delve
# Autogenerated from man page /usr/share/man/man1/delve.1.gz
# using Deroffing man parser
complete -c delve -s a --description 'show all terms in the database.'
complete -c delve -s r --description 'for term list(s).'
complete -c delve -s t --description 'for posting list(s).'
complete -c delve -s s -l stemmer --description 'set the stemming language, the default is \'none\'.'
complete -c delve -s 1 --description 'output one list entry per line.'
complete -c delve -s V --description 'output values for each document referred to.'
complete -c delve -o 'V<valueno>' --description 'output value valueno for each document referred… [See Man Page]'
complete -c delve -s d --description 'output document data for each document referred to.'
complete -c delve -s z --description 'for db, count documents with length 0.'
complete -c delve -s v --description 'extra info (wdf and len for postlist; wdf and t… [See Man Page]'
complete -c delve -l help --description 'display this help and exit.'
complete -c delve -l version --description 'output version information and exit.'

