# diff
# Autogenerated from man page /usr/share/man/man1/diff.1p.gz
# using Deroffing man parser
complete -c diff -s f --description 'Produce output in an alternative form, similar in format to.'
complete -c diff -l - --description '> Tue Jun 19 21:41:39 PDT 1990 RATIONALE The.'
complete -c diff -s h --description 'option was omitted because it was insufficientl… [See Man Page]'

