# djvm
# Autogenerated from man page /usr/share/man/man1/djvm.1.gz
# using Deroffing man parser
complete -c djvm -o 'c[reate]' --description 'Create a bundled DjVu document named  doc.'
complete -c djvm -o 'i[nsert]' --description 'Modify the bundled DjVu document named  doc.'
complete -c djvm -o 'd[elete]' --description 'Remove page  pagenum from the bundled multi-pag… [See Man Page]'
complete -c djvm -o 'l[ist]' --description 'List all component files in the multi-page DjVu document doc.'

