# djvmcvt
# Autogenerated from man page /usr/share/man/man1/djvmcvt.1.gz
# using Deroffing man parser
complete -c djvmcvt -o 'b[undled]' --description 'Create a bundled multi-page DjVu document named R docout.'
complete -c djvmcvt -o 'i[ndirect]' --description 'Create an indirect multi-page DjVu document.'

