# djvups
# Autogenerated from man page /usr/share/man/man1/djvups.1.gz
# using Deroffing man parser
complete -c djvups -o help --description 'Prints the list of recognized options.'
complete -c djvups -o verbose --description 'Displays a progress bar.'
complete -c djvups -o page --description 'Specify the document pages to be converted.'
complete -c djvups -o format --description 'Produce a PostScript file.   This is the default.'
complete -c djvups -o copies --description 'Specify the number of copies to print.'
complete -c djvups -o orientation --description 'Specify whether pages should be printed using t… [See Man Page]'
complete -c djvups -o mode --description 'Specify how pages should be decoded.'
complete -c djvups -o zoom --description 'Specify a zoom factor R zoomspec .'
complete -c djvups -o frame --description 'Specifying   yes causes the generation of a thi… [See Man Page]'
complete -c djvups -o cropmarks --description 'Specifying   yes causes the generation of crop … [See Man Page]'
complete -c djvups -o level --description 'Select the language level of the generated PostScript.'
complete -c djvups -o color --description 'The default value,  yes , generates a color PostScript file.'
complete -c djvups -o gray --description 'This option is equivalent to option  -color=no … [See Man Page]'
complete -c djvups -o colormatch --description 'The default value,  yes , generates a PostScrip… [See Man Page]'
complete -c djvups -o gamma --description 'Specify a gamma correction factor for the devic… [See Man Page]'
complete -c djvups -o booklet --description 'Turns the booklet printing mode on.'
complete -c djvups -o bookletmax --description 'Specifies the maximal number of pages per booklet.'
complete -c djvups -o bookletalign --description 'Specifies a positive or negative offset  applie… [See Man Page]'
complete -c djvups -o bookletfold --description 'Specifies the extra margin left  between both p… [See Man Page]'

