# djvudigital
# Autogenerated from man page /usr/share/man/man1/djvudigital.1.gz
# using Deroffing man parser
complete -c djvudigital -l verbose -s v --description 'Displays more informational messages while converting the file.'
complete -c djvudigital -l quiet -s q --description 'Do not display informational messages while con… [See Man Page]'
complete -c djvudigital -l dpi --description 'Specify the desired resolution to   resolution dots per inch.'
complete -c djvudigital -l psrotate --description 'Rotate the PostScript file by   angle degrees clockwise.'
complete -c djvudigital -l epsf --description 'Specify how to handle Encapsulated PostScript files.'
complete -c djvudigital -l exact-color --description 'Enables a more accurate rendering of the colors.'
complete -c djvudigital -l threshold --description 'Specify a threshold for the foreground/backgrou… [See Man Page]'
complete -c djvudigital -l bg-subsample --description 'Specify the background subsampling ratio.'
complete -c djvudigital -l bg-slices --description 'Specify the encoding quality of the background layer.'
complete -c djvudigital -l fg-colors --description 'Specify the maximum number of distinct colors i… [See Man Page]'
complete -c djvudigital -l fg-image-colors --description 'Specify the maximum number of distinct colors i… [See Man Page]'
complete -c djvudigital -l words --description 'Extract the text from the PostScript code and i… [See Man Page]'
complete -c djvudigital -l lines --description 'Extract the text from the PostScript code and i… [See Man Page]'
complete -c djvudigital -l gsarg --description 'Insert extra arguments on the GhostScript command line.'
complete -c djvudigital -l cseparg --description 'Insert extra arguments on the command line of p… [See Man Page]'
complete -c djvudigital -l sepfile --description 'Produces a separated data file instead of a DjVu file.'
complete -c djvudigital -l check --description 'Display the names of the two auxiliary programs… [See Man Page]'
complete -c djvudigital -l dryrun --description 'Simply display the ghostscript command line gen… [See Man Page]'
complete -c djvudigital -o slice --description 'option of command c44 .  The default is 72+11+10+10 .'
complete -c djvudigital -l help --description 'Display the manual page for  djvudigital .  GHOSTSCRIPT ISSUES.'

