# dmeventd
# Autogenerated from man page /usr/share/man/man8/dmeventd.8.gz
# using Deroffing man parser
complete -c dmeventd -s d --description 'Repeat from 1 to 3 times (-d, -dd, -ddd) to inc… [See Man Page]'
complete -c dmeventd -s f --description 'Don\'t fork, run in the foreground.'
complete -c dmeventd -s h -s '?' --description 'Show help information.'
complete -c dmeventd -s R --description 'Replace a running dmeventd instance.'
complete -c dmeventd -s V --description 'Show version of dmeventd.'

