# dtsdec
# Autogenerated from man page /usr/share/man/man1/dtsdec.1.gz
# using Deroffing man parser
complete -c dtsdec -s h --description 'display help and available audio modes.'
complete -c dtsdec -s s --description 'use program stream demultiplexer, track 0-7 or 0x80-0x87.'
complete -c dtsdec -s t --description 'use transport stream demultiplexer, pid 0x10-0x1ffe.'
complete -c dtsdec -s c --description 'use c implementation, disables all accelerations.'
complete -c dtsdec -s r --description 'disable dynamic range compression.'
complete -c dtsdec -s o --description 'use audio output driver `mode\'.'

