# dunst
# Autogenerated from man page /usr/share/man/man1/dunst.1.gz
# using Type1
complete -c dunst -o h/--help --description 'display help message.'
complete -c dunst -o fn --description 'defines the font or font set used.'
complete -c dunst -o lb/nb/cb --description 'defines the background color of low/normal/critical messages.'
complete -c dunst -o lf/nf/cf --description 'defines the foreground color of low/normal/critical messages.'
complete -c dunst -o to --description 'defines the default timeout.'
complete -c dunst -o lto/nto/cto --description 'timeouts for low/normal/critical messages.'
complete -c dunst -o key --description 'remove notification by pressing key.'
complete -c dunst -o all_key --description 'remove all notifications by pressing key.'
complete -c dunst -o history_key --description 'redisplay last notification by pressing key.'
complete -c dunst -o format --description 'defines the format of the message.  See \\s-1FORMAT. \\s0.'
complete -c dunst -o mon --description 'show the notification on monitor n.'
complete -c dunst -o follow --description 'display notifications on focused monitor.'
complete -c dunst -s s --description 'sort messages by urgency.'
complete -c dunst -o ns --description 'don\'t sort messages by urgency.'
complete -c dunst -o geometry --description 'The geometry of the message window.'
complete -c dunst -o lh/-line_height --description 'The height of a single line in pixel.'
complete -c dunst -o print --description 'Print notifications to stdout.'
complete -c dunst -o v/--version --description 'print version information.'

