# dwebp
# Autogenerated from man page /usr/share/man/man1/dwebp.1.gz
# using Deroffing man parser
complete -c dwebp -s h --description 'Print usage summary.'
complete -c dwebp -o version --description 'Print the version number (as major. minor. revision) and exit.'
complete -c dwebp -s o --description 'Specify the name of the output file (as PNG format by default).'
complete -c dwebp -o bmp --description 'Change the output format to uncompressed BMP.'
complete -c dwebp -o tiff --description 'Change the output format to uncompressed TIFF.'
complete -c dwebp -o pam --description 'Change the output format to PAM (retains alpha).'
complete -c dwebp -o ppm --description 'Change the output format to PPM (discards alpha).'
complete -c dwebp -o pgm --description 'Change the output format to PGM.'
complete -c dwebp -o yuv --description 'Change the output format to raw YUV.'
complete -c dwebp -o nofancy --description 'Don\'t use the fancy upscaler for YUV420.'
complete -c dwebp -o nofilter --description 'Don\'t use the in-loop filtering process even if… [See Man Page]'
complete -c dwebp -o dither --description 'Specify a dithering strength between 0 and 100.'
complete -c dwebp -o nodither --description 'Disable all dithering (default).'
complete -c dwebp -o mt --description 'Use multi-threading for decoding, if possible.'
complete -c dwebp -o crop --description 'Crop the decoded picture to a rectangle with to… [See Man Page]'
complete -c dwebp -o scale --description 'Rescale the decoded picture to dimension width x height.'
complete -c dwebp -s v --description 'Print extra information (decoding time in particular).'
complete -c dwebp -o noasm --description 'Disable all assembly optimizations.'

