# e2image
# Autogenerated from man page /usr/share/man/man8/e2image.8.gz
# using Deroffing man parser
complete -c e2image -s i --description 'option to those programs.'
complete -c e2image -s r --description 'or.'
complete -c e2image -s Q --description 'options, the filesystem must be unmounted or be… [See Man Page]'
complete -c e2image -s f --description 'option, but the resulting image file is very li… [See Man Page]'
complete -c e2image -l sparse --description 'option to the GNU version of cp .'
complete -c e2image -s I --description 'option will cause e2image to install the metada… [See Man Page]'
complete -c e2image -s s --description 'option can be specified.'
complete -c e2image -s a --description 'option can be specified to include all data.'
complete -c e2image -s p --description 'switch may be given to show progress.'
complete -c e2image -s c --description 'option which cause e2image to try reading a blo… [See Man Page]'
complete -c e2image -s n --description 'option will cause all of the writes to be no-op… [See Man Page]'
complete -c e2image -s o --description 'option.   Similarly the.'
complete -c e2image -s O --description 'option specifies the offset that should be seek… [See Man Page]'

