# easside-ng
# Autogenerated from man page /usr/share/man/man1/easside-ng.1.gz
# using Deroffing man parser
complete -c easside-ng -s h --description 'Shows the help screen.'
complete -c easside-ng -s v --description 'Victim BSSID (Optional).'
complete -c easside-ng -s m --description 'Source MAC address to be used (Optional).'
complete -c easside-ng -s i --description 'Source IP address to be used on the wireless LAN.'
complete -c easside-ng -s r --description 'IP address of the AP router.'
complete -c easside-ng -s s --description 'IP address of Buddy-ng server (Mandatory).'
complete -c easside-ng -s f --description 'Wireless interface to use (Mandatory).'
complete -c easside-ng -s c --description 'Lock interface to this channel (Optional).'
complete -c easside-ng -s n --description 'Determine Internet IP only.'

