# enca
# Autogenerated from man page /usr/share/man/man1/enca.1.gz
# using Type1
complete -c enca -s c -l auto-convert --description 'Equivalent to calling Enca as enconv.'
complete -c enca -s g -l guess --description 'Equivalent to calling Enca as enca.'
complete -c enca -s d -l details --description 'It used to print a few pages of details about t… [See Man Page]'
complete -c enca -s e -l enca-name --description 'Prints Enca\'s nice name of the charset, i. e.'
complete -c enca -s f -l human-readable --description 'Prints verbal description of the detected chars… [See Man Page]'
complete -c enca -s i -l iconv-name --description 'Prints how iconv(3) (and/or iconv(1)) calls the… [See Man Page]'
complete -c enca -s r -l rfc1345-name --description 'Prints RFC\\~1345 charset name.'
complete -c enca -s m -l mime-name --description 'Prints preferred MIME name of detected charset.'
complete -c enca -s s -l cstocs-name --description 'Prints how cstocs(1) calls the detected charset.'
complete -c enca -s n -l name --description 'Prints charset (encoding) name selected by WORD… [See Man Page]'
complete -c enca -s x -l convert-to --description 'Converts file to encoding ENC. sp The optional `.'
complete -c enca -s L -l language --description 'Sets language of input files to LANG.'
complete -c enca -s C -l try-converters --description 'Appends comma separated LIST to the list of con… [See Man Page]'
complete -c enca -s E -l external-converter-program --description 'Sets external converter program name to PATH.'
complete -c enca -s p -l with-filename --description 'Forces Enca to prefix each result with corresponding file name.'
complete -c enca -s P -l no-filename --description 'Forces Enca to not prefix results with file names.'
complete -c enca -s V -l verbose --description 'Increases verbosity level (each use increases it by one).'
complete -c enca -s h -l help --description 'Prints brief usage help.'
complete -c enca -s G -l license --description 'Prints full Enca license (through a pager, if possible).'
complete -c enca -s l -l list --description 'Prints list specified by WORD (can be abbreviat… [See Man Page]'

