# enchant
# Autogenerated from man page /usr/share/man/man1/enchant.1.gz
# using Deroffing man parser
complete -c enchant -s a --description 'List alternatives.'
complete -c enchant -s l --description 'List only the misspellings.'
complete -c enchant -s L --description 'Include the line number in the output.'
complete -c enchant -s v --description 'Prints the program\'s version.'

