# esdcompat
# Autogenerated from man page /usr/share/man/man1/esdcompat.1.gz
# using Deroffing man parser
complete -c esdcompat -s h -l help --description 'Show help.'
complete -c esdcompat -l version --description 'Show version information.'
complete -c esdcompat -o tcp -o promiscuous -s d -s b -s r -o as -o unix -o public -o terminate -o nobeeps -o trust -o port -o bind --description 'These options understood by the original esd ar… [See Man Page]'
complete -c esdcompat -o spawnpid -o spawnfd --description 'These internally used options understood by the… [See Man Page]'

