# ex
# Autogenerated from man page /usr/share/man/man1/ex.1p.gz
# using Deroffing man parser
complete -c ex -s c --description 'Specify an initial command to be executed in th… [See Man Page]'
complete -c ex -s r --description 'Recover the named files (see the EXTENDED DESCRIPTION section).'
complete -c ex -s t --description 'option is not specified, all other options, the… [See Man Page]'
complete -c ex -s R --description 'Set readonly edit option.'
complete -c ex -s s --description 'Prepare ex for batch use by taking the following actions:.'
complete -c ex -s v --description 'Begin in visual mode (see vi).'
complete -c ex -s w --description 'Set the value of the window editor option to size .'
complete -c ex -s 1 --description 'addr1 ,c addr2 ,c addr2 + count.'
complete -c ex -o '1)' --description '.'
complete -c ex -s i --description '(interactive mode).'
complete -c ex -s m --description '.'
complete -c ex -s e --description 'option of sed .'
complete -c ex -s x --description 'option, which did encryption based on the algor… [See Man Page]'
complete -c ex -s 2 --description 'Two lines before the current line.'

