# execstack
# Autogenerated from man page /usr/share/man/man8/execstack.8.gz
# using Deroffing man parser
complete -c execstack -s s -l set-execstack --description 'Mark binary or shared library as requiring executable stack.'
complete -c execstack -s c -l clear-execstack --description 'Mark binary or shared library as not requiring … [See Man Page]'
complete -c execstack -s q -l query --description 'Query executable stack marking of binaries and … [See Man Page]'
complete -c execstack -s V --description 'Print  execstack version and exit.'
complete -c execstack -s '?' -l help --description 'Print help message.'
complete -c execstack -l execstack --description 'or.'
complete -c execstack -l noexecstack --description 'assembler options), at link time (through.'
complete -c execstack -s z --description 'or.'
complete -c execstack -l usage --description 'Print a short usage message.'

