# export
# Autogenerated from man page /usr/share/man/man1/export.1p.gz
# using Deroffing man parser
complete -c export -s p --description 'is specified, export shall write to the standar… [See Man Page]'

