# extract_dts
# Autogenerated from man page /usr/share/man/man1/extract_dts.1.gz
# using Deroffing man parser
complete -c extract_dts -s h --description 'display help.'
complete -c extract_dts -s s --description 'set track number (0-7 or 0x80-0x87).'
complete -c extract_dts -s t --description 'use transport stream demultiplexer, pid 0x10-0x… [See Man Page]'

