# extract_mpeg2
# Autogenerated from man page /usr/share/man/man1/extract_mpeg2.1.gz
# using Deroffing man parser
complete -c extract_mpeg2 -s h --description 'display help.'
complete -c extract_mpeg2 -s s --description 'set track number (0-0xf or 0xe0-0xef).'
complete -c extract_mpeg2 -s t --description 'use transport stream demultiplexer, pid 0x10-0x… [See Man Page]'

