# ffind
# Autogenerated from man page /usr/share/man/man1/ffind.1.gz
# using Deroffing man parser
complete -c ffind -s a --description 'Find all occurrences of inode.'
complete -c ffind -s d --description 'Find deleted entries only.'
complete -c ffind -s f --description 'Identify the file system type of the image.'
complete -c ffind -s u --description 'Find undeleted entries only.'
complete -c ffind -s i --description 'Identify the type of image file, such as raw.'
complete -c ffind -s o --description 'The sector offset where the file system starts in the image.'
complete -c ffind -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c ffind -s v --description 'Verbose output to stderr.'
complete -c ffind -s V --description 'Display version.'

