# fftw-wisdom-to-conf
# Autogenerated from man page /usr/share/man/man1/fftw-wisdom-to-conf.1.gz
# using Deroffing man parser
complete -c fftw-wisdom-to-conf -s h -l help --description 'Display help on the command-line options and usage.'
complete -c fftw-wisdom-to-conf -s V -l version --description 'Print the version number and copyright information.'

