# filecap
# Autogenerated from man page /usr/share/man/man8/filecap.8.gz
# using Deroffing man parser
complete -c filecap -s a --description 'This tells the program to show all capabilities… [See Man Page]'
complete -c filecap -s d --description 'This dumps all capabilities for reference.'

