# FileCheck
# Autogenerated from man page /usr/share/man/man1/FileCheck.1.gz
# using Deroffing man parser
complete -c FileCheck -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c FileCheck -l check-prefix --description 'FileCheck searches the contents of match-filena… [See Man Page]'
complete -c FileCheck -l input-file --description 'File to check (defaults to stdin). UNINDENT NDENT 0. 0.'
complete -c FileCheck -l strict-whitespace --description 'By default, FileCheck canonicalizes input horiz… [See Man Page]'
complete -c FileCheck -o version --description 'Show the version number of this program.'

