# flock
# Autogenerated from man page /usr/share/man/man1/flock.1.gz
# using Deroffing man parser
complete -c flock -s s -l shared --description 'Obtain a shared lock, sometimes called a read lock.'
complete -c flock -s x -s e -l exclusive --description 'Obtain an exclusive lock, sometimes called a write lock.'
complete -c flock -s u -l unlock --description 'Drop a lock.'
complete -c flock -s n -l nb -l nonblock --description 'Fail rather than wait if the lock cannot be imm… [See Man Page]'
complete -c flock -s w -l wait -l timeout --description 'Fail if the lock cannot be acquired within R seconds .'
complete -c flock -s o -l close --description 'Close the file descriptor on which the lock is … [See Man Page]'
complete -c flock -s E -l conflict-exit-code --description 'The exit code used when the -n option is in use… [See Man Page]'
complete -c flock -s c -l command --description 'Pass a single R command , without arguments, to… [See Man Page]'
complete -c flock -s h -l help --description 'Display help text and exit.'
complete -c flock -s V -l version --description 'Display version information and exit.  EXAMPLES.'

