# fls
# Autogenerated from man page /usr/share/man/man1/fls.1.gz
# using Deroffing man parser
complete -c fls -s a --description 'Display the ". " and ".'
complete -c fls -s d --description 'Display deleted entries only.'
complete -c fls -s D --description 'Display directory entries only.'
complete -c fls -s f --description 'The type of file system.'
complete -c fls -s F --description 'Display file (all non-directory) entries only.'
complete -c fls -s l --description 'Display file details in long format.'
complete -c fls -s m --description 'Display files in time machine format so that a … [See Man Page]'
complete -c fls -s p --description 'Display the full path for each entry.'
complete -c fls -s r --description 'Recursively display directories.'
complete -c fls -s s --description 'The time skew of the original system in seconds.'
complete -c fls -s i --description 'Identify the type of image file, such as raw.'
complete -c fls -s o --description 'The sector offset where the file system starts in the image.'
complete -c fls -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c fls -s u --description 'Display undeleted entries only.'
complete -c fls -s v --description 'Verbose output to stderr.'
complete -c fls -s V --description 'Display version.'
complete -c fls -s z --description 'The ASCII string of the time zone of the original system.'

