# fort77
# Autogenerated from man page /usr/share/man/man1/fort77.1p.gz
# using Deroffing man parser
complete -c fort77 -s c --description 'option is present, for all pathname operands of… [See Man Page]'
complete -c fort77 -s o --description 'option (if present) or to the file a. out .'
complete -c fort77 -s l --description 'library operands have the format of options, bu… [See Man Page]'
complete -c fort77 -s L --description 'options is significant.'
complete -c fort77 -o cg --description 'need not be recognized by all implementations.'
complete -c fort77 -s g --description 'Produce symbolic information in the object or e… [See Man Page]'
complete -c fort77 -s s --description 'Produce object or executable files, or both, fr… [See Man Page]'
complete -c fort77 -s O --description 'Specify the level of code optimization.'
complete -c fort77 -s w --description 'Suppress warnings.'
complete -c fort77 -o onetrip --description 'option was not included in this volume of POSIX.'
complete -c fort77 -s V --description 'option overlapped with historical vendor practi… [See Man Page]'
complete -c fort77 -s I --description 'option in this version of this volume of POSIX.'
complete -c fort77 -s N --description 'were Booleans: optimize and do not optimize (wi… [See Man Page]'
complete -c fort77 -o gc --description 'as if it were.'

