# fsadm
# Autogenerated from man page /usr/share/man/man8/fsadm.8.gz
# using Deroffing man parser
complete -c fsadm -s e -l ext-offline --description 'Unmount ext2/ext3/ext4 filesystem before doing resize.'
complete -c fsadm -s f -l force --description 'Bypass some sanity checks.'
complete -c fsadm -s h -l help --description 'Display the help text.'
complete -c fsadm -s n -l dry-run --description 'Print commands without running them.'
complete -c fsadm -s v -l verbose --description 'Be more verbose.'
complete -c fsadm -s y -l yes --description 'Answer "yes" at any prompts.'

