# fsc
# Autogenerated from man page /usr/share/man/man1/fsc.1.gz
# using Deroffing man parser
complete -c fsc -o reset --description 'Reset compile server caches.'
complete -c fsc -o shutdown --description 'Shut down the compilation daemon.'
complete -c fsc -o server --description 'Specify compile server host at port number.'
complete -c fsc -o 'J<flag>' --description 'Pass <flag> directly to the Java VM for the compilation daemon.'

