# fsfreeze
# Autogenerated from man page /usr/share/man/man8/fsfreeze.8.gz
# using Deroffing man parser
complete -c fsfreeze -s h -l help --description 'Display help text and exit.'
complete -c fsfreeze -s f -l freeze --description 'This option requests the specified a filesystem… [See Man Page]'
complete -c fsfreeze -s u -l unfreeze --description 'This option is used to un-freeze the filesystem… [See Man Page]'
complete -c fsfreeze -s V -l version --description 'Display version information and exit.  AUTHOR.'

