# fsstat
# Autogenerated from man page /usr/share/man/man1/fsstat.1.gz
# using Deroffing man parser
complete -c fsstat -s t --description 'Print the file system type only.'
complete -c fsstat -s f --description 'Specify the file system type.'
complete -c fsstat -s i --description 'Identify the type of image file, such as raw.'
complete -c fsstat -s o --description 'The sector offset where the file system starts in the image.'
complete -c fsstat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c fsstat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c fsstat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

