# gdbserver
# Autogenerated from man page /usr/share/man/man1/gdbserver.1.gz
# using Type1
complete -c gdbserver -l help --description 'List all options, with brief explanations.'
complete -c gdbserver -l version --description 'This option causes gdbserver to print its versi… [See Man Page]'
complete -c gdbserver -l attach --description 'gdbserver will attach to a running program.   The syntax is: .'
complete -c gdbserver -l multi --description 'To start \\f(CW\\*(C`gdbserver\\*(C\' without suppl… [See Man Page]'
complete -c gdbserver -l debug --description 'Instruct \\f(CW\\*(C`gdbserver\\*(C\' to display ex… [See Man Page]'
complete -c gdbserver -l remote-debug --description 'Instruct \\f(CW\\*(C`gdbserver\\*(C\' to display re… [See Man Page]'
complete -c gdbserver -l wrapper --description 'Specify a wrapper to launch programs for debugging.'

