# geeqie
# Autogenerated from man page /usr/share/man/man1/geeqie.1.gz
# using Deroffing man parser
complete -c geeqie -l with-tools --description 'Force the toolbox to be shown. br.'
complete -c geeqie -s t -l without-tools --description 'Force the toolbox to be hidden. br.'
complete -c geeqie -s f -l fullscreen --description 'Start in full screen mode. br.'
complete -c geeqie -s s -l slideshow --description 'Start in slideshow mode. br.'
complete -c geeqie -s l -l list --description 'Open collection window for command line files. br.'
complete -c geeqie -l debug --description 'Turn on debugging output. br.'
complete -c geeqie -s v -l version --description 'Print version. br.'
complete -c geeqie -s h -l help --description 'Print command line options.'

