# gentest
# Autogenerated from man page /usr/share/man/man1/gentest.1.gz
# using Deroffing man parser
complete -c gentest -s U --description 'Specify the user and password to use when loggi… [See Man Page]'
complete -c gentest -s s --description 'Seed the random number generator with the specified value.'
complete -c gentest -s o --description 'Set the number of operations to perform.'
complete -c gentest -s a --description 'Print the operations that are performed.'
complete -c gentest -s A --description 'Backtrack to find minimal number of operations … [See Man Page]'
complete -c gentest -s i --description 'Specify a file containing the names of fields t… [See Man Page]'
complete -c gentest -s O --description 'Enable oplocks.'
complete -c gentest -s S --description 'Set preset seeds file.  The default is gentest_seeds. dat.'
complete -c gentest -s L --description 'Use preset seeds.'
complete -c gentest -s F --description 'Fast reconnect (just close files).'
complete -c gentest -s C --description 'Continuous analysis mode.'
complete -c gentest -s X --description 'Analyse even when the test succeeded.'

