# get-iab
# Autogenerated from man page /usr/share/man/man1/get-iab.1.gz
# using Deroffing man parser
complete -c get-iab -s h --description 'Display a brief usage message and exit.'
complete -c get-iab -s f --description 'Write the output to the specified file instead … [See Man Page]'
complete -c get-iab -s u --description 'Use the specified URL to fetch the raw IAB data… [See Man Page]'
complete -c get-iab -s v --description 'Display verbose progress messages.  FILES.'

