# get-oui
# Autogenerated from man page /usr/share/man/man1/get-oui.1.gz
# using Deroffing man parser
complete -c get-oui -s h --description 'Display a brief usage message and exit.'
complete -c get-oui -s f --description 'Write the output to the specified file instead … [See Man Page]'
complete -c get-oui -s u --description 'Use the specified URL to fetch the raw OUI data… [See Man Page]'
complete -c get-oui -s v --description 'Display verbose progress messages.  FILES.'

