# getfattr
# Autogenerated from man page /usr/share/man/man1/getfattr.1.gz
# using Deroffing man parser
complete -c getfattr -s n -l name --description 'Dump the value of the named extended attribute … [See Man Page]'
complete -c getfattr -s d -l dump --description 'Dump the values of all extended attributes asso… [See Man Page]'
complete -c getfattr -s e -l encoding --description 'Encode values after retrieving them.'
complete -c getfattr -s h -l no-dereference --description 'Do not dereference symlinks.'
complete -c getfattr -s m -l match --description 'Only include attributes with names matching the… [See Man Page]'
complete -c getfattr -l absolute-names --description 'Do not strip leading slash characters (\'/\').'
complete -c getfattr -l only-values --description 'Dump out the raw extended attribute value(s) wi… [See Man Page]'
complete -c getfattr -s R -l recursive --description 'List the attributes of all files and directories recursively.'
complete -c getfattr -s L -l logical --description 'Logical walk, follow symbolic links to directories.'
complete -c getfattr -s P -l physical --description 'Physical walk, do not follow symbolic links to directories.'
complete -c getfattr -l version --description 'Print the version of  getfattr and exit.'
complete -c getfattr -l help --description 'Print help explaining the command line options.'

