# gif2rgb
# Autogenerated from man page /usr/share/man/man1/gif2rgb.1.gz
# using Deroffing man parser
complete -c gif2rgb -s v --description 'Verbose mode (show progress).'
complete -c gif2rgb -s 1 --description 'Only one file in the format of RGBRGB.'
complete -c gif2rgb -s c --description 'Specifies number of colors to use in RGB-to-GIF… [See Man Page]'
complete -c gif2rgb -s s --description 'Sets RGB-to-GIF conversion mode and specifies t… [See Man Page]'
complete -c gif2rgb -s o --description 'specifies the name of the out file (see also `-1\\*(Aq above).'
complete -c gif2rgb -s h --description 'Print one line of command line help, similar to Usage above.'

