# gif2raw
# Autogenerated from man page /usr/share/man/man1/gif2raw.1.gz
# using Deroffing man parser
complete -c gif2raw -s v --description 'Verbose mode (show progress).'
complete -c gif2raw -s s --description 'Enables raw-to-GIF conversion.'
complete -c gif2raw -s t --description 'Textify.'
complete -c gif2raw -s p --description 'Valid in raw-to-GIF mode only, Color map to loa… [See Man Page]'
complete -c gif2raw -s h --description 'Print one line of command line help, similar to Usage above.'

