# gif2webp
# Autogenerated from man page /usr/share/man/man1/gif2webp.1.gz
# using Deroffing man parser
complete -c gif2webp -s o --description 'Specify the name of the output WebP file.'
complete -c gif2webp -s h -o help --description 'Usage information.'
complete -c gif2webp -o version --description 'Print the version number (as major. minor. revision) and exit.'
complete -c gif2webp -o lossy --description 'Encode the image using lossy compression.'
complete -c gif2webp -o mixed --description 'Mixed compression mode: optimize compression of… [See Man Page]'
complete -c gif2webp -s q --description 'Specify the compression factor for RGB channels… [See Man Page]'
complete -c gif2webp -s m --description 'Specify the compression method to use.'
complete -c gif2webp -o kmax --description 'Specify the minimum and maximum distance betwee… [See Man Page]'
complete -c gif2webp -o metadata --description 'A comma separated list of metadata to copy from… [See Man Page]'
complete -c gif2webp -s f --description 'For lossy encoding only (specified by the -lossy option).'
complete -c gif2webp -o mt --description 'Use multi-threading for encoding, if possible.'
complete -c gif2webp -s v --description 'Print extra information.'
complete -c gif2webp -o kmin --description '.'
complete -c gif2webp -o quiet --description 'Do not print anything.'

