# gifinto
# Autogenerated from man page /usr/share/man/man1/gifinto.1.gz
# using Deroffing man parser
complete -c gifinto -s v --description 'Verbose mode (show progress).'
complete -c gifinto -s s --description 'If file is less than MinFileSize, it is deleted… [See Man Page]'
complete -c gifinto -s h --description 'Print one line of command line help, similar to Usage above.'

