# git-count-objects
# Autogenerated from man page /usr/share/man/man1/git-count-objects.1.gz
# using Deroffing man parser
complete -c git-count-objects -s v -l verbose --description 'Report in more detail: .'
complete -c git-count-objects -s H -l human-readable --description 'Print sizes in human readable format.'

