# git-symbolic-ref
# Autogenerated from man page /usr/share/man/man1/git-symbolic-ref.1.gz
# using Deroffing man parser
complete -c git-symbolic-ref -s d -l delete --description 'Delete the symbolic ref <name>.'
complete -c git-symbolic-ref -s q -l quiet --description 'Do not issue an error message if the <name> is … [See Man Page]'
complete -c git-symbolic-ref -l short --description 'When showing the value of <name> as a symbolic … [See Man Page]'
complete -c git-symbolic-ref -s m --description 'Update the reflog for <name> with <reason>.'

