# git-status
# Autogenerated from man page /usr/share/man/man1/git-status.1.gz
# using Deroffing man parser
complete -c git-status -s s -l short --description 'Give the output in the short-format.'
complete -c git-status -s b -l branch --description 'Show the branch and tracking info even in short-format.'
complete -c git-status -l porcelain --description 'Give the output in an easy-to-parse format for scripts.'
complete -c git-status -l long --description 'Give the output in the long-format.  This is the default.'
complete -c git-status -o 'u[<mode>]' -l 'untracked-files[' --description 'Show untracked files.'
complete -c git-status -l 'ignore-submodules[' --description 'Ignore changes to submodules when looking for changes.'
complete -c git-status -l ignored --description 'Show ignored files as well.'
complete -c git-status -s z --description 'Terminate entries with NUL, instead of LF.'
complete -c git-status -l 'column[' -l no-column --description 'Display untracked files in columns.'
complete -c git-status -s u --description 'option is not used, untracked files and directo… [See Man Page]'
complete -c git-status -l ----------------------------------------------- --description '          [MD]   not updated M        [ MD]   u… [See Man Page]'

