# git-cat-file
# Autogenerated from man page /usr/share/man/man1/git-cat-file.1.gz
# using Deroffing man parser
complete -c git-cat-file -s t --description 'Instead of the content, show the object type id… [See Man Page]'
complete -c git-cat-file -s s --description 'Instead of the content, show the object size id… [See Man Page]'
complete -c git-cat-file -s e --description 'Suppress all output; instead exit with zero sta… [See Man Page]'
complete -c git-cat-file -s p --description 'Pretty-print the contents of <object> based on its type.'
complete -c git-cat-file -l textconv --description 'Show the content as transformed by a textconv filter.'
complete -c git-cat-file -l batch -l batch --description 'Print object information and contents for each … [See Man Page]'
complete -c git-cat-file -l batch-check -l batch-check --description 'Print object information for each object provided on stdin.'

