# glib-mkenums
# Autogenerated from man page /usr/share/man/man1/glib-mkenums.1.gz
# using Deroffing man parser
complete -c glib-mkenums -l fhead --description 'Put out TEXT prior to processing input files.'
complete -c glib-mkenums -l fprod --description 'Put out TEXT everytime a new input file is being processed.'
complete -c glib-mkenums -l ftail --description 'Put out TEXT after all input files have been processed.'
complete -c glib-mkenums -l eprod --description 'Put out TEXT everytime an enum is encountered i… [See Man Page]'
complete -c glib-mkenums -l vhead --description 'Put out TEXT before iterating over the set of v… [See Man Page]'
complete -c glib-mkenums -l vprod --description 'Put out TEXT for every value of an enum.'
complete -c glib-mkenums -l vtail --description 'Put out TEXT after iterating over all values of an enum.'
complete -c glib-mkenums -l comments --description 'Template for auto-generated comments, the defau… [See Man Page]'
complete -c glib-mkenums -l template --description 'Read templates from the given file.'
complete -c glib-mkenums -l identifier-prefix --description 'Indicates what portion of the enum name should … [See Man Page]'
complete -c glib-mkenums -l symbol-prefix --description 'Indicates what prefix should be used to corresp… [See Man Page]'
complete -c glib-mkenums -l help --description 'Print brief help and exit.'
complete -c glib-mkenums -l version --description 'Print version and exit.'

