# glib-compile-resources
# Autogenerated from man page /usr/share/man/man1/glib-compile-resources.1.gz
# using Deroffing man parser
complete -c glib-compile-resources -s h -l help --description 'Print help and exit.'
complete -c glib-compile-resources -l target --description 'Store the compiled resources in the file TARGET.'
complete -c glib-compile-resources -l sourcedir --description 'The files referenced in FILE are loaded from this directory.'
complete -c glib-compile-resources -l generate-source --description 'Instead of a writing the resource bundle in bin… [See Man Page]'
complete -c glib-compile-resources -l generate-header --description 'Generate a header file for use with C code gene… [See Man Page]'
complete -c glib-compile-resources -l generate-dependencies --description 'Prints the list of files that the resource bund… [See Man Page]'
complete -c glib-compile-resources -l c-name --description 'Specify the prefix used for the C identifiers i… [See Man Page]'
complete -c glib-compile-resources -l manual-register --description 'By default code generated by --generate-source … [See Man Page]'
complete -c glib-compile-resources -l internal --description 'By default code generated by --generate-source … [See Man Page]'
complete -c glib-compile-resources -l generate --description '.'
complete -c glib-compile-resources -l 'generate-source.' --description '.'
complete -c glib-compile-resources -l 'generate-header.' --description '.'

