# glib-compile-schemas
# Autogenerated from man page /usr/share/man/man1/glib-compile-schemas.1.gz
# using Deroffing man parser
complete -c glib-compile-schemas -s h -l help --description 'Print help and exit.'
complete -c glib-compile-schemas -l targetdir --description 'Store gschemas.'
complete -c glib-compile-schemas -l dry-run --description 'Don\\*(Aqt write gschemas. compiled.'
complete -c glib-compile-schemas -l allow-any-name --description 'Do not enforce restrictions on key names.'

