# glib-genmarshal
# Autogenerated from man page /usr/share/man/man1/glib-genmarshal.1.gz
# using Deroffing man parser
complete -c glib-genmarshal -l header --description 'Generate header file contents of the marshallers.'
complete -c glib-genmarshal -l body --description 'Generate C code file contents of the marshallers.'
complete -c glib-genmarshal -l prefix --description 'Specify marshaller prefix.'
complete -c glib-genmarshal -l skip-source --description 'Skip source location remarks in generated comments.'
complete -c glib-genmarshal -l stdinc --description 'Use the standard marshallers of the GObject lib… [See Man Page]'
complete -c glib-genmarshal -l nostdinc --description 'Do not use the standard marshallers of the GObj… [See Man Page]'
complete -c glib-genmarshal -l internal --description 'Mark generated functions as internal, using G_GNUC_INTERNAL.'
complete -c glib-genmarshal -l valist-marshallers --description 'Generate valist marshallers, for use with g_sig… [See Man Page]'
complete -c glib-genmarshal -s v -l version --description 'Print version information.'
complete -c glib-genmarshal -l g-fatal-warnings --description 'Make warnings fatal, that is, exit immediately … [See Man Page]'
complete -c glib-genmarshal -s h -l help --description 'Print brief help and exit.'

