# gpg-preset-passphrase
# Autogenerated from man page /usr/share/man/man1/gpg-preset-passphrase.1.gz
# using Deroffing man parser
complete -c gpg-preset-passphrase -l preset --description 'Preset a passphrase.  This is what you usually will use.'
complete -c gpg-preset-passphrase -l forget --description 'Flush the passphrase for the given cache ID from the cache.'
complete -c gpg-preset-passphrase -l - --description 'SIGHUP to it).'
complete -c gpg-preset-passphrase -l 'allow-preset-passphrase.' --description 'gpg-preset-passphrase is invoked this way: gpg-… [See Man Page]'
complete -c gpg-preset-passphrase -s v --description '.'
complete -c gpg-preset-passphrase -l verbose --description 'Output additional information while running.'
complete -c gpg-preset-passphrase -s P --description '.'
complete -c gpg-preset-passphrase -l passphrase --description 'Instead of reading the passphrase from stdin, u… [See Man Page]'

