# gpgv2
# Autogenerated from man page /usr/share/man/man1/gpgv2.1.gz
# using Deroffing man parser
complete -c gpgv2 -s v --description 'Gives more information during processing.'
complete -c gpgv2 -s q --description 'Try to be as quiet as possible.'
complete -c gpgv2 -l keyring --description 'Add file to the list of keyrings.'
complete -c gpgv2 -l status-fd --description 'Write special status strings to the file descriptor n.'
complete -c gpgv2 -l logger-fd --description 'Write log output to file descriptor n and not to stderr.'
complete -c gpgv2 -l ignore-time-conflict --description 'GnuPG normally checks that the timestamps assoc… [See Man Page]'
complete -c gpgv2 -l verbose --description '.'
complete -c gpgv2 -l quiet --description '.'
complete -c gpgv2 -l homedir --description 'Set the name of the home directory to dir.'

