# grc
# Autogenerated from man page /usr/share/man/man1/grc.1.gz
# using Deroffing man parser
complete -c grc -l help --description 'Show summary of options.'
complete -c grc -l version --description 'Display version.'
complete -c grc -s e -l stderr --description 'Redirect error output.'
complete -c grc -s s -l stdout --description 'Redirect standard output.'
complete -c grc -l colour --description 'x is one of on off auto.'

