# gst-play-1
# Autogenerated from man page /usr/share/man/man1/gst-play-1.0.1.gz
# using Type1
complete -c gst-play-1 -l help --description 'Print help synopsis and available command line options.'
complete -c gst-play-1 -l version --description 'Print version and exit.'
complete -c gst-play-1 -l audiosink --description 'Use SOMESINK as audio sink instead of autoaudiosink.'
complete -c gst-play-1 -l videosink --description 'Use SOMESINK as video sink instead of autovideosink.'

