# gst-typefind-1
# Autogenerated from man page /usr/share/man/man1/gst-typefind-1.0.1.gz
# using Type1
complete -c gst-typefind-1 -l help --description 'Print help synopsis and available FLAGS.'
complete -c gst-typefind-1 -l gst-info-mask --description 'GStreamer info flags to set (list with --help).'
complete -c gst-typefind-1 -l gst-debug-mask --description 'GStreamer debugging flags to set (list with --help).'
complete -c gst-typefind-1 -l gst-mask --description 'GStreamer info and debugging flags to set (list with --help).'
complete -c gst-typefind-1 -l gst-plugin-spew --description 'GStreamer info flags to set Enable printout of … [See Man Page]'

