# halt
# Autogenerated from man page /usr/share/man/man8/halt.8.gz
# using Deroffing man parser
complete -c halt -l help --description 'Print a short help text and exit.'
complete -c halt -l halt --description 'Halt the machine, regardless of which one of th… [See Man Page]'
complete -c halt -s p -l poweroff --description 'Power-off the machine, regardless of which one … [See Man Page]'
complete -c halt -l reboot --description 'Reboot the machine, regardless of which one of … [See Man Page]'
complete -c halt -s f -l force --description 'Force immediate halt, power-off, reboot.'
complete -c halt -s w -l wtmp-only --description 'Only write wtmp shutdown entry, do not actually… [See Man Page]'
complete -c halt -s d -l no-wtmp --description 'Do not write wtmp shutdown entry.'
complete -c halt -l no-wall --description 'Do not send wall message before halt, power-off, reboot.'

