# hash
# Autogenerated from man page /usr/share/man/man1/hash.1p.gz
# using Deroffing man parser
complete -c hash -s r --description 'Forget all previously remembered utility locations.'
complete -c hash -s t --description 'in which case utilities found through normal co… [See Man Page]'

