# hexdump
# Autogenerated from man page /usr/share/man/man1/hexdump.1.gz
# using Deroffing man parser
complete -c hexdump -s b -l one-byte-octal --description 'One-byte octal display.'
complete -c hexdump -s c -l one-byte-char --description 'One-byte character display.'
complete -c hexdump -s C -l canonical --description 'Canonical hex+ASCII display.'
complete -c hexdump -s d -l two-bytes-decimal --description 'Two-byte decimal display.'
complete -c hexdump -s e -l format --description 'Specify a format string to be used for displaying data.'
complete -c hexdump -s r -l format-file --description 'Specify a file that contains one or more newlin… [See Man Page]'
complete -c hexdump -s n -l length --description 'Interpret only  length bytes of input.'
complete -c hexdump -s o -l two-bytes-octal --description 'Two-byte octal display.'
complete -c hexdump -s s -l skip --description 'Skip  offset bytes from the beginning of the input.'
complete -c hexdump -s v -l no-squeezing --description 'The  -v option causes  hexdump to display all input data.'
complete -c hexdump -s x -l two-bytes-hex --description 'Two-byte hexadecimal display.'
complete -c hexdump -s f --description 'options, in the order that they were specified.'

