# hfind
# Autogenerated from man page /usr/share/man/man1/hfind.1.gz
# using Deroffing man parser
complete -c hfind -s i --description 'Create an index file for the database.'
complete -c hfind -s f --description 'Specify the location of a file that contains on… [See Man Page]'
complete -c hfind -s e --description 'Extended mode.'
complete -c hfind -s q --description 'Quick mode.'
complete -c hfind -s V --description 'Display version db_file The location of the hash database file.'

