# hostnamectl
# Autogenerated from man page /usr/share/man/man1/hostnamectl.1.gz
# using Deroffing man parser
complete -c hostnamectl -l no-ask-password --description 'Do not query the user for authentication for pr… [See Man Page]'
complete -c hostnamectl -s P -l privileged --description 'Acquire privileges via PolicyKit before executi… [See Man Page]'
complete -c hostnamectl -l static -l transient -l pretty --description 'If status is used (or no explicit command is gi… [See Man Page]'
complete -c hostnamectl -s H -l host --description 'Execute the operation remotely.'
complete -c hostnamectl -s h -l help --description 'Print a short help text and exit.'
complete -c hostnamectl -l version --description 'Print a short version string and exit.'

