# hspell
# Autogenerated from man page /usr/share/man/man1/hspell.1.gz
# using Deroffing man parser
complete -c hspell -s v --description 'If the  -v option is given,  hspell prints emac… [See Man Page]'
complete -c hspell -o vv --description 'Repetition of the  -v option causes  hspell to … [See Man Page]'
complete -c hspell -s V --description 'With the  -V option,  hspell prints true and hu… [See Man Page]'
complete -c hspell -s c --description 'If the  -c option is given,  hspell will sugges… [See Man Page]'
complete -c hspell -s n --description 'The  -n option will give some longer "notes" ab… [See Man Page]'
complete -c hspell -s l --description 'The  -l (linguistic information) option will ex… [See Man Page]'
complete -c hspell -s s --description 'Normally, the words deemed spelling mistakes ar… [See Man Page]'
complete -c hspell -s a --description 'With the  -a option,  hspell tries to emulate (… [See Man Page]'
complete -c hspell -s i --description 'This option only has any effect when used toget… [See Man Page]'
complete -c hspell -s H --description 'By default, Hspell does not allow the He Ha-sh\'ela prefix.'
complete -c hspell -s D --description 'Load the word lists from the given base pathnam… [See Man Page]'
complete -c hspell -o cn --description 'for maximal correction help from hspell .'
complete -c hspell -s d -s B -s m -s T -s C -s S -s P -s p -s w -s W --description 'These options are passed to hspell by lyx or ot… [See Man Page]'

