# i3-input
# Autogenerated from man page /usr/share/man/man1/i3-input.1.gz
# using Deroffing man parser
complete -c i3-input -s s --description 'Specify the path to the i3 IPC socket (it shoul… [See Man Page]'
complete -c i3-input -s F --description 'Every occurence of "%s" in the <format> string … [See Man Page]'
complete -c i3-input -s l --description 'Set the maximum allowed length of the user inpu… [See Man Page]'
complete -c i3-input -s P --description 'Display the <prompt> string in front of user input text field.'
complete -c i3-input -s f --description 'Use the specified X11 core font (use xfontsel to chose a font).'
complete -c i3-input -s v --description 'Show version and exit.'

