# i3bar
# Autogenerated from man page /usr/share/man/man1/i3bar.1.gz
# using Deroffing man parser
complete -c i3bar -s s -l socket --description 'Overwrites the path to the i3 IPC socket.'
complete -c i3bar -s b -l bar_id --description 'Specifies the bar ID for which to get the confi… [See Man Page]'
complete -c i3bar -s v -l version --description 'Display version number and exit.'
complete -c i3bar -s h -l help --description 'Display a short help-message and exit.'

