# i3lock
# Autogenerated from man page /usr/share/man/man1/i3lock.1.gz
# using Deroffing man parser
complete -c i3lock -s v -l version --description 'Display the version of your  i3lock.'
complete -c i3lock -s n -l nofork --description 'Don\'t fork after starting.'
complete -c i3lock -s b -l beep --description 'Enable beeping.'
complete -c i3lock -s d -l dpms --description 'Enable turning off your screen using DPMS.'
complete -c i3lock -s u -l no-unlock-indicator --description 'Disables the unlock indicator.'
complete -c i3lock -s i -l image --description 'Display the given PNG image instead of a blank screen.'
complete -c i3lock -s c -l color --description 'Turns the screen into the given color instead of white.'
complete -c i3lock -s t -l tiling --description 'If an image is specified (via -i) it will displ… [See Man Page]'
complete -c i3lock -s p -l pointer --description 'If you specify "default", i3lock does not hide … [See Man Page]'

