# icat
# Autogenerated from man page /usr/share/man/man1/icat.1.gz
# using Deroffing man parser
complete -c icat -s f --description 'Specifies the file system type.'
complete -c icat -s h --description 'Skip over holes in sparse files, so that absolu… [See Man Page]'
complete -c icat -s r --description 'Use file recovery techniques if the file is deleted.'
complete -c icat -s s --description 'Include the slack space in the output.'
complete -c icat -s i --description 'Identify the type of image file, such as raw.'
complete -c icat -s o --description 'The sector offset where the file system starts in the image.'
complete -c icat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c icat -s v --description 'Enable verbose mode, output to stderr.'
complete -c icat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

