# iconv
# Autogenerated from man page /usr/share/man/man1/iconv.1p.gz
# using Deroffing man parser
complete -c iconv -s c --description 'Omit any characters that are invalid in the cod… [See Man Page]'
complete -c iconv -s f --description '.'
complete -c iconv -s l --description 'Write all supported fromcode and tocode values … [See Man Page]'
complete -c iconv -s s --description 'Suppress any messages written to standard error… [See Man Page]'
complete -c iconv -s t --description 'Identify the codeset to be used for the output file.'

