# ideviceprovision
# Autogenerated from man page /usr/share/man/man1/ideviceprovision.1.gz
# using Deroffing man parser
complete -c ideviceprovision -s u -l udid --description 'target specific device by its 40-digit device UDID.'
complete -c ideviceprovision -s d -l debug --description 'enable communication debugging.'
complete -c ideviceprovision -s h -l help --description 'prints usage information.'

