# ifind
# Autogenerated from man page /usr/share/man/man1/ifind.1.gz
# using Deroffing man parser
complete -c ifind -s d --description 'Finds the meta data structure that has allocate… [See Man Page]'
complete -c ifind -s n --description 'Finds the meta data structure that is pointed t… [See Man Page]'
complete -c ifind -s p --description 'Finds the unallocated MFT entries in an NTFS im… [See Man Page]'
complete -c ifind -s a --description 'Find all meta-data structures (only works when … [See Man Page]'
complete -c ifind -s f --description 'Specify the file system type.'
complete -c ifind -s l --description 'List the details of each file found with \'-p\', like \'fls -l\'.'
complete -c ifind -s i --description 'Identify the type of image file, such as raw.'
complete -c ifind -s o --description 'The sector offset where the file system starts in the image.'
complete -c ifind -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c ifind -s v --description 'Verbose output to stderr.'
complete -c ifind -s V --description 'Display version.'
complete -c ifind -s z --description 'If \'-p -l\' were given, this will set the timezo… [See Man Page]'

