# ijs-config
# Autogenerated from man page /usr/share/man/man1/ijs-config.1.gz
# using Deroffing man parser
complete -c ijs-config -l help --description 'Show summary of options.'
complete -c ijs-config -l version --description 'Show installed libijs version.'
complete -c ijs-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c ijs-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c ijs-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c ijs-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

