# ils
# Autogenerated from man page /usr/share/man/man1/ils.1.gz
# using Deroffing man parser
complete -c ils -s e --description 'List every inode in the file system.'
complete -c ils -s f --description 'Specifies the file system type.'
complete -c ils -s s --description 'The time skew of the original system in seconds.'
complete -c ils -s m --description 'Display the inode details in the format that th… [See Man Page]'
complete -c ils -s O --description 'List only inodes of removed files that are stil… [See Man Page]'
complete -c ils -s p --description 'Display orphan inodes (unallocated with no file name).'
complete -c ils -s r --description '(default) List only inodes of removed files.'
complete -c ils -s i --description 'Identify the type of image file, such as raw.'
complete -c ils -s o --description 'The sector offset where the file system starts in the image.'
complete -c ils -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c ils -s v --description 'Turn on verbose mode, output to stderr.'
complete -c ils -s V --description 'Display Version.'
complete -c ils -s a --description 'List only allocated inodes: these belong to fil… [See Man Page]'
complete -c ils -s A --description 'List only unallocated inodes: these belong to f… [See Man Page]'
complete -c ils -s l --description 'List only inodes with at least one hard link.'
complete -c ils -s L --description 'List only inodes without any hard links.'
complete -c ils -s z --description 'List only inodes that were likely to have not been used.'
complete -c ils -s Z --description 'List only inodes that were likely to be used.'

