# img_cat
# Autogenerated from man page /usr/share/man/man1/img_cat.1.gz
# using Deroffing man parser
complete -c img_cat -s i --description 'Identify the type of image file, such as raw or aff.'
complete -c img_cat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c img_cat -s s --description 'The sector number to start at.'
complete -c img_cat -s e --description 'The sector number to stop at.'
complete -c img_cat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c img_cat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

