# img_stat
# Autogenerated from man page /usr/share/man/man1/img_stat.1.gz
# using Deroffing man parser
complete -c img_stat -s i --description 'Identify the type of image file, such as raw.'
complete -c img_stat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c img_stat -s t --description 'Print the image type only.'
complete -c img_stat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c img_stat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

