# include_server
# Autogenerated from man page /usr/share/man/man1/include_server.1.gz
# using Deroffing man parser
complete -c include_server -o dPAT -l debug_pattern --description 'Bit vector for turning on warnings and debuggin… [See Man Page]'
complete -c include_server -s e -l email --description 'Send email to \'distcc-pump-errors\' or if define… [See Man Page]'
complete -c include_server -l email_bound --description 'Maximal number of emails to send (in addition t… [See Man Page]'
complete -c include_server -l no-email --description 'Do not send email.  This is the default.'
complete -c include_server -l path_observation_re --description 'Issue warning message whenever a filename is re… [See Man Page]'
complete -c include_server -l pid_file --description 'The pid of the include server is written to file FILEPATH.'
complete -c include_server -s s -l statistics --description 'Print information to stdout about include analysis.'
complete -c include_server -l stat_reset_triggers --description 'Flush stat caches when the timestamp of any fil… [See Man Page]'
complete -c include_server -s t -l time --description 'Print elapsed, user, and system time to stderr.'
complete -c include_server -l unsafe_absolute_includes --description 'Do preprocessing on the compilation server even… [See Man Page]'
complete -c include_server -s v -l verify --description 'Verify that files in CPP closure are contained … [See Man Page]'
complete -c include_server -s w -l write_include_closure --description 'Write a .'
complete -c include_server -s x -l exact_analysis --description 'Use CPP instead, do not omit system headers files.'

