# ip-addrlabel
# Autogenerated from man page /usr/share/man/man8/ip-addrlabel.8.gz
# using Deroffing man parser
complete -c ip-addrlabel -o 'V[ersion]' --description '.'
complete -c ip-addrlabel -o 's[tatistics]' --description '.'
complete -c ip-addrlabel -o 'r[esolve]' --description '.'
complete -c ip-addrlabel -o 'f[amily]' --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-addrlabel -o 'o[neline]' --description 'ip addrlabel  {  add  |  del  }  prefix PREFIX … [See Man Page]'

