# ip-link
# Autogenerated from man page /usr/share/man/man8/ip-link.8.gz
# using Deroffing man parser
complete -c ip-link -o 'V[ersion]' --description '.'
complete -c ip-link -o 's[tatistics]' --description '.'
complete -c ip-link -o 'r[esolve]' --description '.'
complete -c ip-link -o 'f[amily]' --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-link -o 'o[neline]' --description 'ip link add [  link DEVICE  ] [  name  ] NAME.'

