# ip
# Autogenerated from man page /usr/share/man/man8/ip.8.gz
# using Deroffing man parser
complete -c ip -s V -o Version --description 'Print the version of the  ip utility and exit.'
complete -c ip -s b -o batch --description 'Read commands from provided file or standard in… [See Man Page]'
complete -c ip -o force --description 'Don\'t terminate ip on errors in batch mode.'
complete -c ip -s s -o stats -o statistics --description 'Output more information.'
complete -c ip -s l -o loops --description 'Specify maximum number of loops the \'ip addr fl… [See Man Page]'
complete -c ip -s f -o family --description 'Specifies the protocol family to use.'
complete -c ip -s 4 --description 'shortcut for  "-family inet" .'
complete -c ip -s 6 --description 'shortcut for  "-family inet6" .'
complete -c ip -s B --description 'shortcut for  "-family bridge" .'
complete -c ip -s D --description 'shortcut for  "-family decnet" .'
complete -c ip -s I --description 'shortcut for  "-family ipx" .'
complete -c ip -s 0 --description 'shortcut for  "-family link" .'
complete -c ip -s o -o oneline --description 'output each record on a single line, replacing … [See Man Page]'
complete -c ip -o 'V[ersion]' --description '.'
complete -c ip -o 's[tatistics]' --description '.'
complete -c ip -o 'r[esolve]' --description '.'
complete -c ip -o 'f[amily]' --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip -o 'o[neline]' --description 'OPTIONS.'
complete -c ip -s r -o resolve --description 'use the system\'s name resolver to print DNS nam… [See Man Page]'

