# ipcmk
# Autogenerated from man page /usr/share/man/man1/ipcmk.1.gz
# using Deroffing man parser
complete -c ipcmk -s M -l shmem --description 'Shared memory segment of size bytes.'
complete -c ipcmk -s S -l semaphore --description 'Semaphore array with number of elements.'
complete -c ipcmk -s Q -l queue --description 'Message queue.  ADDITIONAL OPTIONS.'
complete -c ipcmk -s p -l mode --description 'Access permissions for the resource.   Default is 0644.'
complete -c ipcmk -s h -l help --description 'Display help text and exit.'
complete -c ipcmk -s V -l version --description 'Display version information and exit.'

