# iptables-xml
# Autogenerated from man page /usr/share/man/man1/iptables-xml.1.gz
# using Deroffing man parser
complete -c iptables-xml -s c -l combine --description 'combine consecutive rules with the same matches… [See Man Page]'
complete -c iptables-xml -s v -l verbose --description 'Output xml comments containing the iptables lin… [See Man Page]'

