# ircat
# Autogenerated from man page /usr/share/man/man1/ircat.1.gz
# using Deroffing man parser
complete -c ircat -s h -l help --description 'display usage summary.'
complete -c ircat -s v -l version --description 'display version.'
complete -c ircat -s c -l config --description 'set config file EXAMPLES If .'

