# irexec
# Autogenerated from man page /usr/share/man/man1/irexec.1.gz
# using Deroffing man parser
complete -c irexec -s h -l help --description 'display usage summary.'
complete -c irexec -s v -l version --description 'display version.'
complete -c irexec -s d -l daemon --description 'run in background.'
complete -c irexec -s n -l name --description 'use this program name OPTIONS If you add the --… [See Man Page]'

