# irpty
# Autogenerated from man page /usr/share/man/man1/irpty.1.gz
# using Deroffing man parser
complete -c irpty -s h -l help --description 'display usage summary.'
complete -c irpty -s V -l version --description 'display version.'
complete -c irpty -s e -l no-echo --description 'disable echo.'
complete -c irpty -s i -l ignore-eof --description 'ignore EOF.'
complete -c irpty -s n -l non-interactive --description 'force non-interactive mode.'
complete -c irpty -s v -l verbose --description 'verbose mode SEE ALSO The documentation for lir… [See Man Page]'

