# irrecord
# Autogenerated from man page /usr/share/man/man1/irrecord.1.gz
# using Deroffing man parser
complete -c irrecord -s h -l help --description 'display this message.'
complete -c irrecord -s v -l version --description 'display version.'
complete -c irrecord -s a -l analyse --description 'analyse raw_codes config files.'
complete -c irrecord -s f -l force --description 'force raw mode.'
complete -c irrecord -s n -l disable-namespace --description 'disables namespace checks.'
complete -c irrecord -s l -l list-namespace --description 'list valid button names.'
complete -c irrecord -s H -l driver --description 'use given driver.'
complete -c irrecord -s d -l device --description 'read from given device SEE ALSO The documentati… [See Man Page]'

