# irsend
# Autogenerated from man page /usr/share/man/man1/irsend.1.gz
# using Deroffing man parser
complete -c irsend -s h -l help --description 'display usage summary.'
complete -c irsend -s v -l version --description 'display version.'
complete -c irsend -s d -l device --description 'use given lircd socket [/var/run/lirc/lircd].'
complete -c irsend -s a -l address --description 'connect to lircd at this address.'
complete -c irsend -s '#' -l count --description 'send command n times EXAMPLES irsend LIST Denon… [See Man Page]'

