# irw
# Autogenerated from man page /usr/share/man/man1/irw.1.gz
# using Deroffing man parser
complete -c irw -s h -l help --description 'display usage summary.'
complete -c irw -s v -l version --description 'display version SEE ALSO The documentation for … [See Man Page]'

