# irxevent
# Autogenerated from man page /usr/share/man/man1/irxevent.1.gz
# using Deroffing man parser
complete -c irxevent -s d -l daemon --description 'fork and run in background.'
complete -c irxevent -s h -l help --description 'display usage summary.'
complete -c irxevent -s V -l version --description 'display version FILES Irxevent works with the s… [See Man Page]'

