# iso-info
# Autogenerated from man page /usr/share/man/man1/iso-info.1.gz
# using Deroffing man parser
complete -c iso-info -s d -l debug --description 'Set debugging to LEVEL.'
complete -c iso-info -s i -l 'input[' --description 'Filename to read ISO-9960 image from.'
complete -c iso-info -s f --description 'Generate output similar to \'find .  -print\'.'
complete -c iso-info -s l -l iso9660 --description 'output similar to \'ls -lR\' for an ISO 9660 fs.'
complete -c iso-info -s U -l udf --description 'output similar to \'ls -lR\' for a UDF fs.'
complete -c iso-info -l no-header --description 'Don\'t display header and copyright (for regression.'
complete -c iso-info -l no-joliet --description 'Don\'t use Joliet-extension information.'
complete -c iso-info -l no-rock-ridge --description 'Don\'t use Rock-Ridge-extension information.'
complete -c iso-info -l no-xa --description 'Don\'t use XA-extension information.'
complete -c iso-info -s r -l show-rock-ridge --description 'A maximum of UINT files will be considered.'
complete -c iso-info -s q -l quiet --description 'Don\'t produce warning output.'
complete -c iso-info -s V -l version --description 'display version and copyright information and exit .'
complete -c iso-info -s '?' -l help --description 'Show this help message.'
complete -c iso-info -l usage --description 'Display brief usage message AUTHOR Rocky Bernstein <rocky@gnu.'

