# iso-read
# Autogenerated from man page /usr/share/man/man1/iso-read.1.gz
# using Deroffing man parser
complete -c iso-read -s d -l debug --description 'Set debugging to LEVEL.'
complete -c iso-read -s i -l image --description 'Read from ISO-9660 image.  This option is mandatory.'
complete -c iso-read -s e -l extract --description 'Extract FILE from ISO-9660 image.  This option is mandatory.'
complete -c iso-read -s k -l ignore --description 'Ignore read error(s), i. e.  keep going.'
complete -c iso-read -l no-header --description 'Don\'t display header and copyright (for regression testing).'
complete -c iso-read -s o -l output-file --description 'Output file.  This option is mandatory.'
complete -c iso-read -s U -l udf --description 'Contents are in UDF format.'
complete -c iso-read -s V -l version --description 'display version and copyright information and exit .'
complete -c iso-read -s '?' -l help --description 'Show this help message.'
complete -c iso-read -l usage --description 'Display brief usage message AUTHOR Rocky Bernstein <rocky@gnu.'

