# isql
# Autogenerated from man page /usr/share/man/man1/isql.1.gz
# using Deroffing man parser
complete -c isql -s b --description 'Run isql in non-interactive batch mode.'
complete -c isql -o dDELIMITER --description 'Delimits columns with delimiter.'
complete -c isql -o xHEX --description 'Delimits columns with HEX, which is a hexadecim… [See Man Page]'
complete -c isql -s w --description 'Format the result as HTML table.'
complete -c isql -s c --description 'Output the names of the columns on the first row.'
complete -c isql -o mNUM --description 'Limit the column display width to NUM characters.'
complete -c isql -o lLOCALE --description 'Sets locale to LOCALE.'
complete -c isql -s q --description 'Wrap the character fields in double quotes.'
complete -c isql -s 3 --description 'Use the ODBC 3 calls.'
complete -c isql -s n --description 'Use the newline processing.'
complete -c isql -s e --description 'Use the SQLExecDirect instead of Prepare.'
complete -c isql -s k --description 'Use SQLDriverConnect.'
complete -c isql -s v --description 'Turn on the verbose mode, where the errors are fully described.'
complete -c isql -s d -s x --description '.'
complete -c isql -l version --description 'Prints the program version and exits.'

