# istat
# Autogenerated from man page /usr/share/man/man1/istat.1.gz
# using Deroffing man parser
complete -c istat -s B --description 'Display the addresses of num disk units.'
complete -c istat -s f --description 'Specify the file system type.'
complete -c istat -s s --description 'The time skew of the original system in seconds.'
complete -c istat -s i --description 'Identify the type of image file, such as raw.'
complete -c istat -s o --description 'The sector offset where the file system starts in the image.'
complete -c istat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c istat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c istat -s V --description 'Display version.'
complete -c istat -s z --description 'An ASCII string of the original system\'s time zone.'

