# ivstools
# Autogenerated from man page /usr/share/man/man1/ivstools.1.gz
# using Deroffing man parser
complete -c ivstools -l convert --description 'ivstools.'
complete -c ivstools -l merge --description 'AUTHOR This manual page was written by Adam Cec… [See Man Page]'

