# j2k_dump
# Autogenerated from man page /usr/share/man/man1/j2k_dump.1.gz
# using Deroffing man parser
complete -c j2k_dump -s i --description '(jpeg2000 input file name).'
complete -c j2k_dump -o ImgDir --description '(directory containing jpeg2000 input files) AUT… [See Man Page]'

