# jcat
# Autogenerated from man page /usr/share/man/man1/jcat.1.gz
# using Deroffing man parser
complete -c jcat -s f --description 'Specify the file system type.'
complete -c jcat -s i --description 'Identify the type of image file, such as raw.'
complete -c jcat -s o --description 'The sector offset where the file system starts in the image.'
complete -c jcat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c jcat -s V --description 'Display version.'
complete -c jcat -s v --description 'verbose output image [images] The disk or parti… [See Man Page]'

