# jfs_logdump
# Autogenerated from man page /usr/share/man/man8/jfs_logdump.8.gz
# using Deroffing man parser
complete -c jfs_logdump -s a --description 'Dump the entire contents of the journal log ins… [See Man Page]'
complete -c jfs_logdump -s v --description 'option on the JFS device.'

