# jfs_fscklog
# Autogenerated from man page /usr/share/man/man8/jfs_fscklog.8.gz
# using Deroffing man parser
complete -c jfs_fscklog -s d --description 'Format and display a previously extracted JFS fsck service log.'
complete -c jfs_fscklog -s e --description 'Extract the JFS fsck service log from  device a… [See Man Page]'
complete -c jfs_fscklog -s f --description 'Specify the file name, overriding the default file name.'
complete -c jfs_fscklog -s p --description 'Extract the prior log (as opposed to the most recent log).'
complete -c jfs_fscklog -s V --description 'Print version information and exit (regardless … [See Man Page]'
complete -c jfs_fscklog -s v --description 'option on the JFS device.'

