# jfs_fsck
# Autogenerated from man page /usr/share/man/man8/jfs_fsck.8.gz
# using Deroffing man parser
complete -c jfs_fsck -s a --description 'Autocheck mode - Replay the transaction log.'
complete -c jfs_fsck -s b --description '\\" *currently unused* Perform Bad Block List ut… [See Man Page]'
complete -c jfs_fsck -s c --description '\\" After a replay of the transaction log comple… [See Man Page]'
complete -c jfs_fsck -s f --description 'Replay the transaction log and force checking e… [See Man Page]'
complete -c jfs_fsck -s j --description 'Specify the journal device.'
complete -c jfs_fsck -s n --description 'Open the file system read only.'
complete -c jfs_fsck -l omit_journal_replay --description 'Omit the replay of the transaction log.'
complete -c jfs_fsck -s p --description 'Automatically repair ("preen") the file system.'
complete -c jfs_fsck -l replay_journal_only --description 'Only replay the transaction log.'
complete -c jfs_fsck -s v --description 'Verbose messaging - print details and debug sta… [See Man Page]'
complete -c jfs_fsck -o 'p.' --description '.'
complete -c jfs_fsck -o 'a.' --description '.'
complete -c jfs_fsck -s V --description 'Print version information and exit (regardless … [See Man Page]'

