# jfs_mkfs
# Autogenerated from man page /usr/share/man/man8/jfs_mkfs.8.gz
# using Deroffing man parser
complete -c jfs_mkfs -s b --description '/"Set the block size for a new JFS partition . /". RS . /" .'
complete -c jfs_mkfs -s c --description 'Check the device for bad blocks before building… [See Man Page]'
complete -c jfs_mkfs -s f --description '/"Force - do not ask for confirmation before cr… [See Man Page]'
complete -c jfs_mkfs -s j --description 'Create the external JFS journal on  journal_dev… [See Man Page]'
complete -c jfs_mkfs -s J --description 'Create the JFS journal on its own device or att… [See Man Page]'
complete -c jfs_mkfs -s L --description 'Set the volume label for the newly formatted device.'
complete -c jfs_mkfs -s O --description 'Provide case-insensitive support for compatibility with OS/2.'
complete -c jfs_mkfs -s q --description 'Quiet execution - do not ask for confirmation b… [See Man Page]'
complete -c jfs_mkfs -s s --description 'Set the log size (in megabytes) of the inline log.'
complete -c jfs_mkfs -s l --description '.'
complete -c jfs_mkfs -s U --description 'options of jfs_tune (8). ).'
complete -c jfs_mkfs -s V --description 'Print version information and exit (regardless … [See Man Page]'

