# jobs
# Autogenerated from man page /usr/share/man/man1/jobs.1p.gz
# using Deroffing man parser
complete -c jobs -s l --description '(The letter ell.'
complete -c jobs -s p --description 'Display only the process IDs for the process gr… [See Man Page]'
complete -c jobs -s n --description 'option was included to ``Display the status of … [See Man Page]'

