# join
# Autogenerated from man page /usr/share/man/man1/join.1p.gz
# using Deroffing man parser
complete -c join -s b --description 'on the fields on which they shall be joined, by… [See Man Page]'
complete -c join -o j1 --description '.'
complete -c join -o j2 --description 'options, and a form of the.'

