# jpwl_j2k_to_image
# Autogenerated from man page /usr/share/man/man1/jpwl_j2k_to_image.1.gz
# using Deroffing man parser
complete -c jpwl_j2k_to_image -s i --description '(jpeg2000 input file name).'
complete -c jpwl_j2k_to_image -s l --description 'n is the maximum number of quality layers to decode.'
complete -c jpwl_j2k_to_image -s o --description '(output file name with extension).'
complete -c jpwl_j2k_to_image -s r --description '(n is the highest resolution level to be discarded.'
complete -c jpwl_j2k_to_image -s x --description '(use name as index file and fill it).'
complete -c jpwl_j2k_to_image -o ImgDir --description '(directory containing input files).'
complete -c jpwl_j2k_to_image -o OutFor --description '(extension for output files).'
complete -c jpwl_j2k_to_image -o DUSE_JPWL --description '.'
complete -c jpwl_j2k_to_image -s W --description '.'

