# kadmind
# Autogenerated from man page /usr/share/man/man8/kadmind.8.gz
# using Deroffing man parser
complete -c kadmind -s r --description 'specifies the realm that kadmind will serve; if… [See Man Page]'
complete -c kadmind -s m --description 'causes the master database password to be fetch… [See Man Page]'
complete -c kadmind -o nofork --description 'causes the server to remain in the foreground a… [See Man Page]'
complete -c kadmind -o port --description 'specifies the port on which the administration … [See Man Page]'
complete -c kadmind -s P --description 'specifies the file to which the PID of kadmind … [See Man Page]'
complete -c kadmind -s p --description 'specifies the path to the kdb5_util command to … [See Man Page]'
complete -c kadmind -s K --description 'specifies the path to the kprop command to use … [See Man Page]'
complete -c kadmind -s F --description 'specifies the file path to be used for dumping … [See Man Page]'
complete -c kadmind -s x --description 'specifies database-specific arguments.'

