# katalyzer
# Autogenerated from man page /usr/share/man/man1/katalyzer.1.gz
# using Deroffing man parser
complete -c katalyzer -s h --description 'Show command line help.'
complete -c katalyzer -s V --description 'Show version information.'
complete -c katalyzer -s l --description 'Select the types of information to log, from the list below.'
complete -c katalyzer -o 'l!' --description 'Shorthand to select all information to log.  EXAMPLES.'

