# kateenc
# Autogenerated from man page /usr/share/man/man1/kateenc.1.gz
# using Deroffing man parser
complete -c kateenc -s h --description 'Show command line help.'
complete -c kateenc -s V --description 'Show version information.'
complete -c kateenc -s M --description 'Allow simple HTML-like markup in SRT files.'
complete -c kateenc -s o --description 'Write the output Kate stream to the given file … [See Man Page]'
complete -c kateenc -s l --description 'Sets the language for the stream (default is th… [See Man Page]'
complete -c kateenc -s c --description 'Sets the category for the stream (default is th… [See Man Page]'
complete -c kateenc -s s --description 'Sets the serial number for the output Kate stre… [See Man Page]'
complete -c kateenc -s C --description 'Adds a comment to encode into the output Kate stream.'
complete -c kateenc -s t --description 'Specifies the type of the input (srt, lrc, kate).'
complete -c kateenc -s R --description 'Use repeat packets, with the given threshold (in seconds).'
complete -c kateenc -s K --description 'Use keepalive packets, with the given threshold (in seconds).'

