# kdb5_ldap_util
# Autogenerated from man page /usr/share/man/man8/kdb5_ldap_util.8.gz
# using Deroffing man parser
complete -c kdb5_ldap_util -s D --description 'Specifies the Distinguished Name (DN) of the us… [See Man Page]'
complete -c kdb5_ldap_util -s w --description 'Specifies the password of user_dn.'
complete -c kdb5_ldap_util -s H --description 'Specifies the URI of the LDAP server.'
complete -c kdb5_ldap_util -o subtrees --description 'Specifies the list of subtrees containing the p… [See Man Page]'
complete -c kdb5_ldap_util -o sscope --description 'Specifies the scope for searching the principal… [See Man Page]'
complete -c kdb5_ldap_util -o containerref --description 'Specifies the DN of the container object in whi… [See Man Page]'
complete -c kdb5_ldap_util -s k --description 'Specifies the key type of the master key in the database.'
complete -c kdb5_ldap_util -o kv --description 'Specifies the version number of the master key … [See Man Page]'
complete -c kdb5_ldap_util -s m --description 'Specifies that the master database password sho… [See Man Page]'
complete -c kdb5_ldap_util -s P --description 'Specifies the master database password.'
complete -c kdb5_ldap_util -s r --description 'Specifies the Kerberos realm of the database.'
complete -c kdb5_ldap_util -o sf --description 'Specifies the stash file of the master database password.'
complete -c kdb5_ldap_util -s s --description 'Specifies that the stash file is to be created.'
complete -c kdb5_ldap_util -o maxtktlife --description '(getdate string) Specifies maximum ticket life … [See Man Page]'
complete -c kdb5_ldap_util -o maxrenewlife --description '(getdate string) Specifies maximum renewable li… [See Man Page]'
complete -c kdb5_ldap_util -s f --description 'If specified, will not prompt the user for confirmation.'
complete -c kdb5_ldap_util -o force --description 'Forces the deletion of the policy object.'

