# kdestroy
# Autogenerated from man page /usr/share/man/man1/kdestroy.1.gz
# using Deroffing man parser
complete -c kdestroy -s A --description 'Destroys all caches in the collection, if a cac… [See Man Page]'
complete -c kdestroy -s q --description 'Run quietly.'
complete -c kdestroy -s c --description 'Use cache_name as the credentials (ticket) cach… [See Man Page]'

