# keepassc
# Autogenerated from man page /usr/share/man/man1/keepassc.1.gz
# using Deroffing man parser
complete -c keepassc -s h -l help --description 'show this help message and exit.'
complete -c keepassc -l asroot --description 'parse option to execute keepassc as root user.'
complete -c keepassc -s d -l database --description 'Path to database file.'
complete -c keepassc -s k -l keyfile --description 'Path to keyfile.'
complete -c keepassc -s c -l curses --description 'Use curses interface while using a remote connection.'
complete -c keepassc -o as -l address_server --description 'Server address (not required if using agent).'
complete -c keepassc -o ps -l port_server --description 'Server port (not required if using agent).'
complete -c keepassc -o pa -l port_agent --description 'Agent port.'
complete -c keepassc -s a -l agent --description 'Use agent for remote connection.'
complete -c keepassc -o dc -l direct_conn --description 'Connect directly to server.'
complete -c keepassc -s s -l ssl --description 'Use SSL/TLS.'
complete -c keepassc -s e -l entry --description 'Print entry with parsed title You will see a pa… [See Man Page]'
complete -c keepassc -s l -l log_level --description 'Set logging level for network use.'

