# keepassc-server
# Autogenerated from man page /usr/share/man/man1/keepassc-server.1.gz
# using Deroffing man parser
complete -c keepassc-server -s h -l help --description 'show the help message and exit.'
complete -c keepassc-server -l asroot --description 'Execute server as root user.'
complete -c keepassc-server -s d -l database --description 'Path to database file.'
complete -c keepassc-server -s k -l keyfile --description 'Path to keyfile.'
complete -c keepassc-server -s a -l address --description 'Address for the server.'
complete -c keepassc-server -s p -l port --description 'Port for the server.'
complete -c keepassc-server -o ps -l port_tls --description 'Port for server\'s TLS-port if -S is used.'
complete -c keepassc-server -s l -l log_level --description 'Set logging level.'
complete -c keepassc-server -s s -l ssl --description 'Use SSL/TLS additionaly.'
complete -c keepassc-server -s S --description 'COMMANDS The server is implemented as a daemon.'
complete -c keepassc-server -l ssl_req --description 'Use SSL/TLS only.'

