# kill
# Autogenerated from man page /usr/share/man/man1/kill.1p.gz
# using Deroffing man parser
complete -c kill -o signal_name --description '.'
complete -c kill -o signal_number --description '.'

