# klist
# Autogenerated from man page /usr/share/man/man1/klist.1.gz
# using Deroffing man parser
complete -c klist -s e --description 'Displays the encryption types of the session ke… [See Man Page]'
complete -c klist -s l --description 'If a cache collection is available, displays a … [See Man Page]'
complete -c klist -s A --description 'If a cache collection is available, displays th… [See Man Page]'
complete -c klist -s c --description 'List tickets held in a credentials cache.'
complete -c klist -s f --description 'Shows the flags present in the credentials, usi… [See Man Page]'
complete -c klist -s s --description 'Causes klist to run silently (produce no output).'
complete -c klist -s a --description 'Display list of addresses in credentials.'
complete -c klist -s n --description 'Show numeric addresses instead of reverse-resolving addresses.'
complete -c klist -s C --description 'List configuration data that has been stored in… [See Man Page]'
complete -c klist -s k --description 'List keys held in a keytab file.'
complete -c klist -s i --description 'In combination with -k, defaults to using the d… [See Man Page]'
complete -c klist -s t --description 'Display the time entry timestamps for each keyt… [See Man Page]'
complete -c klist -s K --description 'Display the value of the encryption key in each… [See Man Page]'
complete -c klist -s V --description 'Display the Kerberos version number and exit.'

