# kpropd
# Autogenerated from man page /usr/share/man/man8/kpropd.8.gz
# using Deroffing man parser
complete -c kpropd -s r --description 'Specifies the realm of the master server.'
complete -c kpropd -s f --description 'Specifies the filename where the dumped princip… [See Man Page]'
complete -c kpropd -s p --description 'Allows the user to specify the pathname to the … [See Man Page]'
complete -c kpropd -s d --description 'Turn on debug mode.'
complete -c kpropd -s P --description 'Allow for an alternate port number for kpropd to listen on.'
complete -c kpropd -s a --description 'Allows the user to specify the path to the kpropd.'

