# kprop
# Autogenerated from man page /usr/share/man/man8/kprop.8.gz
# using Deroffing man parser
complete -c kprop -s r --description 'Specifies the realm of the master server.'
complete -c kprop -s f --description 'Specifies the filename where the dumped princip… [See Man Page]'
complete -c kprop -s P --description 'Specifies the port to use to contact the kpropd… [See Man Page]'
complete -c kprop -s d --description 'Prints debugging information.'
complete -c kprop -s s --description 'Specifies the location of the keytab file.'

