# krb5kdc
# Autogenerated from man page /usr/share/man/man8/krb5kdc.8.gz
# using Deroffing man parser
complete -c krb5kdc -s x --description 'Specifies the number of connections to be maint… [See Man Page]'

