# ksu
# Autogenerated from man page /usr/share/man/man1/ksu.1.gz
# using Deroffing man parser
complete -c ksu -s n --description 'Specify a Kerberos target principal name.'
complete -c ksu -s k --description 'Do not delete the target cache upon termination… [See Man Page]'
complete -c ksu -s D --description 'Turn on debug mode.'
complete -c ksu -s z --description 'Restrict the copy of tickets from the source ca… [See Man Page]'
complete -c ksu -s Z --description 'Don\\(aqt copy any tickets from the source cache… [See Man Page]'
complete -c ksu -s q --description 'Suppress the printing of status messages. UNINDENT .'
complete -c ksu -s l -s r -o pf --description 'The ticket granting ticket options only apply t… [See Man Page]'
complete -c ksu -s p --description 'specifies that the proxiable option should be r… [See Man Page]'
complete -c ksu -s f --description 'option specifies that the forwardable option sh… [See Man Page]'
complete -c ksu -s e --description 'ksu proceeds exactly the same as if it was invo… [See Man Page]'
complete -c ksu -s c --description 'Specify source cache name (e. g. , -c FILE:/tmp/my_cache).'
complete -c ksu -s a --description 'Specify arguments to be passed to the target shell.'

