# kswitch
# Autogenerated from man page /usr/share/man/man1/kswitch.1.gz
# using Deroffing man parser
complete -c kswitch -s c --description 'Directly specifies the credential cache to be made primary.'
complete -c kswitch -s p --description 'Causes the cache collection to be searched for … [See Man Page]'

