# kvno
# Autogenerated from man page /usr/share/man/man1/kvno.1.gz
# using Deroffing man parser
complete -c kvno -s c --description 'Specifies the name of a credentials cache to us… [See Man Page]'
complete -c kvno -s e --description 'Specifies the enctype which will be requested f… [See Man Page]'
complete -c kvno -s q --description 'Suppress printing output when successful.'
complete -c kvno -s h --description 'Prints a usage statement and exits.'
complete -c kvno -s P --description 'Specifies that the service1 service2 .'
complete -c kvno -s S --description 'Specifies that the service1 service2 .'
complete -c kvno -s U --description 'Specifies that protocol transition (S4U2Self) i… [See Man Page]'

