# lchsh
# Autogenerated from man page /usr/share/man/man1/lchsh.1.gz
# using Deroffing man parser
complete -c lchsh -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'

