# ldbdel
# Autogenerated from man page /usr/share/man/man1/ldbdel.1.gz
# using Deroffing man parser
complete -c ldbdel -s h --description 'Show list of available options.'
complete -c ldbdel -s H --description 'LDB URL to connect to.  See ldb(3) for details.'

