# ldbrename
# Autogenerated from man page /usr/share/man/man1/ldbrename.1.gz
# using Deroffing man parser
complete -c ldbrename -s h --description 'Show list of available options.'
complete -c ldbrename -s H --description 'LDB URL to connect to.  See ldb(3) for details.'
complete -c ldbrename -s o --description 'Extra ldb options, such as modules.'

