# ldbsearch
# Autogenerated from man page /usr/share/man/man1/ldbsearch.1.gz
# using Deroffing man parser
complete -c ldbsearch -s h --description 'Show list of available options.'
complete -c ldbsearch -s H --description 'LDB URL to connect to.  See ldb(3) for details.'
complete -c ldbsearch -s s --description 'Search scope to use.  One-level, subtree or base.'
complete -c ldbsearch -s i --description 'Read search expressions from stdin.'
complete -c ldbsearch -s b --description 'Specify Base DN to use.'

