# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
# using Deroffing man parser
complete -c ldconfig -s v --description 'Verbose mode.'
complete -c ldconfig -s n --description 'Only process directories specified on the command line.'
complete -c ldconfig -s N --description 'Don\'t rebuild the cache.'
complete -c ldconfig -s X --description 'Don\'t update links.'
complete -c ldconfig -s f --description 'Use  conf instead of R /etc/ld. so. conf .'
complete -c ldconfig -s C --description 'Use  cache instead of R /etc/ld. so. cache .'
complete -c ldconfig -s r --description 'Change to and use  root as the root directory.'
complete -c ldconfig -s l --description 'Library mode.  Manually link individual libraries.'
complete -c ldconfig -s p --description 'option.'

