# ldns-zcat
# Autogenerated from man page /usr/share/man/man1/ldns-zcat.1.gz
# using Deroffing man parser
complete -c ldns-zcat -s o --description 'use ORIGIN when reading in the zone.'
complete -c ldns-zcat -s v --description 'show the version number and exit.'

