# ldns-nsec3-hash
# Autogenerated from man page /usr/share/man/man1/ldns-nsec3-hash.1.gz
# using Deroffing man parser
complete -c ldns-nsec3-hash -s a --description 'Use the given algorithm number for the hash calculation.'
complete -c ldns-nsec3-hash -s s --description 'Use the given salt for the hash calculation.'
complete -c ldns-nsec3-hash -s t --description 'Use count iterations for the hash calculation.'

