# ldns-verify-zone
# Autogenerated from man page /usr/share/man/man1/ldns-verify-zone.1.gz
# using Deroffing man parser
complete -c ldns-verify-zone -s h --description 'Show usage and exit.'
complete -c ldns-verify-zone -s a --description 'Apex only, check only the zone apex.'
complete -c ldns-verify-zone -s e --description 'Signatures may not expire within this period.'
complete -c ldns-verify-zone -s i --description 'Signatures must have been valid at least this long.'
complete -c ldns-verify-zone -s k --description 'A file that contains a trusted DNSKEY or DS rr.'
complete -c ldns-verify-zone -s p --description 'Only check this percentage of the zone.'
complete -c ldns-verify-zone -s S --description 'Chase signature(s) to a known key.'
complete -c ldns-verify-zone -s t -o ']offset' --description 'Set the validation time either by an absolute t… [See Man Page]'
complete -c ldns-verify-zone -s v --description 'Show the version and exit.'
complete -c ldns-verify-zone -s V --description 'Set the verbosity level (default 3):.'

