# ldns-testns
# Autogenerated from man page /usr/share/man/man1/ldns-testns.1.gz
# using Deroffing man parser
complete -c ldns-testns -s r --description 'Listens to a random port.'
complete -c ldns-testns -s p --description 'Listens to the specified port.'
complete -c ldns-testns -s f --description 'Forks this number of additional instances that … [See Man Page]'
complete -c ldns-testns -s v --description 'Outputs more debug information.'
complete -c ldns-testns -s 6 --description 'Bind to IP6 address instead of IP4.  Use together with -p.'

