# ldns-keyfetcher
# Autogenerated from man page /usr/share/man/man1/ldns-keyfetcher.1.gz
# using Deroffing man parser
complete -c ldns-keyfetcher -s 4 --description 'Only use IPv4.'
complete -c ldns-keyfetcher -s 6 --description 'Only use IPv6.'
complete -c ldns-keyfetcher -s h --description 'Show a help text and exit.'
complete -c ldns-keyfetcher -s i --description 'Insecurer mode; there will only be one query for the DNSKEYS.'
complete -c ldns-keyfetcher -s v --description '.'
complete -c ldns-keyfetcher -s r --description '.'
complete -c ldns-keyfetcher -s s --description 'Don\'t print the keys to stdout, but store them in files.'

