# ldns-compare-zones
# Autogenerated from man page /usr/share/man/man1/ldns-compare-zones.1.gz
# using Deroffing man parser
complete -c ldns-compare-zones -s c --description 'Print resource records whose owner names are in… [See Man Page]'
complete -c ldns-compare-zones -s i --description 'Print resource records whose owner names are pr… [See Man Page]'
complete -c ldns-compare-zones -s d --description 'Print resource records whose owner names are pr… [See Man Page]'
complete -c ldns-compare-zones -s a --description 'Print all changes.'
complete -c ldns-compare-zones -s z --description 'Suppress zone sorting; this option is not recom… [See Man Page]'
complete -c ldns-compare-zones -s s --description 'Do not exclude the SOA record from the comparison.'
complete -c ldns-compare-zones -s h --description 'Show usage and exit.'
complete -c ldns-compare-zones -s v --description 'Show the version and exit AUTHOR Written by Ond… [See Man Page]'

