# ldns-test-edns
# Autogenerated from man page /usr/share/man/man1/ldns-test-edns.1.gz
# using Deroffing man parser
complete -c ldns-test-edns -s i --description 'after another, with no other explanations, and … [See Man Page]'

