# ldns-signzone
# Autogenerated from man page /usr/share/man/man1/ldns-signzone.1.gz
# using Deroffing man parser
complete -c ldns-signzone -s b --description 'Augments the zone and the RR\'s with extra comme… [See Man Page]'
complete -c ldns-signzone -s d --description 'Normally, if the DNSKEY RR for a key that is us… [See Man Page]'
complete -c ldns-signzone -s e --description 'Set expiration date of the signatures to this d… [See Man Page]'
complete -c ldns-signzone -s f --description 'Use this file to store the signed zone in (defa… [See Man Page]'
complete -c ldns-signzone -s i --description 'Set inception date of the signatures to this da… [See Man Page]'
complete -c ldns-signzone -s o --description 'Use this as the origin of the zone.'
complete -c ldns-signzone -s v --description 'Print the version and exit.'
complete -c ldns-signzone -s A --description 'Sign the DNSKEY record with all keys.'
complete -c ldns-signzone -s E --description 'Use the EVP cryptographic engine with the given… [See Man Page]'
complete -c ldns-signzone -s k --description 'Use the key with the given id as the signing ke… [See Man Page]'
complete -c ldns-signzone -s K --description 'Use the key with the given id as the signing ke… [See Man Page]'
complete -c ldns-signzone -s n --description 'Use NSEC3 instead of NSEC.'
complete -c ldns-signzone -s a --description 'Algorithm used to create the hashed NSEC3 owner names.'
complete -c ldns-signzone -s p --description 'Opt-out.'
complete -c ldns-signzone -s s --description 'Salt.'
complete -c ldns-signzone -s t --description 'Number of hash iterations.'

