# ldns-dpa
# Autogenerated from man page /usr/share/man/man1/ldns-dpa.1.gz
# using Deroffing man parser
complete -c ldns-dpa -s c --description 'Count occurrences of matching expressions.'
complete -c ldns-dpa -s f --description 'Filter: only process packets that match the expression.'
complete -c ldns-dpa -s h --description 'Show usage.'
complete -c ldns-dpa -s p --description 'Show the total number of correct DNS packets, a… [See Man Page]'
complete -c ldns-dpa -o of --description 'Write all packets that match the -f flag to file, as pcap data.'
complete -c ldns-dpa -o ofh --description 'Write all packets that match the -f flag to fil… [See Man Page]'
complete -c ldns-dpa -s s --description 'Show possible match names.'
complete -c ldns-dpa -o sf --description 'Only evaluate packets (in representation format… [See Man Page]'
complete -c ldns-dpa -s u --description 'Count every occurence of every value of the mat… [See Man Page]'
complete -c ldns-dpa -o ua --description 'For every matchname in -u, show the average val… [See Man Page]'
complete -c ldns-dpa -o uac --description 'For every matchname in -u, show the average num… [See Man Page]'
complete -c ldns-dpa -o um --description 'Only show the results from -u for values that o… [See Man Page]'
complete -c ldns-dpa -s v --description 'Set verbosity to level (1-5, 5 being the highest).'
complete -c ldns-dpa -o notip --description 'Write packets that were not recognized as IP pa… [See Man Page]'
complete -c ldns-dpa -o baddns --description 'Write dns packets that were too mangled to pars… [See Man Page]'
complete -c ldns-dpa -o version --description 'Show version and exit.'

