# ldns-config
# Autogenerated from man page /usr/share/man/man1/ldns-config.1.gz
# using Deroffing man parser
complete -c ldns-config -l cflags --description 'Show the C compiler flags needed to compile with ldns.'
complete -c ldns-config -l libs --description 'Show the flags to be used to link with ldns.'
complete -c ldns-config -l version --description 'Shows the ldns version of the installed ldns library.'
complete -c ldns-config -l libversion --description 'Shows version of the binary api of the installed ldns library.'
complete -c ldns-config -l help --description 'Show ldns-config usage description.'

