# ldns-notify
# Autogenerated from man page /usr/share/man/man1/ldns-notify.1.gz
# using Deroffing man parser
complete -c ldns-notify -s z --description 'The zone that is updated.'
complete -c ldns-notify -s h --description 'Show usage and exit.'
complete -c ldns-notify -s v --description 'Show the version and exit.'
complete -c ldns-notify -s s --description 'Append a SOA record indicating the serial numbe… [See Man Page]'
complete -c ldns-notify -s p --description 'Use port as destination port (default the DNS p… [See Man Page]'
complete -c ldns-notify -s y --description 'Use the given TSIG key and base64-data to sign the NOTIFY.'
complete -c ldns-notify -s d --description 'Print verbose debug information.'
complete -c ldns-notify -s r --description 'Specify the maximum number of retries before no… [See Man Page]'

