# ldns-keygen
# Autogenerated from man page /usr/share/man/man1/ldns-keygen.1.gz
# using Deroffing man parser
complete -c ldns-keygen -s a --description 'Create a key with this algorithm.'
complete -c ldns-keygen -s b --description 'Use this many bits for the key length.'
complete -c ldns-keygen -s k --description 'When given, generate a key signing key.'
complete -c ldns-keygen -s r --description 'Make ldns-keygen use this file to seed the rand… [See Man Page]'
complete -c ldns-keygen -s v --description 'Show the version and exit.'

