# ldns-revoke
# Autogenerated from man page /usr/share/man/man1/ldns-revoke.1.gz
# using Deroffing man parser
complete -c ldns-revoke -s n --description 'Write the result to stdout instead of a file.'

