# ldns-read-zone
# Autogenerated from man page /usr/share/man/man1/ldns-read-zone.1.gz
# using Deroffing man parser
complete -c ldns-read-zone -s c --description 'Canonicalize all resource records in the zone before printing.'
complete -c ldns-read-zone -s d --description 'Only print DNSSEC data from the zone.'
complete -c ldns-read-zone -s b --description 'Include Bubble Babble encoding of DS\'s.'
complete -c ldns-read-zone -s 0 --description 'Print a (null) for the RRSIG inception, expiry and key data.'
complete -c ldns-read-zone -s h --description 'Show usage and exit.'
complete -c ldns-read-zone -s n --description 'Do not print the SOA record.'
complete -c ldns-read-zone -s p --description 'Pad the SOA serial number with spaces so the nu… [See Man Page]'
complete -c ldns-read-zone -s s --description 'Strip DNSSEC data from the zone.'
complete -c ldns-read-zone -s S --description 'Set serial number to the given number, or when … [See Man Page]'
complete -c ldns-read-zone -s u --description 'Mark RR type for printing in unknown type format.'
complete -c ldns-read-zone -s U --description 'Mark RR type for not printing in unknown type format.'
complete -c ldns-read-zone -s v --description 'Show the version and exit.'
complete -c ldns-read-zone -o 'U.' --description '.'
complete -c ldns-read-zone -o 'u.' --description '.'
complete -c ldns-read-zone -s z --description 'Sort the zone before printing (this implies -c)… [See Man Page]'

