# ldns-dane
# Autogenerated from man page /usr/share/man/man1/ldns-dane.1.gz
# using Deroffing man parser
complete -c ldns-dane -s 4 --description 'TLS connect IPv4 only.'
complete -c ldns-dane -s 6 --description 'TLS connect IPv6 only.'
complete -c ldns-dane -s a --description 'Don\'t try to resolve name, but connect to address instead.'
complete -c ldns-dane -s b --description 'print "name.'
complete -c ldns-dane -s c --description 'Do not TLS connect to name:port, but authentica… [See Man Page]'
complete -c ldns-dane -s d --description 'Assume DNSSEC validity even when the TLSA recor… [See Man Page]'
complete -c ldns-dane -s f --description 'Use CAfile to validate.'
complete -c ldns-dane -s h --description 'Print short usage help.'
complete -c ldns-dane -s i --description 'Interact after connecting.'
complete -c ldns-dane -s k --description 'Specify a file that contains a trusted DNSKEY or DS rr.'
complete -c ldns-dane -s n --description 'Do not verify server name in certificate.'
complete -c ldns-dane -s o --description 'When creating a "Trust anchor assertion" TLSA r… [See Man Page]'
complete -c ldns-dane -s p --description 'Use certificates in the CApath directory to validate.'
complete -c ldns-dane -s s --description 'When creating TLSA resource records with the "C… [See Man Page]'
complete -c ldns-dane -s S --description 'Chase signature(s) to a known key.'
complete -c ldns-dane -s t --description 'Read TLSA record(s) from tlsafile.'
complete -c ldns-dane -s T --description 'Return exit status 2 for PKIX validated connect… [See Man Page]'
complete -c ldns-dane -s u --description 'Use UDP transport instead of TCP.'
complete -c ldns-dane -s v --description 'Show version and exit.'

