# ldns-zsplit
# Autogenerated from man page /usr/share/man/man1/ldns-zsplit.1.gz
# using Deroffing man parser
complete -c ldns-zsplit -s n --description 'Split after NUMBER RRs, ldns-zsplit will not sp… [See Man Page]'
complete -c ldns-zsplit -s o --description 'use ORIGIN as origin when reading the zonefile.'
complete -c ldns-zsplit -s z --description 'Sort the zone before splitting.'
complete -c ldns-zsplit -s v --description 'Show version number and exit.'

