# ldrdf
# Autogenerated from man page /usr/share/man/man1/ldrdf.1.gz
# using Deroffing man parser
complete -c ldrdf -s o --description 'Specify an output file.   The default output filename is .'
complete -c ldrdf -s v --description 'Increase verbosity level.'
complete -c ldrdf -s p --description 'Change alignment value to which multiple segmen… [See Man Page]'

