# lessecho
# Autogenerated from man page /usr/share/man/man1/lessecho.1.gz
# using Deroffing man parser
complete -c lessecho -o ex --description 'Specifies "x", rather than backslash, to be the… [See Man Page]'
complete -c lessecho -o ox --description 'Specifies "x", rather than double-quote, to be … [See Man Page]'
complete -c lessecho -o cx --description 'Specifies "x" to be the close quote character.'
complete -c lessecho -o pn --description 'Specifies "n" to be the open quote character, as an integer.'
complete -c lessecho -o dn --description 'Specifies "n" to be the close quote character, as an integer.'
complete -c lessecho -o mx --description 'Specifies "x" to be a metachar.'
complete -c lessecho -o nn --description 'Specifies "n" to be a metachar, as an integer.'
complete -c lessecho -o fn --description 'Specifies "n" to be the escape char for metacha… [See Man Page]'
complete -c lessecho -s a --description 'Specifies that all arguments are to be quoted.'

