# lex
# Autogenerated from man page /usr/share/man/man1/lex.1p.gz
# using Deroffing man parser
complete -c lex -s n --description 'Suppress the summary of statistics usually written with the.'
complete -c lex -s v --description 'option.'
complete -c lex -s t --description 'Write the resulting program to standard output instead of lex.'
complete -c lex -s l --description 'operand with c99 ), the resulting program shall… [See Man Page]'
complete -c lex -s c --description 'option and references to the C language are ret… [See Man Page]'

