# lftpget
# Autogenerated from man page /usr/share/man/man1/lftpget.1.gz
# using Type1
complete -c lftpget -s c --description 'Continue a previous download.'
complete -c lftpget -s d --description 'Debug output.'

