# lgroupmod
# Autogenerated from man page /usr/share/man/man1/lgroupmod.1.gz
# using Deroffing man parser
complete -c lgroupmod -s A -l admin-add --description 'Add users in comma-separated list among group\'s administrators.'
complete -c lgroupmod -s a -l admin-remove --description 'Remove users in comma-separated list from group… [See Man Page]'
complete -c lgroupmod -s g -l gid --description 'Change group\'s group ID to gid.'
complete -c lgroupmod -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lgroupmod -s L -l lock --description 'Lock group.'
complete -c lgroupmod -s M -l member-add --description 'Add users in comma-separated list among group\'s members.'
complete -c lgroupmod -s m -l member-remove --description 'Remove users in comma-separated list from group\'s members.'
complete -c lgroupmod -s n -l name --description 'Rename group to name.'
complete -c lgroupmod -s P -l plainpassword --description 'Set group\'s password to password.'
complete -c lgroupmod -s p -l password --description 'Set group\'s password to the password represente… [See Man Page]'
complete -c lgroupmod -s U -l unlock --description 'Unlock group.'

