# lgroupadd
# Autogenerated from man page /usr/share/man/man1/lgroupadd.1.gz
# using Deroffing man parser
complete -c lgroupadd -s g -l gid --description 'Use group ID gid for the newly created group.'
complete -c lgroupadd -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lgroupadd -s r -l reserved --description 'The group is a system group.'

