# lgroupdel
# Autogenerated from man page /usr/share/man/man1/lgroupdel.1.gz
# using Deroffing man parser
complete -c lgroupdel -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'

