# libvirtd
# Autogenerated from man page /usr/share/man/man8/libvirtd.8.gz
# using Type1
complete -c libvirtd -s h -l help --description 'Display command line help usage then exit.'
complete -c libvirtd -s d -l daemon --description 'Run as a daemon & write \\s-1PID\\s0 file.'
complete -c libvirtd -s f -l config --description 'Use this configuration file, overriding the default value.'
complete -c libvirtd -s l -l listen --description 'Listen for \\s-1TCP/IP\\s0 connections.'
complete -c libvirtd -s p -l pid-file --description 'Use this name for the \\s-1PID\\s0 file, overridi… [See Man Page]'
complete -c libvirtd -s t -l timeout --description 'Exit after timeout period (in seconds) elapse w… [See Man Page]'
complete -c libvirtd -s v -l verbose --description 'Enable output of verbose messages.'

