# lid
# Autogenerated from man page /usr/share/man/man1/lid.1.gz
# using Deroffing man parser
complete -c lid -s g -l group --description 'List users in a group name, or in the invoking … [See Man Page]'
complete -c lid -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lid -s n -l onlynames --description 'List only group or user names.'

