# lircrcd
# Autogenerated from man page /usr/share/man/man1/lircrcd.1.gz
# using Deroffing man parser
complete -c lircrcd -s p -l premission --description 'The --permission option gives the file permissi… [See Man Page]'
complete -c lircrcd -s h -l help --description 'display this message.'
complete -c lircrcd -s v -l version --description 'display version.'
complete -c lircrcd -l permission --description 'file permissions for socket.'
complete -c lircrcd -s o -l output --description 'output socket filename OPTIONS.'

