# lircmd
# Autogenerated from man page /usr/share/man/man8/lircmd.8.gz
# using Deroffing man parser
complete -c lircmd -s h -l help --description 'display this message.'
complete -c lircmd -s v -l version --description 'display version.'
complete -c lircmd -s n -l nodaemon --description 'don\'t fork to background.'
complete -c lircmd -s u -l uinput --description 'generate Linux input events OPTIONS If you prov… [See Man Page]'

