# lircd
# Autogenerated from man page /usr/share/man/man8/lircd.8.gz
# using Deroffing man parser
complete -c lircd -s h -l help --description 'display this message.'
complete -c lircd -s v -l version --description 'display version.'
complete -c lircd -s n -l nodaemon --description 'don\'t fork to background.'
complete -c lircd -s p -l permission --description 'file permissions for /var/run/lirc/lircd.'
complete -c lircd -s H -l driver --description 'use given driver.'
complete -c lircd -s d -l device --description 'read from given device.'
complete -c lircd -s l -l 'listen[' --description 'listen for network connections.'
complete -c lircd -s c -l connect --description 'connect to remote lircd server.'
complete -c lircd -s o -l output --description 'output socket filename.'
complete -c lircd -s P -l pidfile --description 'daemon pid file.'
complete -c lircd -s L -l logfile --description 'daemon log file.'
complete -c lircd -s r -l 'release[' --description 'auto-generate release events.'
complete -c lircd -s a -l allow-simulate --description 'accept SIMULATE command.'
complete -c lircd -s u -l uinput --description 'generate Linux input events.'
complete -c lircd -s R -l repeat-max --description 'allow at most this many repeats OPTIONS The --p… [See Man Page]'

