# llvm-dis
# Autogenerated from man page /usr/share/man/man1/llvm-dis.1.gz
# using Deroffing man parser
complete -c llvm-dis -s o --description 'OPTIONS.'
complete -c llvm-dis -s f --description 'Enable binary output on terminals.'
complete -c llvm-dis -o help --description 'Print a summary of command line options.'

