# llvm-as
# Autogenerated from man page /usr/share/man/man1/llvm-as.1.gz
# using Deroffing man parser
complete -c llvm-as -s f --description 'Enable binary output on terminals.'
complete -c llvm-as -o help --description 'Print a summary of command line options.'
complete -c llvm-as -s o --description 'Specify the output file name.'

