# llvm-symbolizer
# Autogenerated from man page /usr/share/man/man1/llvm-symbolizer.1.gz
# using Deroffing man parser
complete -c llvm-symbolizer -o functions --description 'Print function names as well as source file/line locations.'
complete -c llvm-symbolizer -o use-symbol-table --description 'Prefer function names stored in symbol table to… [See Man Page]'
complete -c llvm-symbolizer -o demangle --description 'Print demangled function names.  Defaults to true.'
complete -c llvm-symbolizer -o inlining --description 'If a source code location is in an inlined func… [See Man Page]'
complete -c llvm-symbolizer -o default-arch --description 'If a binary contains object files for multiple … [See Man Page]'

