# llvm-stress
# Autogenerated from man page /usr/share/man/man1/llvm-stress.1.gz
# using Deroffing man parser
complete -c llvm-stress -s o --description 'Specify the output filename. UNINDENT NDENT 0. 0.'
complete -c llvm-stress -o size --description 'Specify the size of the generated . ll file. UNINDENT NDENT 0.'
complete -c llvm-stress -o seed --description 'Specify the seed to be used for the randomly ge… [See Man Page]'

