# llvm-bcanalyzer
# Autogenerated from man page /usr/share/man/man1/llvm-bcanalyzer.1.gz
# using Deroffing man parser
complete -c llvm-bcanalyzer -o nodetails --description 'Causes llvm-bcanalyzer to abbreviate its output… [See Man Page]'
complete -c llvm-bcanalyzer -o dump --description 'Causes llvm-bcanalyzer to dump the bitcode in a… [See Man Page]'
complete -c llvm-bcanalyzer -o verify --description 'Causes llvm-bcanalyzer to verify the module pro… [See Man Page]'
complete -c llvm-bcanalyzer -o help --description 'Print a summary of command line options.'

