# llvm-prof
# Autogenerated from man page /usr/share/man/man1/llvm-prof.1.gz
# using Deroffing man parser
complete -c llvm-prof -l annotated-llvm -s A --description 'In addition to the normal report printed, print… [See Man Page]'
complete -c llvm-prof -l print-all-code --description 'Using this option enables the --annotated-llvm … [See Man Page]'
complete -c llvm-prof -l time-passes --description 'Record the amount of time needed for each pass … [See Man Page]'

