# llvm-build
# Autogenerated from man page /usr/share/man/man1/llvm-build.1.gz
# using Deroffing man parser
complete -c llvm-build -s h -l help --description 'Print the builtin program help.'
complete -c llvm-build -l source-root --description 'If given, load the project at the given source root path.'
complete -c llvm-build -l print-tree --description 'Print the component tree for the project.'
complete -c llvm-build -l write-library-table --description 'Write out the C++ fragment which defines the co… [See Man Page]'
complete -c llvm-build -l write-llvmbuild --description 'Write out new LLVMBuild.'
complete -c llvm-build -l write-cmake-fragment --description 'Write out the LLVMBuild in the form of a CMake … [See Man Page]'
complete -c llvm-build -l write-make-fragment --description 'Write out the LLVMBuild in the form of a Makefi… [See Man Page]'
complete -c llvm-build -l llvmbuild-source-root --description 'If given, expect the LLVMBuild files for the pr… [See Man Page]'

