# llvm-nm
# Autogenerated from man page /usr/share/man/man1/llvm-nm.1.gz
# using Deroffing man parser
complete -c llvm-nm -s B --description 'Use BSD output format.   Alias for --format=bsd.'
complete -c llvm-nm -s P --description 'Use POSIX. 2 output format.   Alias for --format=posix.'
complete -c llvm-nm -l debug-syms -s a --description 'Show all symbols, even debugger only. UNINDENT NDENT 0. 0.'
complete -c llvm-nm -l defined-only --description 'Print only symbols defined in this file (as opp… [See Man Page]'
complete -c llvm-nm -l dynamic -s D --description 'Display dynamic symbols instead of normal symbols.'
complete -c llvm-nm -l extern-only -s g --description 'Print only symbols whose definitions are extern… [See Man Page]'
complete -c llvm-nm -l format -s f --description 'Select an output format; format may be sysv, posix, or bsd.'
complete -c llvm-nm -o help --description 'Print a summary of command-line options and their meanings.'
complete -c llvm-nm -l no-sort -s p --description 'Shows symbols in order encountered. UNINDENT NDENT 0. 0.'
complete -c llvm-nm -l numeric-sort -s n -s v --description 'Sort symbols by address. UNINDENT NDENT 0. 0.'
complete -c llvm-nm -l print-file-name -s A -s o --description 'Precede each symbol with the file it came from.'
complete -c llvm-nm -l print-size -s S --description 'Show symbol size instead of address. UNINDENT NDENT 0. 0.'
complete -c llvm-nm -l size-sort --description 'Sort symbols by size. UNINDENT NDENT 0. 0.'
complete -c llvm-nm -l undefined-only -s u --description 'Print only symbols referenced but not defined in this file.'

