# lnewusers
# Autogenerated from man page /usr/share/man/man1/lnewusers.1.gz
# using Deroffing man parser
complete -c lnewusers -s f -l file --description 'Read account data from file instead of standard input.'
complete -c lnewusers -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lnewusers -s M -l nocreatehome --description 'Don\'t create home directories.'
complete -c lnewusers -s n -l nocreatemail --description 'Don\'t create mail spool files.'

