# localedef
# Autogenerated from man page /usr/share/man/man1/localedef.1p.gz
# using Deroffing man parser
complete -c localedef -s i --description 'option (if specified) or from standard input.'
complete -c localedef -s c --description 'Create permanent output even if warning message… [See Man Page]'
complete -c localedef -s f --description 'Specify the pathname of a file containing a map… [See Man Page]'
complete -c localedef -s u --description '.'
complete -c localedef -s 1 --description 'the result will be undefined.'

