# locale
# Autogenerated from man page /usr/share/man/man1/locale.1p.gz
# using Deroffing man parser
complete -c locale -s f --description 'option when the locale was created shall be wri… [See Man Page]'

