# localectl
# Autogenerated from man page /usr/share/man/man1/localectl.1.gz
# using Deroffing man parser
complete -c localectl -l no-ask-password --description 'Do not query the user for authentication for pr… [See Man Page]'
complete -c localectl -s P -l privileged --description 'Acquire privileges via PolicyKit before executi… [See Man Page]'
complete -c localectl -l no-convert --description 'If set-keymap or set-x11-keymap is invoked and … [See Man Page]'
complete -c localectl -s H -l host --description 'Execute the operation remotely.'
complete -c localectl -s h -l help --description 'Print a short help text and exit.'
complete -c localectl -l version --description 'Print a short version string and exit.'
complete -c localectl -l no-pager --description 'Do not pipe output into a pager.'
complete -c localectl -l 'no-pager.' --description '$SYSTEMD_LESS.'

