# locktest
# Autogenerated from man page /usr/share/man/man1/locktest.1.gz
# using Deroffing man parser
complete -c locktest -s U --description 'Specify the user and password to use when loggi… [See Man Page]'
complete -c locktest -s s --description 'Seed the random number generator with the specified value.'
complete -c locktest -s o --description 'Set the number of operations to perform.'
complete -c locktest -s a --description 'Print the operations that are performed.'
complete -c locktest -s A --description 'Backtrack to find minimal number of operations … [See Man Page]'
complete -c locktest -s O --description 'Enable oplocks.'
complete -c locktest -s u --description 'Hide unlock fails.'
complete -c locktest -s E --description 'enable exact error code checking.'
complete -c locktest -s Z --description 'enable the zero/zero lock.'
complete -c locktest -s R --description 'set lock range.'
complete -c locktest -s B --description 'set lock base.'
complete -c locktest -s M --description 'set min lock length.'
complete -c locktest -s k --description 'Use kerberos.'

