# log2pcap
# Autogenerated from man page /usr/share/man/man1/log2pcap.1.gz
# using Deroffing man parser
complete -c log2pcap -s h --description 'If this parameter is specified the output file … [See Man Page]'
complete -c log2pcap -s q --description 'Be quiet.'
complete -c log2pcap -s '?' -l help --description 'Print a summary of command line options.'

