# losetup
# Autogenerated from man page /usr/share/man/man8/losetup.8.gz
# using Deroffing man parser
complete -c losetup -s a -l all --description 'show status of all loop devices.'
complete -c losetup -s c -l set-capacity --description 'force loop driver to reread size of the file as… [See Man Page]'
complete -c losetup -s d -l detach --description 'detach the file or device associated with the s… [See Man Page]'
complete -c losetup -s D -l detach-all --description 'detach all associated loop devices.'
complete -c losetup -s f -l find --description 'find the first unused loop device.'
complete -c losetup -s h -l help --description 'print help.'
complete -c losetup -s j -l associated --description 'show status of all loop devices associated with given  file.'
complete -c losetup -s l -l list --description 'if a loop device or the -a option is specified,… [See Man Page]'
complete -c losetup -s n -l noheadings --description 'don\'t print headings for --list output format.'
complete -c losetup -s o -l offset --description 'the data start is moved offset bytes into the s… [See Man Page]'
complete -c losetup -s O -l output --description 'specify which columns are to be printed for the --list output.'
complete -c losetup -l sizelimit --description 'the data end is set to no more than size bytes … [See Man Page]'
complete -c losetup -s P -l partscan --description 'force kernel to scan partition table on newly c… [See Man Page]'
complete -c losetup -l raw --description 'use raw --list output format.'
complete -c losetup -s r -l read-only --description 'setup read-only loop device.'
complete -c losetup -l show --description 'print device name if the  -f option and a  file… [See Man Page]'
complete -c losetup -s v -l verbose --description 'verbose mode.'

