# lpasswd
# Autogenerated from man page /usr/share/man/man1/lpasswd.1.gz
# using Deroffing man parser
complete -c lpasswd -s F -l plainpassword-fd --description 'Read password from file descriptor fd, terminat… [See Man Page]'
complete -c lpasswd -s f -l password-fd --description 'Read password hash from file descriptor fd, ter… [See Man Page]'
complete -c lpasswd -s g -l group --description 'Change password of group name.'
complete -c lpasswd -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lpasswd -s P -l plainpassword --description 'Set the password to password.'
complete -c lpasswd -s p -l password --description 'Set the password to the password represented by… [See Man Page]'

