# ls
# Autogenerated from man page /usr/share/man/man1/ls.1p.gz
# using Deroffing man parser
complete -c ls -o laRF --description 'in the POSIX locale: total 11 drwxr-xr-x   3 fo… [See Man Page]'
complete -c ls -o rwxr--r-- --description '.'
complete -c ls -o rw-r--r-- --description 'RATIONALE Some historical implementations of th… [See Man Page]'

