# lslocks
# Autogenerated from man page /usr/share/man/man8/lslocks.8.gz
# using Deroffing man parser
complete -c lslocks -s h -l help --description 'Display help text and exit.'
complete -c lslocks -s n -l noheadings --description 'Do not print a header line.'
complete -c lslocks -s o -l output --description 'Specify which output columns to print.'
complete -c lslocks -s p -l pid --description 'Display only the locks held by the process with this pid.'
complete -c lslocks -s r -l raw --description 'Use the raw output format.'
complete -c lslocks -s u -l notruncate --description 'Do not truncate text in columns.'

