# lua5
# Autogenerated from man page /usr/share/man/man1/lua5.1.1.gz
# using Deroffing man parser
complete -c lua5 -s e --description 'execute statement R stat .'
complete -c lua5 -s i --description 'enter interactive mode after  script is executed.'
complete -c lua5 -s l --description 'call  require(\' name \') before executing R script .'
complete -c lua5 -s v --description 'is assumed when the standard input is a terminal; otherwise,.'

