# luakit
# Autogenerated from man page /usr/share/man/man1/luakit.1.gz
# using Deroffing man parser
complete -c luakit -s h -l help --description 'Show help options.'
complete -c luakit -l help-all --description 'Show all help options.'
complete -c luakit -l help-gtk --description 'Show GTK+ Options . SS "Application Options:".'
complete -c luakit -s k -l check --description 'check config and exit.'
complete -c luakit -s c -l config --description 'configuration file to use.'
complete -c luakit -s n -l nonblock --description 'run in background.'
complete -c luakit -s U -l nounique --description 'ignore libunique bindings.'
complete -c luakit -s u -l uri --description 'uri(s) to load at startup.'
complete -c luakit -s v -l verbose --description 'print debugging output.'
complete -c luakit -s V -l version --description 'print version and exit.'
complete -c luakit -l display --description 'X display to use.'

