# lusermod
# Autogenerated from man page /usr/share/man/man1/lusermod.1.gz
# using Deroffing man parser
complete -c lusermod -s c -l gecos --description 'Set user\'s \\f[SM]GECOS field to gecos.'
complete -c lusermod -s d -l directory --description 'Set user\'s home directory to directory.'
complete -c lusermod -s g -l gid --description 'Change user\'s primary group ID to gid.'
complete -c lusermod -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c lusermod -s L -l lock --description 'Lock user\'s account.'
complete -c lusermod -s l -l login --description 'Rename user to name.'
complete -c lusermod -s m -l movedirectory --description 'After changing user\'s home directory (using the… [See Man Page]'
complete -c lusermod -s P -l plainpassword --description 'Set user\'s password to password.'
complete -c lusermod -s p -l password --description 'Set user\'s password to the password represented… [See Man Page]'
complete -c lusermod -s s -l shell --description 'Set user\'s login shell to shell.'
complete -c lusermod -s U -l unlock --description 'Unlock user\'s account.'
complete -c lusermod -s u -l uid --description 'Change user\'s user ID to uid.'
complete -c lusermod -l commonname --description 'Set user\'s common name to name.'
complete -c lusermod -l givenname --description 'Set user\'s given name to name.'
complete -c lusermod -l homephone --description 'Set user\'s home telephone number to phone.'
complete -c lusermod -l roomnumber --description 'Set user\'s room number to room.'
complete -c lusermod -l surname --description 'Set user\'s surname to name.'
complete -c lusermod -l telephonenumber --description 'Set user\'s telephone number to phone.'

