# luserdel
# Autogenerated from man page /usr/share/man/man1/luserdel.1.gz
# using Deroffing man parser
complete -c luserdel -s G -l dontremovegroup --description 'By default the user\'s primary group is removed … [See Man Page]'
complete -c luserdel -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c luserdel -s r -l removehome --description 'Remove user\'s home directory and mail spool aft… [See Man Page]'

