# luseradd
# Autogenerated from man page /usr/share/man/man1/luseradd.1.gz
# using Deroffing man parser
complete -c luseradd -s c -l gecos --description 'Set the \\f[SM]GECOS field to gecos.'
complete -c luseradd -s d -l directory --description 'Set user\'s home directory to directory.'
complete -c luseradd -s g -l gid --description 'Set user\'s primary group to group.'
complete -c luseradd -s i -l interactive --description 'Ask all questions when connecting to the user d… [See Man Page]'
complete -c luseradd -s k -l skeleton --description 'Populate the newly created user\'s home director… [See Man Page]'
complete -c luseradd -s M -l nocreatehome --description 'Don\'t create a home directory and a mail spool … [See Man Page]'
complete -c luseradd -s n -l nocreategroup --description 'If a group is not specified using -g, use group… [See Man Page]'
complete -c luseradd -s P -l plainpassword --description 'Set user\'s password to password.'
complete -c luseradd -s p -l password --description 'Set user\'s password to the password represented… [See Man Page]'
complete -c luseradd -s r -l reserved --description 'The user is a system user.'
complete -c luseradd -s s -l shell --description 'Set user\'s login shell to shell.'
complete -c luseradd -s u -l uid --description 'Use user ID uid for the newly created user.'
complete -c luseradd -l commonname --description 'Use common name  name for the newly created user.'
complete -c luseradd -l givenname --description 'Use given name  name for the newly created user.'
complete -c luseradd -l homephone --description 'Use home telephone number  phone for the newly created user.'
complete -c luseradd -l roomnumber --description 'Use room number  room for the newly created user.'
complete -c luseradd -l surname --description 'Use surname  name for the newly created user.'
complete -c luseradd -l telephonenumber --description 'Use telephone number phone for the newly created user.'

