# lvdisplay
# Autogenerated from man page /usr/share/man/man8/lvdisplay.8.gz
# using Deroffing man parser
complete -c lvdisplay -l all --description 'Include information in the output about interna… [See Man Page]'
complete -c lvdisplay -s c -l colon --description 'Generate colon separated output for easier pars… [See Man Page]'
complete -c lvdisplay -s m -l maps --description 'Display the mapping of logical extents to physi… [See Man Page]'
complete -c lvdisplay -l 'columns.' --description '.'
complete -c lvdisplay -l columns -s C --description 'Display output in columns, the equivalent of lvs.'

