# lvextend
# Autogenerated from man page /usr/share/man/man8/lvextend.8.gz
# using Deroffing man parser
complete -c lvextend -s f -l force --description 'Proceed with size extension without prompting.'
complete -c lvextend -s l -l extents --description 'Extend or set the logical volume size in units … [See Man Page]'
complete -c lvextend -s L -l size --description 'Extend or set the logical volume size in units of megabytes.'
complete -c lvextend -s i -l stripes --description 'Gives the number of stripes for the extension.'
complete -c lvextend -s I -l stripesize --description 'Gives the number of kilobytes for the granulari… [See Man Page]'
complete -c lvextend -s n -l nofsck --description 'Do not perform fsck before extending filesystem… [See Man Page]'
complete -c lvextend -l noudevsync --description 'Disable udev synchronisation.'
complete -c lvextend -s r -l resizefs --description 'Resize underlying filesystem together with the … [See Man Page]'
complete -c lvextend -l use-policies --description 'Resizes the logical volume according to configured policy.'

