# lvm
# Autogenerated from man page /usr/share/man/man8/lvm.8.gz
# using Deroffing man parser
complete -c lvm -s h -s '?' -l help --description 'Display the help text.'
complete -c lvm -l version --description 'Display version information.'
complete -c lvm -s v -l verbose --description 'Set verbose level.'
complete -c lvm -s d -l debug --description 'Set debug level.'
complete -c lvm -s q -l quiet --description 'Suppress output and log messages.  Overrides -d and -v.'
complete -c lvm -l yes --description 'Don\'t prompt for confirmation interactively but… [See Man Page]'
complete -c lvm -s t -l test --description 'Run in test mode.  Commands will not update metadata.'
complete -c lvm -l driverloaded --description 'Whether or not the device-mapper kernel driver is loaded.'
complete -c lvm -s A -l autobackup --description 'Whether or not to metadata should be backed up … [See Man Page]'
complete -c lvm -s P -l partial --description 'When set, the tools will do their best to provi… [See Man Page]'
complete -c lvm -s M -l metadatatype --description 'Specifies which type of on-disk metadata to use… [See Man Page]'
complete -c lvm -l ignorelockingfailure --description 'This lets you proceed with read-only metadata o… [See Man Page]'
complete -c lvm -l ignoreskippedcluster --description 'Use to avoid exiting with an non-zero status co… [See Man Page]'
complete -c lvm -l addtag --description 'Add the tag Tag to a PV, VG or LV.'
complete -c lvm -l deltag --description 'Delete the tag Tag from a PV, VG or LV, if it\'s present.'
complete -c lvm -l alloc --description 'Selects the allocation policy when a command ne… [See Man Page]'
complete -c lvm -l profile --description 'Selects the configuration profile to use when p… [See Man Page]'
complete -c lvm -l config --description 'Uses the ConfigurationString as direct string r… [See Man Page]'

