# lvmconf
# Autogenerated from man page /usr/share/man/man8/lvmconf.8.gz
# using Type1
complete -c lvmconf -l disable-cluster --description 'Set locking_type to the default non-clustered type.'
complete -c lvmconf -l enable-cluster --description 'Set locking_type to the default clustered type on this system.'
complete -c lvmconf -l file --description 'Apply the changes to configfile instead of the … [See Man Page]'
complete -c lvmconf -l lockinglib --description 'Set external locking_library locking library to… [See Man Page]'

