# lvmdump
# Autogenerated from man page /usr/share/man/man8/lvmdump.8.gz
# using Deroffing man parser
complete -c lvmdump -s a --description 'Advanced collection.'
complete -c lvmdump -s c --description 'If clvmd is running, gather cluster data as well.'
complete -c lvmdump -s d --description 'Dump into a directory instead of tarball By def… [See Man Page]'
complete -c lvmdump -s h --description 'Print help message.'
complete -c lvmdump -s l --description 'Include lvmetad(8) daemon dump if it is running.'
complete -c lvmdump -s m --description 'Gather LVM metadata from the PVs This option ge… [See Man Page]'
complete -c lvmdump -s u --description 'OPTIONS.'

