# lvresize
# Autogenerated from man page /usr/share/man/man8/lvresize.8.gz
# using Deroffing man parser
complete -c lvresize -s f -l force --description 'Force resize without prompting even when it may… [See Man Page]'
complete -c lvresize -s n -l nofsck --description 'Do not perform fsck before resizing filesystem … [See Man Page]'
complete -c lvresize -s r -l resizefs --description 'Resize underlying filesystem together with the … [See Man Page]'
complete -c lvresize -s l -l extents --description 'Change or set the logical volume size in units … [See Man Page]'
complete -c lvresize -s L -l size --description 'Change or set the logical volume size in units of megabytes.'
complete -c lvresize -s i -l stripes --description 'Gives the number of stripes to use when extendi… [See Man Page]'
complete -c lvresize -l poolmetadatasize --description 'Change or set the thin pool metadata logical volume size.'
complete -c lvresize -s I -l stripesize --description 'Gives the number of kilobytes for the granulari… [See Man Page]'
complete -c lvresize -l noudevsync --description 'Disable udev synchronisation.'

