# lvreduce
# Autogenerated from man page /usr/share/man/man8/lvreduce.8.gz
# using Deroffing man parser
complete -c lvreduce -s f -l force --description 'Force size reduction without prompting even whe… [See Man Page]'
complete -c lvreduce -s l -l extents --description 'Reduce or set the logical volume size in units … [See Man Page]'
complete -c lvreduce -s L -l size --description 'Reduce or set the logical volume size in units of megabytes.'
complete -c lvreduce -s n -l nofsck --description 'Do not perform fsck before resizing filesystem … [See Man Page]'
complete -c lvreduce -l noudevsync --description 'Disable udev synchronisation.'
complete -c lvreduce -s r -l resizefs --description 'Resize underlying filesystem together with the … [See Man Page]'

