# lvs
# Autogenerated from man page /usr/share/man/man8/lvs.8.gz
# using Deroffing man parser
complete -c lvs -l aligned --description 'Use with --separator to align the output columns.'
complete -c lvs -l all --description 'Include information in the output about interna… [See Man Page]'
complete -c lvs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c lvs -l noheadings --description 'Suppress the headings line that is normally the… [See Man Page]'
complete -c lvs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c lvs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c lvs -l segments --description 'otherwise any "lv_" prefixes are optional.'
complete -c lvs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c lvs -l rows --description 'Output columns as rows.'
complete -c lvs -l separator --description 'String to use to separate each column.'
complete -c lvs -l unbuffered --description 'Produce output immediately without sorting or a… [See Man Page]'
complete -c lvs -l units --description 'All sizes are output in these units: (h)uman-re… [See Man Page]'
complete -c lvs -l unquoted --description 'When used with --nameprefixes, output values in… [See Man Page]'

