# lxc-clone
# Autogenerated from man page /usr/share/man/man1/lxc-clone.1.gz
# using Deroffing man parser
complete -c lxc-clone -l 'snapshot\\*(T>' --description 'The new container\'s rootfs should be a LVM or b… [See Man Page]'
complete -c lxc-clone -l 'keepname\\*(T>' --description 'Do not change the hostname of the container (in… [See Man Page]'
complete -c lxc-clone -l 'keepmac\\*(T>' --description 'Use the same MAC address as the original contai… [See Man Page]'
complete -c lxc-clone -l 'copyhooks\\*(T>' --description 'Copy all mount hooks into the new container\'s d… [See Man Page]'
complete -c lxc-clone -l fssize --description 'In the case of a block device backed container,… [See Man Page]'
complete -c lxc-clone -l lxcpath --description 'The lxcpath of the original container.'
complete -c lxc-clone -l newpath --description 'The lxcpath for the new container.'
complete -c lxc-clone -l backingstore --description 'Select a different backing store for the new container.'
complete -c lxc-clone -l orig --description 'The name of the original container to clone.'
complete -c lxc-clone -s B --description '.'
complete -c lxc-clone -s o -s n --description 'respectively.  OPTIONS.'

