# lxc-start
# Autogenerated from man page /usr/share/man/man1/lxc-start.1.gz
# using Deroffing man parser
complete -c lxc-start -l 'daemon\\*(T>' --description 'Run the container as a daemon.'
complete -c lxc-start -l pidfile --description 'Create a file with the process id.'
complete -c lxc-start -l rcfile --description 'Specify the configuration file to configure the… [See Man Page]'
complete -c lxc-start -l console --description 'Specify a device to use for the container\'s con… [See Man Page]'
complete -c lxc-start -l console-log --description 'Specify a file to log the container\'s console output to.'
complete -c lxc-start -l define --description 'Assign value VAL to configuration variable KEY.'
complete -c lxc-start -l 'close-all-fds\\*(T>' --description 'If any file descriptors are inherited, close them.'
complete -c lxc-start -l 'close-all-fds.' --description '.'

