# lxc-create
# Autogenerated from man page /usr/share/man/man1/lxc-create.1.gz
# using Deroffing man parser
complete -c lxc-create -l dir --description 'that the container rootfs should be placed unde… [See Man Page]'
complete -c lxc-create -l lvname --description 'named \\fIlvname1 rather than the default, which… [See Man Page]'
complete -c lxc-create -l thinpool --description 'LV as a thin-provisioned volume in the pool nam… [See Man Page]'
complete -c lxc-create -l fstype --description 'filesystem on the LV, rather than the default, which is ext4.'
complete -c lxc-create -l fssize --description 'filesystem) of size SIZE rather than the default, which is 1G.'

