# machinectl
# Autogenerated from man page /usr/share/man/man1/machinectl.1.gz
# using Deroffing man parser
complete -c machinectl -s p -l property --description 'When showing machine properties, limit the outp… [See Man Page]'
complete -c machinectl -s a -l all --description 'When showing machine properties, show all prope… [See Man Page]'
complete -c machinectl -s l -l full --description 'Do not ellipsize process tree entries.'
complete -c machinectl -l kill-who --description 'When used with kill, choose which processes to kill.'
complete -c machinectl -s s -l signal --description 'When used with kill, choose which signal to sen… [See Man Page]'
complete -c machinectl -l no-legend --description 'Do not print the legend, i. e.'
complete -c machinectl -s H -l host --description 'Execute the operation remotely.'
complete -c machinectl -s M -l machine --description 'Execute operation on a local container.'
complete -c machinectl -s h -l help --description 'Print a short help text and exit.'
complete -c machinectl -l version --description 'Print a short version string and exit.'
complete -c machinectl -l no-pager --description 'Do not pipe output into a pager.'
complete -c machinectl -l 'no-pager.' --description '$SYSTEMD_LESS.'

