# mactime
# Autogenerated from man page /usr/share/man/man1/mactime.1.gz
# using Deroffing man parser
complete -c mactime -s b --description 'Specify the location of a body file.'
complete -c mactime -s g --description 'Specify the location of the group file.'
complete -c mactime -s p --description 'Specify the location of the passwd file.'
complete -c mactime -s i --description 'Specify the location of an index file to write to.'
complete -c mactime -s d --description 'Display timeline and index files in comma delimited format.'
complete -c mactime -s h --description 'Display header info about the session including… [See Man Page]'
complete -c mactime -s V --description 'Display version to STDOUT.'
complete -c mactime -s m --description 'The month is given as a number instead of name … [See Man Page]'
complete -c mactime -s y --description 'The date is displayed in ISO8601 format.'
complete -c mactime -s z --description 'The timezone from where the data was collected.'

