# masktest
# Autogenerated from man page /usr/share/man/man1/masktest.1.gz
# using Deroffing man parser
complete -c masktest -s U --description 'Specify the user and password to use when loggi… [See Man Page]'
complete -c masktest -s s --description 'Seed the random number generator with the specified value.'
complete -c masktest -s n --description 'Set the number of operations to perform.'
complete -c masktest -s a --description 'Print the operations that are performed.'
complete -c masktest -s M --description 'Maximum protocol to use.'
complete -c masktest -s f --description 'Specify characters that can be used when generating file names.'
complete -c masktest -s E --description 'Abort when difference in behaviour is found.'
complete -c masktest -s m --description 'Specify characters used for wildcards.'
complete -c masktest -s v --description 'Be verbose.'

