# mcabber
# Autogenerated from man page /usr/share/man/man1/mcabber.1.gz
# using Deroffing man parser
complete -c mcabber -s h --description 'Quick help usage message.'
complete -c mcabber -s V --description 'Displays mcabber version and compile-time definitions.'
complete -c mcabber -s f --description 'Use configuration file configfile.'
complete -c mcabber -l - --description '.'

