# mcookie
# Autogenerated from man page /usr/share/man/man1/mcookie.1.gz
# using Deroffing man parser
complete -c mcookie -s f -l file --description 'Use file as a macig cookie seed.'
complete -c mcookie -s v -l verbose --description 'Explain what is being done.'
complete -c mcookie -s V -l version --description 'Display version information and exit.'
complete -c mcookie -s h -l help --description 'Display help text and exit.'

