# mdmon
# Autogenerated from man page /usr/share/man/man8/mdmon.8.gz
# using Deroffing man parser
complete -c mdmon -l foreground --description 'Normally,  mdmon will fork and continue in the background.'
complete -c mdmon -l takeover --description 'This instructs  mdmon to replace any active  md… [See Man Page]'
complete -c mdmon -l all --description 'This tells mdmon to find any active containers … [See Man Page]'
complete -c mdmon -l all-active-arrays --description 'Note that mdmon is automatically started by mda… [See Man Page]'

