# metalog
# Autogenerated from man page /usr/share/man/man8/metalog.8.gz
# using Type1
complete -c metalog -s a -l async --description 'Improve performance by using buffers (bug log f… [See Man Page]'
complete -c metalog -s B -l daemonize --description 'have the server start in background (daemonization).'
complete -c metalog -s c -l consolelevel --description 'Set the console log level (Linux only).'
complete -c metalog -s C -l configfile --description 'Use an alternate configuration file.'
complete -c metalog -s h -l help --description 'Output help information and exit.'
complete -c metalog -s N -l no-kernel --description 'Do not attempt to log messages from the kernel.'
complete -c metalog -s P -l pidfile --description 'Use an alternate file to store the process number.'
complete -c metalog -s s -l sync -l synchronous --description 'Start in synchronous mode, with no bufferization.'
complete -c metalog -s v -l verbose --description 'Run in verbose mode (useful for debugging behavior).'

