# mev
# Autogenerated from man page /usr/share/man/man1/mev.1.gz
# using Deroffing man parser
complete -c mev -s C --description 'Select a virtual console to get events from.'
complete -c mev -s d --description 'Choose a default mask.'
complete -c mev -s e --description 'Choose the event mask.  By default any event is received.'
complete -c mev -s E --description 'Enter emacs mode.'
complete -c mev -s f --description 'Fit events inside the screen before reporting them.'
complete -c mev -s i --description 'Interactive.'
complete -c mev -s m --description 'Choose the minimum modifier mask.'
complete -c mev -s M --description 'Choose the maximum modifier mask.'
complete -c mev -s p --description 'Requests to draw the pointer during drags.'

