# mkreiserfs
# Autogenerated from man page /usr/share/man/man8/mkreiserfs.8.gz
# using Deroffing man parser
complete -c mkreiserfs -s b -l block-size --description 'N is block size in bytes.'
complete -c mkreiserfs -s h -l hash --description 'HASH specifies which hash function will sort th… [See Man Page]'
complete -c mkreiserfs -l format --description 'FORMAT specifies the format for the new filsystem.'
complete -c mkreiserfs -s u -l uuid --description 'Sets  the  Universally  Unique  IDentifier  of … [See Man Page]'
complete -c mkreiserfs -s l -l label --description 'Sets  the  volume  label  of  the filesystem.'
complete -c mkreiserfs -s q -l quiet --description 'Sets mkreiserfs to work quietly without produci… [See Man Page]'
complete -c mkreiserfs -s j -l journal-device --description 'FILE is the name of the block device on which i… [See Man Page]'
complete -c mkreiserfs -s o -l journal-offset --description 'N is the offset where the journal starts when i… [See Man Page]'
complete -c mkreiserfs -s s -l journal-size --description 'N is the size of the journal in blocks.'
complete -c mkreiserfs -s t -l transaction-max-size --description 'N is the maximum transaction size parameter for the journal.'
complete -c mkreiserfs -s B -l badblocks --description 'File is the file name of the file that contains… [See Man Page]'
complete -c mkreiserfs -s f --description 'Forces mkreiserfs to continue even when the dev… [See Man Page]'
complete -c mkreiserfs -s d --description 'Sets mkreiserfs to print debugging information … [See Man Page]'
complete -c mkreiserfs -s V --description 'Prints the version and then exits.'

