# mmls
# Autogenerated from man page /usr/share/man/man1/mmls.1.gz
# using Deroffing man parser
complete -c mmls -s t --description 'Specify the media management type.'
complete -c mmls -s o --description 'Specify the offset into the image where the vol… [See Man Page]'
complete -c mmls -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c mmls -s i --description 'Identify the type of image file, such as raw.'
complete -c mmls -s B --description 'Include a column with the partition sizes in bytes.'
complete -c mmls -s r --description 'Recurse into DOS partitions and look for other … [See Man Page]'
complete -c mmls -s v --description 'Verbose output of debugging statements to stderr.'
complete -c mmls -s V --description 'Display version.'
complete -c mmls -s a --description 'Show allocated volumes.'
complete -c mmls -s A --description 'Show unallocated volumes.'
complete -c mmls -s m --description 'Show metadata volumes.'
complete -c mmls -s M --description 'Hide metadata volumes image [images] The disk o… [See Man Page]'

