# mmstat
# Autogenerated from man page /usr/share/man/man1/mmstat.1.gz
# using Deroffing man parser
complete -c mmstat -s t --description 'Specify the media management type.'
complete -c mmstat -s o --description 'Specify the offset into the image where the vol… [See Man Page]'
complete -c mmstat -s b --description 'The size, in bytes, of the underlying device sectors.'
complete -c mmstat -s i --description 'Identify the type of image file, such as raw.'
complete -c mmstat -s v --description 'Verbose output of debugging statements to stderr.'
complete -c mmstat -s V --description 'Display version image [images] The disk or part… [See Man Page]'

