# mode2
# Autogenerated from man page /usr/share/man/man1/mode2.1.gz
# using Deroffing man parser
complete -c mode2 -s h -l help --description 'display usage summary.'
complete -c mode2 -s v -l version --description 'display version.'
complete -c mode2 -s d -l device --description 'read from given device.'
complete -c mode2 -s H -l driver --description 'use given driver.'
complete -c mode2 -s m -l mode --description 'enable alternative display mode.'
complete -c mode2 -s r -l raw --description 'access device directly SEE ALSO mode2(1), smode2(1), xmode2(1).'

