# modinfo
# Autogenerated from man page /usr/share/man/man8/modinfo.8.gz
# using Deroffing man parser
complete -c modinfo -s V -l version --description 'Print the modinfo version.'
complete -c modinfo -s F -l field --description 'Only print this field value, one per line.'
complete -c modinfo -s b -l basedir --description 'Root directory for modules, / by default.'
complete -c modinfo -s k --description 'Provide information about a kernel other than the running one.'
complete -c modinfo -s 0 -l null --description 'Use the ASCII zero character to separate field … [See Man Page]'
complete -c modinfo -s a -l author -s d -l description -s l -l license -s p -l parameters -s n -l filename --description 'These are shortcuts for the --field flag\\*(Aqs … [See Man Page]'

