# mosh-server
# Autogenerated from man page /usr/share/man/man1/mosh-server.1.gz
# using Deroffing man parser
complete -c mosh-server -s s --description 'bind to the local interface used for an incomin… [See Man Page]'
complete -c mosh-server -s v --description 'Print some debugging information even after detaching.'
complete -c mosh-server -s i --description 'IP address of the local interface to bind (for … [See Man Page]'
complete -c mosh-server -s p --description 'UDP port number or port-range to bind.'
complete -c mosh-server -s c --description 'Number of colors to advertise to applications through TERM (e.'
complete -c mosh-server -s l --description 'Locale-related environment variable to try as p… [See Man Page]'

