# mosh
# Autogenerated from man page /usr/share/man/man1/mosh.1.gz
# using Deroffing man parser
complete -c mosh -l client --description 'path to client helper on local machine (default… [See Man Page]'
complete -c mosh -l server --description 'command to run server helper on remote machine … [See Man Page]'
complete -c mosh -l ssh --description 'OpenSSH command to remotely execute mosh-server… [See Man Page]'
complete -c mosh -l predict --description 'Controls use of speculative local echo.'
complete -c mosh -s a --description 'Synonym for --predict=always.'
complete -c mosh -s n --description 'Synonym for --predict=never.'
complete -c mosh -s p -l port --description 'Use a particular server-side UDP port or port r… [See Man Page]'
complete -c mosh -l no-init --description 'Do not send the smcup initialization string and… [See Man Page]'

