# mountpoint
# Autogenerated from man page /usr/share/man/man1/mountpoint.1.gz
# using Deroffing man parser
complete -c mountpoint -s h -l help --description 'Display help text and exit.'
complete -c mountpoint -s q -l quiet --description 'Be quiet - don\'t print anything.'
complete -c mountpoint -s d -l fs-devno --description 'Print major/minor device number of the filesystem on stdout.'
complete -c mountpoint -s x -l devno --description 'Print major/minor device number of the blockdevice on stdout.'

