# mp4art
# Autogenerated from man page /usr/share/man/man1/mp4art.1.gz
# using Deroffing man parser
complete -c mp4art -l list --description 'list all covr-boxes.'
complete -c mp4art -l add --description 'add covr-box from IMG file.'
complete -c mp4art -l replace --description 'replace covr-box with IMG file.'
complete -c mp4art -l remove --description 'remove covr-box.'
complete -c mp4art -l extract --description 'extract covr-box . PP ACTION PARAMETERS.'
complete -c mp4art -l art-any --description 'act on all covr-boxes (default).'
complete -c mp4art -l art-index --description 'act on covr-box index IDX . PP OPTIONS.'
complete -c mp4art -s z -l optimize --description 'optimize mp4 file after modification.'
complete -c mp4art -s y -l dryrun --description 'do not actually create or modify any files.'
complete -c mp4art -s k -l keepgoing --description 'continue batch processing even after errors.'
complete -c mp4art -s o -l overwrite --description 'overwrite existing files when creating.'
complete -c mp4art -s f -l force --description 'force overwrite even if file is read-only.'
complete -c mp4art -s q -l quiet --description 'equivalent to --verbose 0.'
complete -c mp4art -s d -l debug --description 'increase debug or long-option to set NUM.'
complete -c mp4art -s v -l verbose --description 'increase verbosity or long-option to set NUM.'
complete -c mp4art -s h -l help --description 'print brief help or long-option for extended help.'
complete -c mp4art -l version --description 'print version information and exit .'

