# mp4file
# Autogenerated from man page /usr/share/man/man1/mp4file.1.gz
# using Deroffing man parser
complete -c mp4file -l list --description 'list (summary information).'
complete -c mp4file -l optimize --description 'optimize mp4 structure.'
complete -c mp4file -l dump --description 'dump mp4 structure in human-readable format . PP OPTIONS.'
complete -c mp4file -s y -l dryrun --description 'do not actually create or modify any files.'
complete -c mp4file -s k -l keepgoing --description 'continue batch processing even after errors.'
complete -c mp4file -s q -l quiet --description 'equivalent to --verbose 0.'
complete -c mp4file -s d -l debug --description 'increase debug or long-option to set NUM.'
complete -c mp4file -s v -l verbose --description 'increase verbosity or long-option to set NUM.'
complete -c mp4file -s h -l help --description 'print brief help or long-option for extended help.'
complete -c mp4file -l version --description 'print version information and exit .'

