# mp4subtitle
# Autogenerated from man page /usr/share/man/man1/mp4subtitle.1.gz
# using Deroffing man parser
complete -c mp4subtitle -l list --description 'list available subtitles.'
complete -c mp4subtitle -l export --description 'export subtitles to TXT.'
complete -c mp4subtitle -l import --description 'import subtitles from TXT.'
complete -c mp4subtitle -l remove --description 'remove all subtitles . PP OPTIONS.'
complete -c mp4subtitle -s z -l optimize --description 'optimize mp4 file after modification.'
complete -c mp4subtitle -s y -l dryrun --description 'do not actually create or modify any files.'
complete -c mp4subtitle -s k -l keepgoing --description 'continue batch processing even after errors.'
complete -c mp4subtitle -s o -l overwrite --description 'overwrite existing files when creating.'
complete -c mp4subtitle -s f -l force --description 'force overwrite even if file is read-only.'
complete -c mp4subtitle -s q -l quiet --description 'equivalent to --verbose 0.'
complete -c mp4subtitle -s d -l debug --description 'increase debug or long-option to set NUM.'
complete -c mp4subtitle -s v -l verbose --description 'increase verbosity or long-option to set NUM.'
complete -c mp4subtitle -s h -l help --description 'print brief help or long-option for extended help.'
complete -c mp4subtitle -l version --description 'print version information and exit .'

