# mpeg2dec
# Autogenerated from man page /usr/share/man/man1/mpeg2dec.1.gz
# using Deroffing man parser
complete -c mpeg2dec -s h --description 'display help and available video modes.'
complete -c mpeg2dec -s s --description 'use program stream demultiplexer, track 0-0xf or 0xe0-0xef.'
complete -c mpeg2dec -s t --description 'use transport stream demultiplexer, pid 0x10-0x1ffe.'
complete -c mpeg2dec -s c --description 'use c implementation, disables all accelerations.'
complete -c mpeg2dec -s o --description 'use video output driver `mode\'.'

