# multixterm
# Autogenerated from man page /usr/share/man/man1/multixterm.1.gz
# using Deroffing man parser
complete -c multixterm -o xa --description 'The optional -xa argument indicates arguments to pass to xterm.'
complete -c multixterm -o xc --description 'The optional -xc argument indicates a command t… [See Man Page]'
complete -c multixterm -o xd --description 'The optional -xd argument indicates a directory… [See Man Page]'
complete -c multixterm -o xf --description 'The optional -xf argument indicates a file to b… [See Man Page]'
complete -c multixterm -o xn --description 'The optional -xn argument indicates a name for each xterm.'
complete -c multixterm -o xv --description 'The optional -xv flag puts multixterm into a ve… [See Man Page]'
complete -c multixterm -o 'name).' --description 'make them easy to remember, all the multixterm … [See Man Page]'

