# ncftpbatch
# Autogenerated from man page /usr/share/man/man1/ncftpbatch.1.gz
# using Type1
complete -c ncftpbatch -s d --description 'Begin background processing of FTP jobs in the … [See Man Page]'
complete -c ncftpbatch -s l --description 'Lists the contents of the user\'s job queue.'

