# ncftpls
# Autogenerated from man page /usr/share/man/man1/ncftpls.1.gz
# using Type1
complete -c ncftpls -s m --description 'Use a machine readable list format, if the server supports it.'
complete -c ncftpls -s 1 --description 'Most basic format, one item per line.'
complete -c ncftpls -s l --description 'Long list format.'
complete -c ncftpls -s C --description 'Columnized list format.  This is the default list format.'
complete -c ncftpls -s R --description 'Recurse all subdirectories while listing.'
complete -c ncftpls -s a --description 'Show all files, if server allows it (as in "/bin/ls -a").'
complete -c ncftpls -s i --description 'Filter the listing (if server supports it) with… [See Man Page]'
complete -c ncftpls -s x --description 'Set the  ls flags to use on the server.'
complete -c ncftpls -s u --description 'Use username  XX instead of anonymous.'
complete -c ncftpls -s p --description 'Use password  XX with the username.'
complete -c ncftpls -s P --description 'Use port number  XX instead of the default FTP … [See Man Page]'
complete -c ncftpls -s d --description 'Use the file  XX for debug logging.'
complete -c ncftpls -s t --description 'Timeout after  XX seconds.'
complete -c ncftpls -s E --description 'Use regular (PORT) data connections.'
complete -c ncftpls -s F --description 'Use passive (PASV) data connections.'
complete -c ncftpls -s r --description 'Redial a maximum of   XX times until connected … [See Man Page]'
complete -c ncftpls -s W --description 'Send raw FTP command  XX after logging in.'
complete -c ncftpls -s X --description 'Send raw FTP command  XX after each file transferred.'
complete -c ncftpls -s Y --description 'Send raw FTP command  XX before logging out.'

