# ncftp
# Autogenerated from man page /usr/share/man/man1/ncftp.1.gz
# using Deroffing man parser
complete -c ncftp -s u --description 'Use username XX instead of anonymous.'
complete -c ncftp -s p --description 'Use password XX with the username.'
complete -c ncftp -s j --description 'Use account  XX in supplement to the username a… [See Man Page]'
complete -c ncftp -s P --description 'Use port number XX instead of the default FTP s… [See Man Page]'

