# newusers
# Autogenerated from man page /usr/share/man/man8/newusers.8.gz
# using Deroffing man parser
complete -c newusers -s c -l crypt-method --description 'Use the specified method to encrypt the passwords.'
complete -c newusers -s h -l help --description 'Display help message and exit.'
complete -c newusers -s r -l system --description 'Create a system account.'
complete -c newusers -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c newusers -s s -l sha-rounds --description 'Use the specified number of rounds to encrypt the passwords.'

