# nice
# Autogenerated from man page /usr/share/man/man1/nice.1p.gz
# using Deroffing man parser
complete -c nice -s x --description 'utility , for example, would be treated the sam… [See Man Page]'
complete -c nice -l 1 --description 'utility .'
complete -c nice -s 0 --description 'utility , while 4.'

