# nl-qdisc-add
# Autogenerated from man page /usr/share/man/man8/nl-qdisc-add.8.gz
# using Deroffing man parser
complete -c nl-qdisc-add -s h -l help --description 'Print help text to console and exit.'
complete -c nl-qdisc-add -s v -l version --description 'Print versioning information to console and exit.'
complete -c nl-qdisc-add -s q -l quiet --description 'Do not print informal notifications about actio… [See Man Page]'
complete -c nl-qdisc-add -s d -l dev --description 'Network device the qdisc is attached to.'
complete -c nl-qdisc-add -s p -l parent --description 'Identifier of the parent qdisc/class this qdisc is attached to.'
complete -c nl-qdisc-add -s i -l id --description 'Identifier of qdisc.  It can be specified as classid or name.'
complete -c nl-qdisc-add -l update --description 'Update qdisc if it already exists, otherwise at… [See Man Page]'
complete -c nl-qdisc-add -l replace --description 'Replace or update qdisc if it already exists.'
complete -c nl-qdisc-add -l update-only --description 'Update an existing qdisc but do not create it i… [See Man Page]'
complete -c nl-qdisc-add -l replace-only --description 'Update or replace an existing qdisc but do not … [See Man Page]'
complete -c nl-qdisc-add -l interactive --description 'The interactive mode requires confirmation by t… [See Man Page]'
complete -c nl-qdisc-add -l yes --description 'Make the default answer for interactive prompts be \'y\'es.'
complete -c nl-qdisc-add -s k -l kind --description 'Only delete qdiscs of this type. SS nl-qdisc-list Options.'
complete -c nl-qdisc-add -l details --description 'Show detailed information for each qdisc listed.'
complete -c nl-qdisc-add -l stats --description 'Show statistics information for each qdisc listed.'
complete -c nl-qdisc-add -s r -l recursive --description 'List all TC objects recurisvely attached to all… [See Man Page]'

