# nmblookup4
# Autogenerated from man page /usr/share/man/man1/nmblookup4.1.gz
# using Deroffing man parser
complete -c nmblookup4 -s M --description 'Searches for a master browser by looking up the… [See Man Page]'
complete -c nmblookup4 -s R --description 'Set the recursion desired bit in the packet to … [See Man Page]'
complete -c nmblookup4 -s S --description 'Once the name query has returned an IP address … [See Man Page]'
complete -c nmblookup4 -s r --description 'Try and bind to UDP port 137 to send and receive UDP datagrams.'
complete -c nmblookup4 -s A --description 'Interpret name as an IP Address and do a node s… [See Man Page]'
complete -c nmblookup4 -s B --description 'Send the query to the given broadcast address.'
complete -c nmblookup4 -s U --description 'Do a unicast query to the specified address or … [See Man Page]'
complete -c nmblookup4 -s T --description 'This causes any IP addresses found in the looku… [See Man Page]'
complete -c nmblookup4 -s f --description 'Show which flags apply to the name that has been looked up.'

