# nmblookup
# Autogenerated from man page /usr/share/man/man1/nmblookup.1.gz
# using Deroffing man parser
complete -c nmblookup -s M -l master-browser --description 'Searches for a master browser by looking up the… [See Man Page]'
complete -c nmblookup -s R -l recursion --description 'Set the recursion desired bit in the packet to … [See Man Page]'
complete -c nmblookup -s S -l status --description 'Once the name query has returned an IP address … [See Man Page]'
complete -c nmblookup -s r -l root-port --description 'Try and bind to UDP port 137 to send and receive UDP datagrams.'
complete -c nmblookup -s A -l lookup-by-ip --description 'Interpret name as an IP Address and do a node s… [See Man Page]'
complete -c nmblookup -s n -l netbiosname --description 'This option allows you to override the NetBIOS … [See Man Page]'
complete -c nmblookup -s i -l scope --description 'This specifies a NetBIOS scope that nmblookup w… [See Man Page]'
complete -c nmblookup -s W -l workgroup --description 'Set the SMB domain of the username.'
complete -c nmblookup -s O -l socket-options --description 'TCP socket options to set on the client socket.'
complete -c nmblookup -s '?' -l help --description 'Print a summary of command line options.'
complete -c nmblookup -l usage --description 'Display brief usage message.'
complete -c nmblookup -s B -l broadcast --description 'Send the query to the given broadcast address.'
complete -c nmblookup -s U -l unicast --description 'Do a unicast query to the specified address or … [See Man Page]'
complete -c nmblookup -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c nmblookup -s V -l version --description 'Prints the program version number.'
complete -c nmblookup -s s -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c nmblookup -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c nmblookup -l option --description 'Set the smb.'
complete -c nmblookup -s T -l translate --description 'This causes any IP addresses found in the looku… [See Man Page]'
complete -c nmblookup -s f -l flags --description 'Show which flags apply to the name that has been looked up.'

