# notmuch-insert
# Autogenerated from man page /usr/share/man/man1/notmuch-insert.1.gz
# using Deroffing man parser
complete -c notmuch-insert -l folder --description '.'
complete -c notmuch-insert -l create-folder --description '.'

