# notmuch-search
# Autogenerated from man page /usr/share/man/man1/notmuch-search.1.gz
# using Deroffing man parser
complete -c notmuch-search -l format --description '.'
complete -c notmuch-search -l format-version --description '.'
complete -c notmuch-search -l output --description 'summary.'
complete -c notmuch-search -l duplicate --description 'tags.'
complete -c notmuch-search -l sort --description '.'
complete -c notmuch-search -l offset --description '.'
complete -c notmuch-search -l limit --description '.'
complete -c notmuch-search -l exclude --description '.'

