# notmuch-count
# Autogenerated from man page /usr/share/man/man1/notmuch-count.1.gz
# using Deroffing man parser
complete -c notmuch-count -l output --description 'messages.'
complete -c notmuch-count -l exclude --description '.'
complete -c notmuch-count -l batch --description '.'
complete -c notmuch-count -l input --description '.'

