# notmuch
# Autogenerated from man page /usr/share/man/man1/notmuch.1.gz
# using Deroffing man parser
complete -c notmuch -l help --description 'Print a synopsis of available commands and exit. RE  . RS 4.'
complete -c notmuch -l version --description 'Print the installed version of notmuch, and exit. RE  . RS 4.'
complete -c notmuch -l config --description '.'

