# notmuch-restore
# Autogenerated from man page /usr/share/man/man1/notmuch-restore.1.gz
# using Deroffing man parser
complete -c notmuch-restore -l accumulate --description '.'
complete -c notmuch-restore -l format --description '.'

