# notmuch-show
# Autogenerated from man page /usr/share/man/man1/notmuch-show.1.gz
# using Deroffing man parser
complete -c notmuch-show -l entire-thread --description '.'
complete -c notmuch-show -l format --description 'and.'
complete -c notmuch-show -l format-version --description '.'
complete -c notmuch-show -l part --description '.'
complete -c notmuch-show -l verify --description '.'
complete -c notmuch-show -l decrypt --description '.'
complete -c notmuch-show -l exclude --description '.'
complete -c notmuch-show -l body --description '.'
complete -c notmuch-show -l include-html --description '.'

