# notmuch-setup
# Autogenerated from man page /usr/share/man/man1/notmuch-setup.1.gz
# using Deroffing man parser
complete -c notmuch-setup -l help --description 'Print a synopsis of available commands and exit. RE  . RS 4.'
complete -c notmuch-setup -l version --description 'Print the installed version of notmuch, and exit. RE  . RS 4.'
complete -c notmuch-setup -l config --description '.'

