# ntdbdump
# Autogenerated from man page /usr/share/man/man8/ntdbdump.8.gz
# using Deroffing man parser
complete -c ntdbdump -s h --description 'Get help information.'
complete -c ntdbdump -s k --description 'The -k option restricts dumping to a single key, if found.'

