# ntdbbackup
# Autogenerated from man page /usr/share/man/man8/ntdbbackup.8.gz
# using Deroffing man parser
complete -c ntdbbackup -s h --description 'Get help information.'
complete -c ntdbbackup -s s --description 'The -s option allows the administrator to speci… [See Man Page]'
complete -c ntdbbackup -s v --description 'The -v will check the database for damages (cor… [See Man Page]'

