# ntlm_auth
# Autogenerated from man page /usr/share/man/man1/ntlm_auth.1.gz
# using Deroffing man parser
complete -c ntlm_auth -l username --description 'Specify username of user to authenticate.'
complete -c ntlm_auth -l domain --description 'Specify domain of user to authenticate.'
complete -c ntlm_auth -l workstation --description 'Specify the workstation the user authenticated from.'
complete -c ntlm_auth -l challenge --description 'NTLM challenge (in HEXADECIMAL).'
complete -c ntlm_auth -l lm-response --description 'LM Response to the challenge (in HEXADECIMAL).'
complete -c ntlm_auth -l nt-response --description 'NT or NTLMv2 Response to the challenge (in HEXADECIMAL).'
complete -c ntlm_auth -l password --description 'User\\*(Aqs plaintext password .'
complete -c ntlm_auth -l request-lm-key --description 'Retrieve LM session key.'
complete -c ntlm_auth -l request-nt-key --description 'Request NT key.'
complete -c ntlm_auth -l diagnostics --description 'Perform Diagnostics on the authentication chain.'
complete -c ntlm_auth -l require-membership-of --description 'Require that a user be a member of specified gr… [See Man Page]'
complete -c ntlm_auth -l pam-winbind-conf --description 'Define the path to the pam_winbind. conf file.'
complete -c ntlm_auth -l target-hostname --description 'Define the target hostname.'
complete -c ntlm_auth -l target-service --description 'Define the target service.'
complete -c ntlm_auth -l use-cached-creds --description 'Whether to use credentials cached by winbindd.'
complete -c ntlm_auth -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c ntlm_auth -s V -l version --description 'Prints the program version number.'
complete -c ntlm_auth -s '?' -l help --description 'Print a summary of command line options.'
complete -c ntlm_auth -l usage --description 'Display brief usage message.'
complete -c ntlm_auth -l helper-protocol --description '.'

