# numastat
# Autogenerated from man page /usr/share/man/man8/numastat.8.gz
# using Type1
complete -c numastat -s c --description 'Minimize table display width by dynamically shr… [See Man Page]'
complete -c numastat -s m --description 'Show the meminfo-like system-wide memory usage information.'
complete -c numastat -s n --description 'Show the original numastat statistics info.'
complete -c numastat -s p --description 'Show per-node memory allocation information for… [See Man Page]'
complete -c numastat -o 's[<node>]' --description 'Sort the table data in descending order before … [See Man Page]'
complete -c numastat -s v --description 'Make some reports more verbose.'
complete -c numastat -s V --description 'Display numastat version information and exit.'

