# odbcinst
# Autogenerated from man page /usr/share/man/man1/odbcinst.1.gz
# using Deroffing man parser
complete -c odbcinst -s i --description 'Install (add section to config file) new OBJECT.'
complete -c odbcinst -s u --description 'Uninstall (remove section from config file) existing OBJECT.'
complete -c odbcinst -s q --description 'Query the config files and print the options fo… [See Man Page]'
complete -c odbcinst -s j --description 'Prints current configuration of unixODBC, listi… [See Man Page]'
complete -c odbcinst -s c --description 'Calls SQLCreateDataSource.'
complete -c odbcinst -s m --description 'Calls SQLManageDataSources.'
complete -c odbcinst -l version --description 'Prints program version and exits. SS OBJECTS.'
complete -c odbcinst -s d --description 'The ACTION affect drivers (and thus the odbcinst.'
complete -c odbcinst -s s --description 'The ACTION affect data sources (and thus the us… [See Man Page]'
complete -c odbcinst -s f --description 'The FILE is template file, describing the confi… [See Man Page]'
complete -c odbcinst -s r --description 'Same as the -f OPTION, only take the standard i… [See Man Page]'
complete -c odbcinst -s n --description 'Specifies the NAME of the OBJECT.'
complete -c odbcinst -s v --description 'Turn off verbose mode.'
complete -c odbcinst -s l --description 'The specified data source is system-wide.'
complete -c odbcinst -s h --description 'The specified data source is user-specific.'

