# packetforge-ng
# Autogenerated from man page /usr/share/man/man1/packetforge-ng.1.gz
# using Deroffing man parser
complete -c packetforge-ng -s H -l help --description 'Shows the help screen.'
complete -c packetforge-ng -s p --description 'Set frame control word (hex).'
complete -c packetforge-ng -s a --description 'Set Access Point MAC addres.'
complete -c packetforge-ng -s c --description 'Set Destination MAC address.'
complete -c packetforge-ng -s h --description 'Set Source MAC address.'
complete -c packetforge-ng -s j --description 'set FromDS bit.'
complete -c packetforge-ng -s o --description 'clear ToDS bit.'
complete -c packetforge-ng -s e --description 'disable WEP encryption.'
complete -c packetforge-ng -s k --description 'Set source IP (and port).'
complete -c packetforge-ng -s l --description 'Set destination IP (and port).'
complete -c packetforge-ng -s w --description 'Write packet to this pcap file.'
complete -c packetforge-ng -s r --description 'Read packet from this pcap file.'
complete -c packetforge-ng -s y --description 'Read PRGA from this file.'
complete -c packetforge-ng -s t --description 'Set Time To Live in IP-Header.'
complete -c packetforge-ng -s s --description 'Set size of the generated null packet.'
complete -c packetforge-ng -s 0 -l arp --description 'Forge an ARP packet.'
complete -c packetforge-ng -s 1 -l udp --description 'Forge an UDP packet.'
complete -c packetforge-ng -s 2 -l icmp --description 'Forge an ICMP packet.'
complete -c packetforge-ng -s 3 -l null --description 'Forge a llc null packet.'
complete -c packetforge-ng -s 9 -l custom --description 'Build a custom packet, requires -r to read an u… [See Man Page]'

