# packer
# Autogenerated from man page /usr/share/man/man8/packer.8.gz
# using Deroffing man parser
complete -c packer -l ignore --description 'Ignore packages.  Separate package names with a comma.'
complete -c packer -l noconfirm --description 'Perform commands without confirmation from the user.'
complete -c packer -l noedit --description 'Perform commands without asking if the user wan… [See Man Page]'
complete -c packer -l quickcheck --description 'Check for updates and exit.'
complete -c packer -l auronly --description 'Only perform commands for the AUR.'
complete -c packer -l devel --description 'Update development packages.  (cvs, git. ).'
complete -c packer -l skipinteg --description 'Skip the integrity check by ignoring AUR package MD5 sums.'
complete -c packer -l preview --description 'Always offer to edit the pkgbuild before sourcing it.'
complete -c packer -o Ss --description '.'
complete -c packer -s S --description '.'
complete -c packer -o Syu --description '.'
complete -c packer -o Si --description '.'
complete -c packer -s G --description '.'
complete -c packer -s h --description '.'

