# pango-querymodules
# Autogenerated from man page /usr/share/man/man1/pango-querymodules.1.gz
# using Deroffing man parser
complete -c pango-querymodules -s '?' -l help --description 'Prints a short help text and exits.'
complete -c pango-querymodules -l version --description 'Prints version information.'
complete -c pango-querymodules -l system --description 'Do not load user-specific configuration.'
complete -c pango-querymodules -l update-cache --description 'Update the Pango module cache file directly, in… [See Man Page]'

