# patch
# Autogenerated from man page /usr/share/man/man1/patch.1p.gz
# using Deroffing man parser
complete -c patch -s C --description 'options are specified).'
complete -c patch -s U --description 'options are specified).'
complete -c patch -l - --description '.'
complete -c patch -s w --description 'option in early proposals was changed to.'
complete -c patch -s L --description '.'

