# pathchk
# Autogenerated from man page /usr/share/man/man1/pathchk.1p.gz
# using Deroffing man parser
complete -c pathchk -s C --description 'noclobber ) option added to the shell, replaces… [See Man Page]'

