# pdfdetach
# Autogenerated from man page /usr/share/man/man1/pdfdetach.1.gz
# using Deroffing man parser
complete -c pdfdetach -o list --description 'List all of the embedded files in the PDF file.'
complete -c pdfdetach -o save --description 'Save the specified embedded file.'
complete -c pdfdetach -o saveall --description 'Save all of the embedded files.'
complete -c pdfdetach -s o --description 'Set the file name used when saving an embedded … [See Man Page]'
complete -c pdfdetach -o enc --description 'Sets the encoding to use for text output (embedded file names).'
complete -c pdfdetach -o opw --description 'Specify the owner password for the PDF file.'
complete -c pdfdetach -o upw --description 'Specify the user password for the PDF file.'
complete -c pdfdetach -s v --description 'Print copyright and version information.'
complete -c pdfdetach -s h --description 'Print usage information.  ( -help and.'
complete -c pdfdetach -l help --description 'are equivalent.'

