# pdfmom
# Autogenerated from man page /usr/share/man/man1/pdfmom.1.gz
# using Deroffing man parser
complete -c pdfmom -o Tpdf --description 'option (which is the default), pdfmom processes… [See Man Page]'
complete -c pdfmom -o Tps --description 'is given, processing is passed over to pdfroff … [See Man Page]'
complete -c pdfmom -o mpdfmark -o mom -l no-toc --description 'options are implied and should not be given on … [See Man Page]'
complete -c pdfmom -s m --description 'options when.'

