# pidl
# Autogenerated from man page /usr/share/man/man1/pidl.1p.gz
# using Type1
complete -c pidl -l help --description 'Show list of available options.'
complete -c pidl -l version --description 'Show pidl version.'
complete -c pidl -l outputdir --description 'Write output files to the specified directory.'
complete -c pidl -l includedir --description 'Add \\s-1DIR\\s0 to the search path used by the preprocessor.'
complete -c pidl -l parse-idl-tree --description 'Read internal tree structure from input files r… [See Man Page]'
complete -c pidl -l dump-idl --description 'Generate a new \\s-1IDL\\s0 file.'
complete -c pidl -l header --description 'Generate a C header file for the specified interface.'
complete -c pidl -l ndr-parser --description 'Generate a C file and C header containing \\s-1NDR\\s0 parsers.'
complete -c pidl -l tdr-parser --description 'Generate a C file and C header containing \\s-1TDR\\s0 parsers.'
complete -c pidl -l typelib --description 'Write type information to the specified file.'
complete -c pidl -l server --description 'Generate boilerplate for the \\s-1RPC\\s0 server … [See Man Page]'
complete -c pidl -l template --description 'Generate stubs for a \\s-1RPC\\s0 server that imp… [See Man Page]'
complete -c pidl -l ws-parser --description 'Generate an Wireshark dissector (in C) and header file.'
complete -c pidl -l diff --description 'Parse an \\s-1IDL\\s0 file,  generate a new \\s-1I… [See Man Page]'
complete -c pidl -l dump-idl-tree --description 'Tell pidl to dump the internal tree representat… [See Man Page]'
complete -c pidl -l dump-ndr-tree --description 'Tell pidl to dump the internal \\s-1NDR\\s0 infor… [See Man Page]'
complete -c pidl -l samba3-ndr-client --description 'Generate client calls for Samba3, to be placed in rpc_client/.'

