# pidof
# Autogenerated from man page /usr/share/man/man1/pidof.1.gz
# using Deroffing man parser
complete -c pidof -s s --description 'Single shot - this instructs the program to onl… [See Man Page]'
complete -c pidof -s c --description 'Only return process ids that are running with t… [See Man Page]'
complete -c pidof -s x --description 'Scripts too - this causes the program to also r… [See Man Page]'
complete -c pidof -s o --description 'Tells pidof to omit processes with that process id.'

