# pkgdelta
# Autogenerated from man page /usr/share/man/man8/pkgdelta.8.gz
# using Deroffing man parser
complete -c pkgdelta -l max-delta-size --description 'Only create delta files if the delta is smaller… [See Man Page]'
complete -c pkgdelta -l min-pkg-size --description 'Minimal size of the package file in bytes to be… [See Man Page]'
complete -c pkgdelta -s q -l quiet --description 'Be quiet.  Do not output anything but warnings and errors.'

