# pkttyagent
# Autogenerated from man page /usr/share/man/man1/pkttyagent.1.gz
# using Deroffing man parser
complete -c pkttyagent -l process --description 'or.'
complete -c pkttyagent -l 'system-bus-name.' --description '.'
complete -c pkttyagent -l notify-fd --description 'to pass the number of a file descriptor that ha… [See Man Page]'
complete -c pkttyagent -l fallback --description 'is used, the textual authentication agent will … [See Man Page]'

