# powerpill
# Autogenerated from man page /usr/share/man/man1/powerpill.json.1.gz
# using Deroffing man parser
complete -c powerpill -l conf-path --description '.'
complete -c powerpill -l no-motd --description 'Sometimes Rsync will attempt to redownload a fi… [See Man Page]'
complete -c powerpill -l verbose --description 'AUTHORS Xyne.'

