# ppl_lpsol
# Autogenerated from man page /usr/share/man/man1/ppl_lpsol.1.gz
# using Deroffing man parser
complete -c ppl_lpsol -s c -l 'check[' --description 'optima are checked with a tolerance of THRESHOL… [See Man Page]'
complete -c ppl_lpsol -s i -l incremental --description 'solves the problem incrementally.'
complete -c ppl_lpsol -s m -l min --description 'minimizes the objective function.'
complete -c ppl_lpsol -s M -l max --description 'maximizes the objective function (default).'
complete -c ppl_lpsol -s n -l no-optimization --description 'checks for satisfiability only.'
complete -c ppl_lpsol -s r -l no-mip --description 'consider integer variables as real variables.'
complete -c ppl_lpsol -o CSECS -l max-cpu --description 'limits CPU usage to SECS seconds.'
complete -c ppl_lpsol -o RMB -l max-memory --description 'limits memory usage to MB megabytes.'
complete -c ppl_lpsol -s h -l help --description 'prints this help text to stdout.'
complete -c ppl_lpsol -o oPATH -l output --description 'appends output to PATH.'
complete -c ppl_lpsol -s e -l enumerate --description 'use the (expensive!) enumeration method.'
complete -c ppl_lpsol -o pM -l pricing --description 'use pricing method M for simplex (assumes -s); … [See Man Page]'
complete -c ppl_lpsol -s s -l simplex --description 'use the simplex method.'
complete -c ppl_lpsol -s t -l timings --description 'prints timings to stderr.'
complete -c ppl_lpsol -s v -l verbosity --description 'sets verbosity level (from 0 to 4, default 3): … [See Man Page]'
complete -c ppl_lpsol -l '>' --description '2 --> state + optimal value 3 --> state + optim… [See Man Page]'
complete -c ppl_lpsol -s V -l version --description 'prints version information to stdout AVAILABILI… [See Man Page]'

