# ppl_lcdd
# Autogenerated from man page /usr/share/man/man1/ppl_lcdd.1.gz
# using Deroffing man parser
complete -c ppl_lcdd -o CSECS -l max-cpu --description 'limits CPU usage to SECS seconds.'
complete -c ppl_lcdd -o RMB -l max-memory --description 'limits memory usage to MB megabytes.'
complete -c ppl_lcdd -s h -l help --description 'prints this help text to stdout.'
complete -c ppl_lcdd -o oPATH -l output --description 'appends output to PATH.'
complete -c ppl_lcdd -s t -l timings --description 'prints timings to stderr.'
complete -c ppl_lcdd -s v -l verbose --description 'produces lots of output.'
complete -c ppl_lcdd -s V -l version --description 'prints version information to stdout.'
complete -c ppl_lcdd -o cPATH -l check --description 'checks if the result is equal to what is in PAT… [See Man Page]'

