# ppl_pips
# Autogenerated from man page /usr/share/man/man1/ppl_pips.1.gz
# using Deroffing man parser
complete -c ppl_pips -o RMB -l max-memory --description 'limits memory usage to MB megabytes.'
complete -c ppl_pips -s h -l help --description 'prints this help text to stdout.'
complete -c ppl_pips -o oPATH -l output --description 'appends output to PATH.'
complete -c ppl_pips -s P -l polylib --description 'reads problem in PolyLib format (default).'
complete -c ppl_pips -s p -l piplib --description 'reads problem in PipLib format.'
complete -c ppl_pips -s t -l timings --description 'prints timings to stderr.'
complete -c ppl_pips -s v -l verbose --description 'produces lots of output.'
complete -c ppl_pips -s i -l iterations --description 'executes the resolution N times (default=1).'
complete -c ppl_pips -s V -l version --description 'prints version information to stdout.'
complete -c ppl_pips -o cPATH -l check --description 'checks if the result is equal to what is in PATH .'
complete -c ppl_pips -s f -l cut-first --description 'uses the first non-integer row (default).'
complete -c ppl_pips -s d -l cut-deepest --description 'tries to generate the deepest cut.'
complete -c ppl_pips -s a -l cut-all --description 'always generates all possible cuts .'
complete -c ppl_pips -s F -l row-first --description 'uses the first row with negative parameter (default).'
complete -c ppl_pips -s M -l row-max --description 'chooses row generating the lexico-maximal pivot… [See Man Page]'

