# pr
# Autogenerated from man page /usr/share/man/man1/pr.1p.gz
# using Deroffing man parser
complete -c pr -s s --description 'option does not allow the option letter to be s… [See Man Page]'
complete -c pr -s e --description '.'
complete -c pr -s i --description 'and.'
complete -c pr -s n --description 'require that both arguments, if present, not be… [See Man Page]'
complete -c pr -o column --description 'Produce multi-column output that is arranged in… [See Man Page]'
complete -c pr -o 'e[char][gap]' --description '.'
complete -c pr -o 'i[char][gap]' --description 'In output, replace <space> characters with <tab… [See Man Page]'
complete -c pr -o 'n[char][width]' --description '.'
complete -c pr -s p --description 'Pause before beginning each page if the standar… [See Man Page]'
complete -c pr -o 's[char]' --description 'Separate text columns by the single character c… [See Man Page]'
complete -c pr -s 2 --description 'a problem when a full page with headers and tra… [See Man Page]'

