# printf
# Autogenerated from man page /usr/share/man/man1/printf.1p.gz
# using Deroffing man parser
complete -c printf -o 9999999999@-2147483648@printf: -o 9999999999 --description 'ABC@0@printf: "ABC" expected numeric value The … [See Man Page]'
complete -c printf -s 3 --description 'Numeric value of constant -3 51 6 Numeric value… [See Man Page]'

