# pspell-config
# Autogenerated from man page /usr/share/man/man1/pspell-config.1.gz
# using Deroffing man parser
complete -c pspell-config -l version --description 'outputs version information about the installed pspell.'
complete -c pspell-config -l datadir --description 'displays the data directory.'
complete -c pspell-config -l pkgdatadir --description 'displays the aspell package directory AUTHOR Th… [See Man Page]'

