# pth-config
# Autogenerated from man page /usr/share/man/man1/pth-config.1.gz
# using Type1
complete -c pth-config -l help --description 'Prints the short usage information.'
complete -c pth-config -l version --description 'Prints the version number and date of the insta… [See Man Page]'
complete -c pth-config -l all --description 'Forces the output of all flags, that is, includ… [See Man Page]'
complete -c pth-config -l prefix --description 'Prints the installation prefix of architecture … [See Man Page]'
complete -c pth-config -l exec-prefix --description 'Prints the installation prefix of architecture dependent files.'
complete -c pth-config -l bindir --description 'Prints the installation directory of binaries.'
complete -c pth-config -l libdir --description 'Prints the installation directory of libraries.'
complete -c pth-config -l includedir --description 'Prints the installation directory of include headers.'
complete -c pth-config -l mandir --description 'Prints the installation directory of manual pages.'
complete -c pth-config -l datadir --description 'Prints the installation directory of shared data.'
complete -c pth-config -l acdir --description 'Prints the installation directory of autoconf data.'
complete -c pth-config -l cflags --description 'Prints the C compiler flags which are needed to… [See Man Page]'
complete -c pth-config -l ldflags --description 'Prints the linker flags (\\f(CW\\*(C`-L\\*(C\') whi… [See Man Page]'

