# pump
# Autogenerated from man page /usr/share/man/man1/pump.1.gz
# using Type1
complete -c pump -l help --description 'Displays summary instructions.'
complete -c pump -l startup --description 'Starts an include server, and outputs the envir… [See Man Page]'

