# pvck
# Autogenerated from man page /usr/share/man/man8/pvck.8.gz
# using Deroffing man parser
complete -c pvck -l labelsector --description 'By default, 4 sectors of PhysicalVolume are sca… [See Man Page]'

