# pvcreate
# Autogenerated from man page /usr/share/man/man8/pvcreate.8.gz
# using Deroffing man parser
complete -c pvcreate -s f -l force --description 'Force the creation without any confirmation.'
complete -c pvcreate -s u -l uuid --description 'Specify the uuid for the device.'
complete -c pvcreate -s y -l yes --description 'Answer yes to all questions.'
complete -c pvcreate -l restorefile -l norestorefile --description 'used.'
complete -c pvcreate -s Z -l zero --description 'Whether or not the first 4 sectors (2048 bytes)… [See Man Page]'
complete -c pvcreate -l metadatasize --description 'The approximate amount of space to be set aside… [See Man Page]'
complete -c pvcreate -l dataalignment --description 'Align the start of the data to a multiple of this number.'
complete -c pvcreate -l 'dataalignmentoffset.' --description '.'
complete -c pvcreate -l dataalignmentoffset --description 'Shift the start of the data area by this additi… [See Man Page]'
complete -c pvcreate -l metadataignore --description 'Ignore or un-ignore metadata areas on this physical volume.'
complete -c pvcreate -l labelsector --description 'By default the PV is labelled with an LVM2 iden… [See Man Page]'
complete -c pvcreate -l bootloaderareasize --description 'Create a separate bootloader area of specified … [See Man Page]'
complete -c pvcreate -l setphysicalvolumesize --description 'Overrides the automatically-detected size of the PV.'

