# pvdisplay
# Autogenerated from man page /usr/share/man/man8/pvdisplay.8.gz
# using Deroffing man parser
complete -c pvdisplay -s c -l colon --description 'Generate colon separated output for easier pars… [See Man Page]'
complete -c pvdisplay -s s -l short --description 'Only display the size of the given physical volumes.'
complete -c pvdisplay -s m -l maps --description 'Display the mapping of physical extents to logi… [See Man Page]'
complete -c pvdisplay -l 'columns.' --description '.'
complete -c pvdisplay -l columns -s C --description 'Display output in columns, the equivalent of pvs(8).'

