# pvmove
# Autogenerated from man page /usr/share/man/man8/pvmove.8.gz
# using Deroffing man parser
complete -c pvmove -l abort --description 'Abort any moves in progress.'
complete -c pvmove -l noudevsync --description 'Disable udev synchronisation.'
complete -c pvmove -s b -l background --description 'Run the daemon in the background.'
complete -c pvmove -s i -l interval --description 'Report progress as a percentage at regular intervals.'
complete -c pvmove -s n -l name --description 'Move only the extents belonging to LogicalVolum… [See Man Page]'

