# pvremove
# Autogenerated from man page /usr/share/man/man8/pvremove.8.gz
# using Deroffing man parser
complete -c pvremove -o ff -l force -l force --description 'Force the removal of a physical volume belongin… [See Man Page]'
complete -c pvremove -s y -l yes --description 'Answer yes to all questions.'

