# pvresize
# Autogenerated from man page /usr/share/man/man8/pvresize.8.gz
# using Deroffing man parser
complete -c pvresize -l setphysicalvolumesize --description 'Overrides the automatically-detected size of the PV.'

