# pvscan
# Autogenerated from man page /usr/share/man/man8/pvscan.8.gz
# using Deroffing man parser
complete -c pvscan -s e -l exported --description 'Only show physical volumes belonging to exported volume groups.'
complete -c pvscan -s n -l novolumegroup --description 'Only show physical volumes not belonging to any volume group.'
complete -c pvscan -s s -l short --description 'Short listing format.'
complete -c pvscan -s u -l uuid --description 'Show UUIDs (Uniform Unique Identifiers) in addi… [See Man Page]'
complete -c pvscan -s a -l activate --description 'Together with the information already cached in… [See Man Page]'
complete -c pvscan -s b -l background --description 'Run the command in the background.'
complete -c pvscan -l cache -l major -l minor --description 'Scan one or more devices and instruct the lvmet… [See Man Page]'

