# pwck
# Autogenerated from man page /usr/share/man/man8/pwck.8.gz
# using Deroffing man parser
complete -c pwck -s h -l help --description 'Display help message and exit.'
complete -c pwck -s q -l quiet --description 'Report errors only.'
complete -c pwck -s r -l read-only --description 'Execute the pwck command in read-only mode.'
complete -c pwck -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'
complete -c pwck -s s -l sort --description 'Sort entries in /etc/passwd and /etc/shadow by UID.'

