# pwconv
# Autogenerated from man page /usr/share/man/man8/pwconv.8.gz
# using Deroffing man parser
complete -c pwconv -s h -l help --description 'Display help message and exit.'
complete -c pwconv -s R -l root --description 'Apply changes in the CHROOT_DIR directory and u… [See Man Page]'

