# python
# Autogenerated from man page /usr/share/man/man1/python.1.gz
# using Deroffing man parser
complete -c python -s B --description 'Don\'t write . py[co] files on import.'
complete -c python -s b --description 'Issue warnings about str(bytes_instance), str(b… [See Man Page]'
complete -c python -s c --description 'Specify the command to execute (see next section).'
complete -c python -s d --description 'Turn on parser debugging output (for wizards on… [See Man Page]'
complete -c python -s E --description 'Ignore environment variables like PYTHONPATH an… [See Man Page]'
complete -c python -s h -s '?' -l help --description 'Prints the usage for the interpreter executable and exits.'
complete -c python -s i --description 'When a script is passed as first argument or th… [See Man Page]'
complete -c python -s m --description 'Searches  sys.'
complete -c python -s O --description 'Turn on basic optimizations.'
complete -c python -o OO --description 'Discard docstrings in addition to the -O optimizations.'
complete -c python -s q --description 'Do not print the version and copyright messages.'
complete -c python -s s --description 'Don\'t add user site directory to sys. path.'
complete -c python -s S --description 'Disable the import of the module site and the s… [See Man Page]'
complete -c python -s u --description 'Force the binary I/O layers of stdout and stder… [See Man Page]'
complete -c python -s v --description 'Print a message each time a module is initializ… [See Man Page]'
complete -c python -s V -l version --description 'Prints the Python version number of the executable and exits.'
complete -c python -s W --description 'Warning control.'
complete -c python -s X --description 'Set implementation specific option.'
complete -c python -s x --description 'Skip the first line of the source.'

