# qalter
# Autogenerated from man page /usr/share/man/man1/qalter.1p.gz
# using Deroffing man parser
complete -c qalter -s a --description 'Redefine the time at which the batch job become… [See Man Page]'
complete -c qalter -s A --description '.'
complete -c qalter -s c --description 'Redefine whether the batch job should be checkp… [See Man Page]'
complete -c qalter -s e --description '.'
complete -c qalter -s h --description 'Redefine the types of holds, if any, on the batch job.'
complete -c qalter -s j --description 'Redefine which streams of the batch job are to be merged.'
complete -c qalter -s k --description 'Redefine which output of the batch job to retai… [See Man Page]'
complete -c qalter -s l --description '.'
complete -c qalter -s m --description '.'
complete -c qalter -s M --description 'Redefine the list of users to which the batch s… [See Man Page]'
complete -c qalter -s N --description 'Redefine the name of the batch job.  The qalter.'
complete -c qalter -s o --description '.'
complete -c qalter -s p --description 'Redefine the priority of the batch job.'
complete -c qalter -s r --description 'Redefine whether the batch job is rerunnable.'
complete -c qalter -s S --description '.'
complete -c qalter -s u --description 'Redefine the user name under which the batch jo… [See Man Page]'
complete -c qalter -s V --description '.'
complete -c qalter -s v --description 'and.'
complete -c qalter -s q --description 'The.'
complete -c qalter -s P --description 'option allows users to modify the priority of a batch job.'

