# qmove
# Autogenerated from man page /usr/share/man/man1/qmove.1p.gz
# using Deroffing man parser
complete -c qmove -s u --description 'option provides the user with the convenience o… [See Man Page]'

