# qmsg
# Autogenerated from man page /usr/share/man/man1/qmsg.1p.gz
# using Deroffing man parser
complete -c qmsg -s E --description 'Specify that the message is written to the stan… [See Man Page]'
complete -c qmsg -s O --description 'Specify that the message is written to the stan… [See Man Page]'

