# rapper
# Autogenerated from man page /usr/share/man/man1/rapper.1.gz
# using Deroffing man parser
complete -c rapper -s h -l help --description 'Show a summary of the options.'
complete -c rapper -s i -l input --description 'Set the input  FORMAT to one of \'rdfxml\' (RDF/X… [See Man Page]'
complete -c rapper -s I -l input-uri --description 'Set the input/parser base  URI or use value \'-\' for no base.'
complete -c rapper -s o -l output --description 'Set the output  FORMAT to \'ntriples\' (N-Triples… [See Man Page]'
complete -c rapper -s O -l output-uri --description 'Set the output/serializer base  URI or use valu… [See Man Page]'
complete -c rapper -s c -l count --description 'Only count the triples and produce no other output.'
complete -c rapper -s e -l ignore-errors --description 'Ignore errors, do not emit the messages and try… [See Man Page]'
complete -c rapper -s f -l feature --description 'Set a parser or serializer feature  FEATURE to … [See Man Page]'
complete -c rapper -s g -l guess --description 'Guess the parser to use from the source-URI rat… [See Man Page]'
complete -c rapper -s q -l quiet --description 'No extra information messages.'
complete -c rapper -s r -l replace-newlines --description 'Replace newlines in multi-line literals with spaces.'
complete -c rapper -l show-graphs --description 'Print graph names (URIs) as they are seen in the input.'
complete -c rapper -l show-namespaces --description 'Print namespaces as they are seen in the input.'
complete -c rapper -s t -l trace --description 'Print URIs retrieved during parsing.'
complete -c rapper -s w -l ignore-warnings --description 'Ignore warnings, do not emit the messages.'
complete -c rapper -s v -l version --description 'Print the raptor version and exit.  EXAMPLES.'

