# rasqal-config
# Autogenerated from man page /usr/share/man/man1/rasqal-config.1.gz
# using Deroffing man parser
complete -c rasqal-config -l version --description 'Print the currently installed version of rasqal… [See Man Page]'
complete -c rasqal-config -l version-decimal --description 'Print the currently installed version of rasqal… [See Man Page]'
complete -c rasqal-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c rasqal-config -l libtool-libs --description 'Print the path to the libtool file for rasqal.'
complete -c rasqal-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c rasqal-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

