# raw
# Autogenerated from man page /usr/share/man/man8/raw.8.gz
# using Deroffing man parser
complete -c raw -s q -l query --description 'Set query mode.'
complete -c raw -s a -l all --description 'With  -q , specify that all bound raw devices s… [See Man Page]'
complete -c raw -s h -l help --description 'Display help text and exit.'
complete -c raw -s V -l version --description 'Display version information and exit.'

