# rdf2bin
# Autogenerated from man page /usr/share/man/man1/rdf2bin.1.gz
# using Deroffing man parser
complete -c rdf2bin -s o --description 'Relocate at origin R relocation-origin .'
complete -c rdf2bin -s p --description 'Pad segments until their size is a multiple of … [See Man Page]'
complete -c rdf2bin -s f --description 'Specify the output format.'

