# rdfproc
# Autogenerated from man page /usr/share/man/man1/rdfproc.1.gz
# using Deroffing man parser
complete -c rdfproc -s h -l help --description 'Show a summary of the options.'
complete -c rdfproc -s c -l contexts --description 'Use a store with Redland contexts.'
complete -c rdfproc -s n -l new --description 'Make a new store, overwriting any existing one.'
complete -c rdfproc -s o -l output --description 'Set the output FORMAT for sequences of triples,… [See Man Page]'
complete -c rdfproc -s p -l password --description 'Read the storage option \'password\' from standard input.'
complete -c rdfproc -s q -l quiet --description 'Suppress informational messages (that go to stderr).'
complete -c rdfproc -s r -l results --description 'Set the query results syntax format.'
complete -c rdfproc -s s -l storage --description 'Set the Redland storage type (default \'hashes\').'
complete -c rdfproc -s t -l storage-options --description 'Set options for the the Redland storage, defaul… [See Man Page]'
complete -c rdfproc -s v -l version --description 'Print the Redland version and exit.'
complete -c rdfproc -s V -l verbose --description 'Show informational messages on stderr.'

