# readonly
# Autogenerated from man page /usr/share/man/man1/readonly.1p.gz
# using Deroffing man parser
complete -c readonly -s p --description 'is specified, readonly writes to the standard o… [See Man Page]'

