# read
# Autogenerated from man page /usr/share/man/man1/read.1p.gz
# using Deroffing man parser
complete -c read -s r --description 'option is specified, <backslash> shall act as a… [See Man Page]'

