# redland-config
# Autogenerated from man page /usr/share/man/man1/redland-config.1.gz
# using Deroffing man parser
complete -c redland-config -l version --description 'Print the currently installed version of redlan… [See Man Page]'
complete -c redland-config -l version-decimal --description 'Print the currently installed version of redlan… [See Man Page]'
complete -c redland-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c redland-config -l libtool-libs --description 'Print the flags that are necessary to link a re… [See Man Page]'
complete -c redland-config -l private-libs --description 'Print the linker flags that are necessary to bu… [See Man Page]'
complete -c redland-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c redland-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

