# regdiff
# Autogenerated from man page /usr/share/man/man1/regdiff.1.gz
# using Deroffing man parser
complete -c regdiff -l help --description 'Show list of available options.'
complete -c regdiff -l backend --description 'Name of backend to load.'
complete -c regdiff -l credentials --description 'Credentials to use, if any.'

