# regpatch
# Autogenerated from man page /usr/share/man/man1/regpatch.1.gz
# using Deroffing man parser
complete -c regpatch -l help --description 'Show list of available options.'
complete -c regpatch -l backend --description 'Name of backend to load.'
complete -c regpatch -l credentials --description 'Credentials to use, if any.'

