# regshell
# Autogenerated from man page /usr/share/man/man1/regshell.1.gz
# using Deroffing man parser
complete -c regshell -l help --description 'Show list of available options.'
complete -c regshell -l backend --description 'Name of backend to load.'
complete -c regshell -l credentials --description 'Credentials to use, if any.'

