# reiserfsck
# Autogenerated from man page /usr/share/man/man8/reiserfsck.8.gz
# using Deroffing man parser
complete -c reiserfsck -l rebuild-sb --description 'This option recovers the superblock on a Reiserfs partition.'
complete -c reiserfsck -l check --description 'This default action checks filesystem consisten… [See Man Page]'
complete -c reiserfsck -l fix-fixable --description 'This option recovers certain kinds of corruptio… [See Man Page]'
complete -c reiserfsck -l rebuild-tree --description 'This option rebuilds the entire filesystem tree… [See Man Page]'
complete -c reiserfsck -l clean-attributes --description 'This option cleans reserved fields of Stat-Data items.'
complete -c reiserfsck -l journal -s j --description 'This option supplies the device name of the cur… [See Man Page]'
complete -c reiserfsck -l interactive -s i --description '\\" This makes reiserfsck to stop after each pass completed. \\".'
complete -c reiserfsck -l adjust-size -s z --description 'This option causes reiserfsck to correct file s… [See Man Page]'
complete -c reiserfsck -l badblocks -s B --description 'This option sets the badblock list to be the li… [See Man Page]'
complete -c reiserfsck -l logfile -s l --description 'This option causes reiserfsck to report any cor… [See Man Page]'
complete -c reiserfsck -l nolog -s n --description 'This option prevents reiserfsck from reporting … [See Man Page]'
complete -c reiserfsck -l quiet -s q --description 'This option prevents reiserfsck from reporting … [See Man Page]'
complete -c reiserfsck -l yes -s y --description 'This option inhibits reiserfsck from asking you… [See Man Page]'
complete -c reiserfsck -s a -s p --description 'These options are usually passed by fsck -A dur… [See Man Page]'
complete -c reiserfsck -l force -s f --description 'Force checking even if the file system seems clean.'
complete -c reiserfsck -s V --description 'This option prints the reiserfsprogs version and then exit.'
complete -c reiserfsck -s r --description 'backwards compatibility.'
complete -c reiserfsck -l no-journal-available --description 'This option allows reiserfsck to proceed when t… [See Man Page]'
complete -c reiserfsck -l scan-whole-partition -s S --description 'This option causes --rebuild-tree to scan the w… [See Man Page]'

