# resolvconf
# Autogenerated from man page /usr/share/man/man8/resolvconf.8.gz
# using Darwin man parser
complete -c resolvconf -s I --description 'Initialise the state directory /run/resolvconf.'
complete -c resolvconf -s f --description 'Ignore non existant interfaces.'
complete -c resolvconf -s i --description 'List the interfaces, optionally matching patter… [See Man Page]'
complete -c resolvconf -s l --description 'List the resolv. conf files we have.'
complete -c resolvconf -s m --description 'Set the metric of the interface when adding it, default of 0.'
complete -c resolvconf -s p --description 'Marks the interface resolv. conf as private.'
complete -c resolvconf -s u --description 'Force resolvconf to update all it\'s subscribers.'
complete -c resolvconf -s v --description 'Echo variables DOMAINS, SEARCH and NAMESERVERS … [See Man Page]'

