# rmdir
# Autogenerated from man page /usr/share/man/man1/rmdir.1p.gz
# using Deroffing man parser
complete -c rmdir -s s --description 'option that suppressed the informational message output by the.'

