# rmid
# Autogenerated from man page /usr/share/man/man1/rmid.1.gz
# using Type1
complete -c rmid -o 'C<someCommandLineOption>' --description 'Specifies an option that is passed as a command… [See Man Page]'
complete -c rmid -o 'J<someCommandLineOption>' --description 'Specifies an option that is passed to the \\f2ja… [See Man Page]'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'Specifies the policy that \\f2rmid employs to ch… [See Man Page]'
complete -c rmid -o log --description 'Specifies the name of the directory the activat… [See Man Page]'
complete -c rmid -o port --description 'Specifies the port \\f2rmid\'s registry uses.'

