# roqet
# Autogenerated from man page /usr/share/man/man1/roqet.1.gz
# using Deroffing man parser
complete -c roqet -s e -l exec --description 'Execute the query string in the argument QUERY … [See Man Page]'
complete -c roqet -s i -l input --description 'Set the input query LANGUAGE to one of the supp… [See Man Page]'
complete -c roqet -s h -l help --description '.'
complete -c roqet -s p -l protocol --description 'Call the SPARQL HTTP protocol SERVICE-URI to ex… [See Man Page]'
complete -c roqet -s r -l results --description 'Set the query results output FORMAT For variabl… [See Man Page]'
complete -c roqet -s R -l results-input-format --description 'Set the query results input.'
complete -c roqet -s t -l results-input --description 'Read query results from FILE OTHER OPTIONS.'
complete -c roqet -s c -l count --description 'Only count the triples and produce no other output.'
complete -c roqet -s d -l dump-query --description 'Print the parsed query out in a given FORMAT on… [See Man Page]'
complete -c roqet -s D -l data --description 'Add RDF data source URI (not a named graph).'
complete -c roqet -s E -l ignore-errors --description 'Do not print error messages and do not exit wit… [See Man Page]'
complete -c roqet -s f -l feature --description 'Set query feature NAME to the VALUE or integer 1 if omitted.'
complete -c roqet -s F -l format --description 'Set the data source format name for subsequent … [See Man Page]'
complete -c roqet -s G -l named --description 'Add RDF data source URI (named graph).'
complete -c roqet -s n -l dryrun --description 'Prepare the query but do not execute it.'
complete -c roqet -s q -l quiet --description 'No extra information messages.'
complete -c roqet -s s -l source --description 'Add RDF data source URI (named graph) URI by ad… [See Man Page]'
complete -c roqet -s v -l version --description 'Print the rasqal library version and exit.'
complete -c roqet -s W -l warnings --description 'Set the warning  LEVEL in the range 0 (do not w… [See Man Page]'

