# runuser
# Autogenerated from man page /usr/share/man/man1/runuser.1.gz
# using Deroffing man parser
complete -c runuser -s c -l command --description 'Pass  command to the shell with the  -c option.'
complete -c runuser -l session-command --description 'Same as  -c but do not create a new session (discouraged).'
complete -c runuser -s f -l fast --description 'Pass  -f to the shell which may or may not be u… [See Man Page]'
complete -c runuser -s g -l group --description 'specify the primary group, this option is allow… [See Man Page]'
complete -c runuser -s G -l supp-group --description 'specify a supplemental group, this option is al… [See Man Page]'
complete -c runuser -s l -l login --description 'Starts the shell as login shell with an environ… [See Man Page]'
complete -c runuser -s m -s p -l preserve-environment --description 'Preserves the whole environment, ie does not se… [See Man Page]'
complete -c runuser -s s -l shell --description 'Runs the specified shell instead of the default.'
complete -c runuser -l help --description 'Display help text and exit.'
complete -c runuser -l version --description 'Display version information and exit.'

