# sact
# Autogenerated from man page /usr/share/man/man1/sact.1p.gz
# using Deroffing man parser
complete -c sact -s e --description 'has been executed previously without a subseque… [See Man Page]'

