# sccs
# Autogenerated from man page /usr/share/man/man1/sccs.1p.gz
# using Deroffing man parser
complete -c sccs -s d --description 'A pathname of a directory to be used as a root … [See Man Page]'
complete -c sccs -s p --description '.'
complete -c sccs -s r --description 'Invoke command with the real user ID of the pro… [See Man Page]'
complete -c sccs -s b --description 'option is given, branches shall be ignored in t… [See Man Page]'
complete -c sccs -s m --description '.'
complete -c sccs -s s --description 'and.'
complete -c sccs -s y --description 'options shall be passed to delta , and any.'
complete -c sccs -s c --description '.'
complete -c sccs -s e --description '.'
complete -c sccs -s i --description '.'
complete -c sccs -s k --description '.'
complete -c sccs -s l --description '.'
complete -c sccs -s x --description 'options shall be passed to get .'
complete -c sccs -s t --description 'options shall be passed to get ; any.'
complete -c sccs -s f --description '.'
complete -c sccs -s h --description 'and.'
complete -c sccs -s C --description 'option shall be passed to diff as.'
complete -c sccs -s u --description 'user option is given, then only files being edi… [See Man Page]'
complete -c sccs -s U --description 'option shall be equivalent to.'

