# scmp_sys_resolver
# Autogenerated from man page /usr/share/man/man1/scmp_sys_resolver.1.gz
# using Deroffing man parser
complete -c scmp_sys_resolver -s a --description 'The architecture to use for resolving the system call.'
complete -c scmp_sys_resolver -s t --description 'If neccessary, translate the system call name t… [See Man Page]'
complete -c scmp_sys_resolver -s h --description 'A simple one-line usage display.'

