# scriptreplay
# Autogenerated from man page /usr/share/man/man1/scriptreplay.1.gz
# using Deroffing man parser
complete -c scriptreplay -s t -l timing --description 'File containing script timing output.'
complete -c scriptreplay -s s -l typescript --description 'File containing the script terminal output.'
complete -c scriptreplay -s d -l divisor --description 'Speed up the replay displaying this  number of times.'
complete -c scriptreplay -s V -l version --description 'Display version information and exit.'
complete -c scriptreplay -s h -l help --description 'Display help text and exit.  EXAMPLE.'

