# secret-tool
# Autogenerated from man page /usr/share/man/man1/secret-tool.1.gz
# using Deroffing man parser
complete -c secret-tool -l label --description 'argument.'
complete -c secret-tool -l all --description '.'
complete -c secret-tool -l unlock --description '.'

