# set
# Autogenerated from man page /usr/share/man/man1/set.1p.gz
# using Deroffing man parser
complete -c set -s a --description 'When this option is on, the export attribute sh… [See Man Page]'
complete -c set -s b --description 'This option shall be supported if the implement… [See Man Page]'
complete -c set -s C --description '(Uppercase C.'
complete -c set -s e --description 'When this option is on, when any command fails … [See Man Page]'
complete -c set -s f --description 'The shell shall disable pathname expansion.'
complete -c set -s h --description 'Locate and remember utilities invoked by functi… [See Man Page]'
complete -c set -s m --description 'This option shall be supported if the implement… [See Man Page]'
complete -c set -s n --description 'The shell shall read commands but does not exec… [See Man Page]'
complete -c set -s o --description 'Write the current settings of the options to st… [See Man Page]'
complete -c set -s u --description 'verbose 10 Equivalent to.'
complete -c set -s v --description 'vi 10 Allow shell command line editing using th… [See Man Page]'
complete -c set -s x --description '.'
complete -c set -s k --description 'The.'
complete -c set -s t --description 'The.'
complete -c set -o able --description 'option syntax.'

