# setconf
# Autogenerated from man page /usr/share/man/man1/setconf.1.gz
# using Deroffing man parser
complete -c setconf -s v --description 'displays the current version number.'
complete -c setconf -s h -l help --description 'displays brief usage information.'
complete -c setconf -s t -l test --description 'performs internal self testing.'
complete -c setconf -s a -l add --description 'adds an option, if not already present.'

