# setsid
# Autogenerated from man page /usr/share/man/man1/setsid.1.gz
# using Deroffing man parser
complete -c setsid -s c -l ctty --description 'Set the controlling terminal to the current one.'
complete -c setsid -s w -l wait --description 'Wait the execution of the program to end, and r… [See Man Page]'

