# sg_luns
# Autogenerated from man page /usr/share/man/man8/sg_luns.8.gz
# using Deroffing man parser
complete -c sg_luns -s d -l decode --description 'decode LUNs into their component parts, as desc… [See Man Page]'
complete -c sg_luns -s h -l help --description 'output the usage message then exit.'
complete -c sg_luns -s H -l hex --description '[device mode] when given once this utility will… [See Man Page]'
complete -c sg_luns -s l -l linux --description 'this option is only available in Linux.'
complete -c sg_luns -s m -l maxlen --description 'where LEN is the (maximum) response length in bytes.'
complete -c sg_luns -s q -l quiet --description 'output only the ASCII hex rendering of each rep… [See Man Page]'
complete -c sg_luns -s r -l raw --description 'output the SCSI response (i. e.'
complete -c sg_luns -s s -l select --description 'this option sets the SELECT REPORT field (SR) i… [See Man Page]'
complete -c sg_luns -s t -l test --description 'ALUN is assumed to be a hexadecimal number in A… [See Man Page]'
complete -c sg_luns -s v -l verbose --description 'increase the level of verbosity, (i. e.  debug output).'
complete -c sg_luns -s V -l version --description 'print the version string and then exit.'

