# sg_xcopy
# Autogenerated from man page /usr/share/man/man8/sg_xcopy.8.gz
# using Deroffing man parser
complete -c sg_xcopy -s h -l help --description 'outputs usage message and exits.'
complete -c sg_xcopy -l on_dst --description 'send the XCOPY command to the output file/device.'
complete -c sg_xcopy -l on_src --description 'send the XCOPY command to the input file/device.'
complete -c sg_xcopy -s v -l verbose --description 'equivalent to verbose=1.'
complete -c sg_xcopy -s V -l version --description 'outputs version number information and exits.'

