# sigfind
# Autogenerated from man page /usr/share/man/man1/sigfind.1.gz
# using Deroffing man parser
complete -c sigfind -s b --description 'Specify the block size in which to search.'
complete -c sigfind -s o --description 'Specify the offset in a block in which the sign… [See Man Page]'
complete -c sigfind -s t --description 'Specify a template name that defines the signat… [See Man Page]'
complete -c sigfind -s l --description 'The signature is stored in little-endian orderi… [See Man Page]'
complete -c sigfind -s V --description 'Display version [hex_signature] The binary sign… [See Man Page]'

