# slirpvde
# Autogenerated from man page /usr/share/man/man1/slirpvde.1.gz
# using Deroffing man parser
complete -c slirpvde -s s -l sock -l socket -l vdesock -l unix --description 'specify the VDE switch directory (default /var/run/vde. ctl).'
complete -c slirpvde -s p -l pidfile --description 'specify the name of the file which contains the… [See Man Page]'
complete -c slirpvde -s g -l group --description 'specify the UNIX group for the VDE communication socket.'
complete -c slirpvde -s m -l mod --description 'specify the octal UNIX permissions for the VDE … [See Man Page]'
complete -c slirpvde -s P -l port --description 'specify the port of the vde switch whern slirpv… [See Man Page]'
complete -c slirpvde -s d -l daemon --description 'detach from terminal and run slirpvde in background.'
complete -c slirpvde -s H -l host --description 'specify the host address (default 10. 0. 2. 2/24).'
complete -c slirpvde -s n -l network --description 'specify the network address (default 10. 0. 2. 0/24).'
complete -c slirpvde -s N -l dns --description 'Specify the address of the dns server.'
complete -c slirpvde -s D -l dhcp --description 'turn on the DHCP server for the network autocon… [See Man Page]'
complete -c slirpvde -s L --description 'specifyes a TCP port redirection.'
complete -c slirpvde -s U --description 'specifyes a UDP port redirection.'
complete -c slirpvde -s X --description 'redirect a X window screen of a virtual machine.'
complete -c slirpvde -s x --description 'redirect a port of the virtual router (usually 10. 0. 2.'
complete -c slirpvde -s t -l tftp --description 'slirpvde enables a tftp server sharing (read-on… [See Man Page]'
complete -c slirpvde -s q -l quiet --description 'Quiet;   do   not  write  anything  to  standard  output.'

