# slsh
# Autogenerated from man page /usr/share/man/man1/slsh.1.gz
# using Type1
complete -c slsh -l help --description 'Show a summary of options.'
complete -c slsh -l version --description 'Show slsh version information.'
complete -c slsh -s g --description 'Compile with debugging code, tracebacks, etc.'
complete -c slsh -s n --description 'Don\'t load the personal initialization file.'
complete -c slsh -l init --description 'Use this file instead of ~/. slshrc.'
complete -c slsh -l no-readline --description 'Do not use a readline interface for the interactive mode.'
complete -c slsh -s e --description 'Execute ``string\'\' as S-Lang code.'
complete -c slsh -s i --description 'Force interactive mode.'
complete -c slsh -s q -l quiet --description 'Startup quietly by not printing the version and… [See Man Page]'
complete -c slsh -s t --description 'Normally, slsh will call slsh_main if it is defined.'

