# smbd
# Autogenerated from man page /usr/share/man/man8/smbd.8.gz
# using Deroffing man parser
complete -c smbd -s D -l daemon --description 'If specified, this parameter causes the server … [See Man Page]'
complete -c smbd -s F -l foreground --description 'If specified, this parameter causes the main sm… [See Man Page]'
complete -c smbd -s S -l log-stdout --description 'If specified, this parameter causes smbd to log… [See Man Page]'
complete -c smbd -s i -l interactive --description 'If this parameter is specified it causes the se… [See Man Page]'
complete -c smbd -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c smbd -s V -l version --description 'Prints the program version number.'
complete -c smbd -s s -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c smbd -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c smbd -l option --description 'Set the smb.'
complete -c smbd -s '?' -l help --description 'Print a summary of command line options.'
complete -c smbd -l usage --description 'Display brief usage message.'
complete -c smbd -l no-process-group --description 'Do not create a new process group for smbd.'
complete -c smbd -s b -l build-options --description 'Prints information about how Samba was built.'
complete -c smbd -s p -l 'port<port' --description 'port number(s) is a space or comma-separated li… [See Man Page]'
complete -c smbd -s P -l 'profiling-level<profiling' --description 'profiling level is a number specifying the leve… [See Man Page]'

