# smbta-util
# Autogenerated from man page /usr/share/man/man8/smbta-util.8.gz
# using Deroffing man parser
complete -c smbta-util -s h --description '.'
complete -c smbta-util -s f --description '.'
complete -c smbta-util -s g --description '.'
complete -c smbta-util -s u --description '.'
complete -c smbta-util -s s --description '.'
complete -c smbta-util -s c --description '.'

