# smbtorture
# Autogenerated from man page /usr/share/man/man1/smbtorture.1.gz
# using Deroffing man parser
complete -c smbtorture -s d --description 'Use the specified Samba debug level.'
complete -c smbtorture -s U --description 'Use the specified username/password combination… [See Man Page]'
complete -c smbtorture -s k --description 'Use kerberos when authenticating.'
complete -c smbtorture -s W --description 'Use specified name as our workgroup name.'
complete -c smbtorture -s n --description 'Use specified name as our NetBIOS name.'
complete -c smbtorture -s O --description 'Use specified socket options, equivalent of the smb.'
complete -c smbtorture -s m --description 'Specify the maximum SMB dialect that should be used.'
complete -c smbtorture -s s --description 'Initialize the randomizer using seed as seed.'
complete -c smbtorture -s L --description 'Use oplocks.'
complete -c smbtorture -s X --description 'Enable dangerous tests.'
complete -c smbtorture -s t --description 'Specify the NBENCH time limit in seconds.  Defaults to 600.'
complete -c smbtorture -s p --description 'Specify ports to connect to.'
complete -c smbtorture -s c --description 'Read NBENCH commands from file instead of from CLIENT. TXT.'
complete -c smbtorture -s A --description 'Show not just OK or FAILED but more detailed output.'
complete -c smbtorture -s C --description 'Load a list of UNC names from the specified filename.'
complete -c smbtorture -s N --description 'Specify number of smbtorture processes to launch.'
complete -c smbtorture -s o --description 'Number of times some operations should be tried… [See Man Page]'
complete -c smbtorture -s e --description 'Number of entries to use in certain tests (such… [See Man Page]'
complete -c smbtorture -s f --description 'Number of failures before aborting a test (default: 1).'

