# sorter
# Autogenerated from man page /usr/share/man/man1/sorter.1.gz
# using Deroffing man parser
complete -c sorter -s d --description 'Specify the location of where all files should be written.'
complete -c sorter -s l --description 'List information to STDOUT (no files are ever written).'
complete -c sorter -s f --description 'Specify the file system type of the image(s).'
complete -c sorter -s i --description 'Specify the image type in which the file system is located.'
complete -c sorter -s o --description 'Specify the sector offset from the beginning of… [See Man Page]'
complete -c sorter -s b --description 'Specify the minimum size of file to process.'
complete -c sorter -s c --description 'Specify the location of an additional configuration file.'
complete -c sorter -s C --description 'Specify the location of the ONLY configuration file.'
complete -c sorter -s m --description 'Specify the mounting point of the image being analyzed.'
complete -c sorter -s a --description 'Specify the location a hash database with entri… [See Man Page]'
complete -c sorter -s n --description 'Specify the location of the NIST National Softw… [See Man Page]'
complete -c sorter -s x --description 'Specify the location a hash database with entri… [See Man Page]'
complete -c sorter -s e --description 'Perform extension mismatch checks on (no catego… [See Man Page]'
complete -c sorter -s U --description 'Do no save data about unknown file types.'
complete -c sorter -s h --description 'Create category files in HTML.'
complete -c sorter -o md5 --description 'Calculate the MD5 value for each file and save … [See Man Page]'
complete -c sorter -o sha1 --description 'Calculate the SHA-1 value for each file and sav… [See Man Page]'
complete -c sorter -s s --description 'Save the actual file content to sub-directories… [See Man Page]'
complete -c sorter -s v --description 'Display verbose information.'
complete -c sorter -s V --description 'Display version.'

