# spawn-fcgi
# Autogenerated from man page /usr/share/man/man1/spawn-fcgi.1.gz
# using Deroffing man parser
complete -c spawn-fcgi -s f --description 'Filename of the FastCGI application to spawn.'
complete -c spawn-fcgi -s d --description 'Change the current directory before spawning the application.'
complete -c spawn-fcgi -s a --description 'IPv4/IPv6 address to bind to; only used if -p is given too.'
complete -c spawn-fcgi -s p --description 'TCP port to bind to; you cannot combine this wi… [See Man Page]'
complete -c spawn-fcgi -s s --description 'Path to the Unix domain socket to bind to; you … [See Man Page]'
complete -c spawn-fcgi -s C --description '(PHP only) Number of children to spawn by setti… [See Man Page]'
complete -c spawn-fcgi -s F --description 'Number of children to fork, defaults to 1.'
complete -c spawn-fcgi -s P --description 'Name of the PID file for spawned processes (ign… [See Man Page]'
complete -c spawn-fcgi -s n --description 'No forking should take place (for daemontools).'
complete -c spawn-fcgi -s M --description 'Change file mode of the Unix domain socket; onl… [See Man Page]'
complete -c spawn-fcgi -s '?' -s h --description 'General usage instructions.'
complete -c spawn-fcgi -s v --description 'Shows version information and exits . P .'
complete -c spawn-fcgi -s c --description 'Chroot to specified directory; the Unix domain … [See Man Page]'
complete -c spawn-fcgi -s S --description 'Create Unix domain socket before chroot().'
complete -c spawn-fcgi -s u --description 'User ID to change to.'
complete -c spawn-fcgi -s g --description 'Group ID to change to.'
complete -c spawn-fcgi -s U --description 'Change user of the Unix domain socket, defaults… [See Man Page]'
complete -c spawn-fcgi -s G --description 'Change group of the Unix domain socket, default… [See Man Page]'

