# strings
# Autogenerated from man page /usr/share/man/man1/strings.1p.gz
# using Deroffing man parser
complete -c strings -s a --description 'Scan files in their entirety.  If.'
complete -c strings -s n --description 'Specify the minimum string length, where the nu… [See Man Page]'
complete -c strings -s t --description 'Write each string preceded by its byte offset f… [See Man Page]'
complete -c strings -s o --description 'option historically means different things on d… [See Man Page]'
complete -c strings -s O --description 'to mean ``offset\'\', but was changed to.'

