# su
# Autogenerated from man page /usr/share/man/man1/su.1.gz
# using Deroffing man parser
complete -c su -s c -l command --description 'Pass  command to the shell with the  -c option.'
complete -c su -l session-command --description 'Same as  -c but do not create a new session (discouraged).'
complete -c su -s f -l fast --description 'Pass  -f to the shell, which may or may not be … [See Man Page]'
complete -c su -s g -l group --description 'Specify the primary group.'
complete -c su -s G -l supp-group --description 'Specify a supplemental group.'
complete -c su -s l -l login --description 'Starts the shell as login shell with an environ… [See Man Page]'
complete -c su -s m -s p -l preserve-environment --description 'Preserves the whole environment, i. e.'
complete -c su -s s -l shell --description 'Runs the specified shell instead of the default.'
complete -c su -l help --description 'Display help text and exit.'
complete -c su -l version --description 'Display version information and exit.'

