# sudoreplay
# Autogenerated from man page /usr/share/man/man8/sudoreplay.8.gz
# using Darwin man parser
complete -c sudoreplay -s d --description 'Store session logs in dir instead of the defaul… [See Man Page]'
complete -c sudoreplay -s f --description 'Select which I/O type(s) to display.'
complete -c sudoreplay -s h --description 'Display a short help message to the standard output and exit.'
complete -c sudoreplay -s l --description 'Enable list mode.'
complete -c sudoreplay -s m --description 'Specify an upper bound on how long to wait betw… [See Man Page]'
complete -c sudoreplay -s s --description 'This option causes sudoreplay sudoreplay to adj… [See Man Page]'
complete -c sudoreplay -s V --description 'Print the sudoreplay sudoreplay versions versio… [See Man Page]'

