# sulogin
# Autogenerated from man page /usr/share/man/man8/sulogin.8.gz
# using Deroffing man parser
complete -c sulogin -s e -l force --description 'If the default method of obtaining the root pas… [See Man Page]'
complete -c sulogin -s p -l login-shell --description 'Specifying this option causes sulogin to start … [See Man Page]'
complete -c sulogin -s t -l timeout --description 'Specify the maximum amount of time to wait for user input.'
complete -c sulogin -s h -l help --description 'Display help text and exit.'
complete -c sulogin -s V -l version --description 'Display version information and exit.'

