# surf
# Autogenerated from man page /usr/share/man/man1/surf.1.gz
# using Deroffing man parser
complete -c surf -s c --description 'Specify the cookiefile to use.'
complete -c surf -s e --description 'Reparents to window specified by xid.'
complete -c surf -s i --description 'Disable Images.'
complete -c surf -s n --description 'Disable the Web Inspector (Developer Tools).'
complete -c surf -s p --description 'Disable Plugins.'
complete -c surf -s r --description 'Specify the user scriptfile.'
complete -c surf -s s --description 'Disable Javascript.'
complete -c surf -s t --description 'Specify the user stylefile.'
complete -c surf -s u --description 'Specify the useragent which surf should use.'
complete -c surf -s v --description 'Prints version information to standard output, then exits.'
complete -c surf -s x --description 'Prints xid to standard output.'

