# swapon
# Autogenerated from man page /usr/share/man/man8/swapon.8.gz
# using Deroffing man parser
complete -c swapon -s a -l all --description 'All devices marked as ``swap\'\' in  /etc/fstab a… [See Man Page]'
complete -c swapon -s d -l discard --description 'Enable swap discards, if the swap backing devic… [See Man Page]'
complete -c swapon -s e -l ifexists --description 'Silently skip devices that do not exist.'
complete -c swapon -s f -l fixpgsz --description 'Reinitialize (exec /sbin/mkswap) the swap space… [See Man Page]'
complete -c swapon -s h -l help --description 'Display help text and exit.'
complete -c swapon -s L --description 'Use the partition that has the specified R label .'
complete -c swapon -s p -l priority --description 'Specify the priority of the swap device.'
complete -c swapon -s s -l summary --description 'Display swap usage summary by device.'
complete -c swapon -l show --description 'Display definable device table similar to  --summary output.'
complete -c swapon -l noheadings --description 'Do not print headings when displaying  --show output.'
complete -c swapon -l raw --description 'Display  --show output without aligning table columns.'
complete -c swapon -l bytes --description 'Display swap size in bytes in  --show output in… [See Man Page]'
complete -c swapon -s v -l verbose --description 'Be verbose.'
complete -c swapon -s U --description 'to indicate a device by label or uuid.'
complete -c swapon -s V -l version --description 'Display version information and exit.'

