# sync
# Autogenerated from man page /usr/share/man/man1/sync.1.gz
# using Deroffing man parser
complete -c sync -l help --description 'display this help and exit.'
complete -c sync -l version --description 'output version information and exit.'

