# systemd-cgtop
# Autogenerated from man page /usr/share/man/man1/systemd-cgtop.1.gz
# using Deroffing man parser
complete -c systemd-cgtop -s p --description 'Order by control group path name.'
complete -c systemd-cgtop -s t --description 'Order by number of tasks in control group (i. e.'
complete -c systemd-cgtop -s c --description 'Order by CPU load.'
complete -c systemd-cgtop -s m --description 'Order by memory usage.'
complete -c systemd-cgtop -s i --description 'Order by disk I/O load.'
complete -c systemd-cgtop -s b -l batch --description 'Run in "batch" mode: do not accept input and ru… [See Man Page]'
complete -c systemd-cgtop -s n -l iterations --description 'Perform only this many iterations.'
complete -c systemd-cgtop -s d -l delay --description 'Specify refresh delay in seconds (or if one of … [See Man Page]'
complete -c systemd-cgtop -l depth --description 'Maximum control group tree traversal depth.'
complete -c systemd-cgtop -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-cgtop -l version --description 'Print a short version string and exit.'

