# systemd-analyze
# Autogenerated from man page /usr/share/man/man1/systemd-analyze.1.gz
# using Deroffing man parser
complete -c systemd-analyze -l user --description 'Shows performance data of user sessions instead… [See Man Page]'
complete -c systemd-analyze -l system --description 'Shows performance data of the system manager.'
complete -c systemd-analyze -l order -l require --description 'When used in conjunction with the dot command (… [See Man Page]'
complete -c systemd-analyze -l from-pattern -l to-pattern --description 'When used in conjunction with the dot command (… [See Man Page]'
complete -c systemd-analyze -l fuzz --description 'When used in conjunction with the critical-chai… [See Man Page]'
complete -c systemd-analyze -s H -l host --description 'Execute the operation remotely.'
complete -c systemd-analyze -s M -l machine --description 'Execute operation on a local container.'
complete -c systemd-analyze -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-analyze -l version --description 'Print a short version string and exit.'
complete -c systemd-analyze -l no-pager --description 'Do not pipe output into a pager.'
complete -c systemd-analyze -l log-level --description 'described in systemd(1)).'
complete -c systemd-analyze -l 'no-pager.' --description '$SYSTEMD_LESS.'

