# systemd
# Autogenerated from man page /usr/share/man/man1/systemd.1.gz
# using Deroffing man parser
complete -c systemd -l test --description 'Determine startup sequence, dump it and exit.'
complete -c systemd -l dump-configuration-items --description 'Dump understood unit configuration items.'
complete -c systemd -l unit --description 'Set default unit to activate on startup.'
complete -c systemd -l system -l user --description 'For --system, tell systemd to run a system inst… [See Man Page]'
complete -c systemd -l dump-core --description 'Dump core on crash.'
complete -c systemd -l crash-shell --description 'Run shell on crash.'
complete -c systemd -l confirm-spawn --description 'Ask for confirmation when spawning processes.'
complete -c systemd -l show-status --description 'Show terse service status information while booting.'
complete -c systemd -l log-target --description 'Set log target.'
complete -c systemd -l log-level --description 'Set log level.'
complete -c systemd -l log-color --description 'Highlight important log messages.  Argument is a boolean value.'
complete -c systemd -l log-location --description 'Include code location in log messages.'
complete -c systemd -l default-standard-output -l default-standard-error --description 'Sets the default output or error output for all… [See Man Page]'
complete -c systemd -s h -l help --description 'Print a short help text and exit.'
complete -c systemd -l version --description 'Print a short version string and exit.'
complete -c systemd -l 'test.' --description '.'
complete -c systemd -o '1.' --description 'systemd. confirm_spawn=.'
complete -c systemd -s b --description '.'

