# systemd-ask-password
# Autogenerated from man page /usr/share/man/man1/systemd-ask-password.1.gz
# using Deroffing man parser
complete -c systemd-ask-password -l icon --description 'Specify an icon name alongside the password que… [See Man Page]'
complete -c systemd-ask-password -l timeout --description 'Specify the query timeout in seconds.  Defaults to 90s.'
complete -c systemd-ask-password -l no-tty --description 'Never ask for password on current TTY even if one is available.'
complete -c systemd-ask-password -l accept-cached --description 'If passed, accept cached passwords, i. e.'
complete -c systemd-ask-password -l multiple --description 'When used in conjunction with --accept-cached a… [See Man Page]'
complete -c systemd-ask-password -s h -l help --description 'Print a short help text and exit.'

