# systemd-bootchart
# Autogenerated from man page /usr/share/man/man1/systemd-bootchart.1.gz
# using Deroffing man parser
complete -c systemd-bootchart -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-bootchart -s n -l sample --description 'Specify the number of samples, N, to record.'
complete -c systemd-bootchart -s f -l freq --description 'Specify the sample log frequency, a positive real f, in Hz.'
complete -c systemd-bootchart -s r -l rel --description 'Use relative times instead of absolute times.'
complete -c systemd-bootchart -s F -l no-filter --description 'Disable filtering of tasks that did not contrib… [See Man Page]'
complete -c systemd-bootchart -s C -l cmdline --description 'Display the full command line with arguments of… [See Man Page]'
complete -c systemd-bootchart -s o -l output --description 'Specify the output directory for the graphs.'
complete -c systemd-bootchart -s i -l init --description 'Use this init binary.  Defaults to /sbin/init.'
complete -c systemd-bootchart -s p -l pss --description 'Enable logging and graphing of processes\\*(Aq P… [See Man Page]'
complete -c systemd-bootchart -s e -l entropy --description 'Enable logging and graphing of the kernel rando… [See Man Page]'
complete -c systemd-bootchart -s x -l scale-x --description 'Horizontal scaling factor for all variable graph components.'
complete -c systemd-bootchart -s y -l scale-y --description 'Vertical scaling factor for all variable graph components.'
complete -c systemd-bootchart -l 'freq.' --description '.'

