# systemd-activate
# Autogenerated from man page /usr/share/man/man8/systemd-activate.8.gz
# using Deroffing man parser
complete -c systemd-activate -s l -l listen --description 'Listen on this address.  Takes a string like "2000" or "127. 0.'
complete -c systemd-activate -s a -l accept --description 'Launch a separate instance of daemon per connec… [See Man Page]'
complete -c systemd-activate -s E -l setenv --description 'Add this variable to the environment of the launched process.'
complete -c systemd-activate -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-activate -l version --description 'Print a short version string and exit.'

