# systemd-readahead-replay
# Autogenerated from man page /usr/share/man/man8/systemd-readahead-replay.service.8.gz
# using Deroffing man parser
complete -c systemd-readahead-replay -l max-files --description 'Maximum number of files to read ahead.'
complete -c systemd-readahead-replay -l file-size-max --description 'Maximum size of files in bytes to read ahead.'
complete -c systemd-readahead-replay -l timeout --description 'Maximum time in microseconds to spend collecting data.'
complete -c systemd-readahead-replay -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-readahead-replay -l version --description 'Print a short version string and exit.'

