# systemd-machine-id-setup
# Autogenerated from man page /usr/share/man/man1/systemd-machine-id-setup.1.gz
# using Deroffing man parser
complete -c systemd-machine-id-setup -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-machine-id-setup -l version --description 'Print a short version string and exit.'
complete -c systemd-machine-id-setup -o uuid --description 'option, this UUID is used to initialize the mac… [See Man Page]'

