# systemd-notify
# Autogenerated from man page /usr/share/man/man1/systemd-notify.1.gz
# using Deroffing man parser
complete -c systemd-notify -l ready --description 'Inform the init system about service start-up completion.'
complete -c systemd-notify -l pid --description 'Inform the init system about the main PID of the daemon.'
complete -c systemd-notify -l status --description 'Send a free-form status string for the daemon t… [See Man Page]'
complete -c systemd-notify -l booted --description 'Returns 0 if the system was booted up with syst… [See Man Page]'
complete -c systemd-notify -l readahead --description 'Controls disk read-ahead operations.'
complete -c systemd-notify -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-notify -l version --description 'Print a short version string and exit.'

