# systemd-run
# Autogenerated from man page /usr/share/man/man1/systemd-run.1.gz
# using Deroffing man parser
complete -c systemd-run -l scope --description 'Create a transient .'
complete -c systemd-run -l unit --description 'Use this unit name instead of an automatically generated one.'
complete -c systemd-run -l property -s p --description 'Sets a unit property for the scope or service u… [See Man Page]'
complete -c systemd-run -l description --description 'Provide description for the service or scope unit.'
complete -c systemd-run -l slice --description 'Make the new . service or .'
complete -c systemd-run -l remain-after-exit --description 'After the service or scope process has terminat… [See Man Page]'
complete -c systemd-run -l send-sighup --description 'When terminating the scope or service unit, sen… [See Man Page]'
complete -c systemd-run -l service-type --description 'Sets the service type.  Also see Type= in systemd. service(5).'
complete -c systemd-run -l uid -l gid --description 'Runs the service process under the UNIX user and group.'
complete -c systemd-run -l nice --description 'Runs the service process with the specified nice level.'
complete -c systemd-run -l setenv --description 'Runs the service process with the specified env… [See Man Page]'
complete -c systemd-run -l user --description 'Talk to the service manager of the calling user… [See Man Page]'
complete -c systemd-run -l system --description 'Talk to the service manager of the system.'
complete -c systemd-run -s H -l host --description 'Execute the operation remotely.'
complete -c systemd-run -s M -l machine --description 'Execute operation on a local container.'
complete -c systemd-run -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-run -l version --description 'Print a short version string and exit.'
complete -c systemd-run -l 'scope.' --description 'simple.'

