# systemd-detect-virt
# Autogenerated from man page /usr/share/man/man1/systemd-detect-virt.1.gz
# using Deroffing man parser
complete -c systemd-detect-virt -s c -l container --description 'Only detects container virtualization (i. e.'
complete -c systemd-detect-virt -s v -l vm --description 'Only detects VM virtualization (i. e.'
complete -c systemd-detect-virt -s q -l quiet --description 'Suppress output of the virtualization technology identifier.'
complete -c systemd-detect-virt -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-detect-virt -l version --description 'Print a short version string and exit.'

