# systemd-tmpfiles
# Autogenerated from man page /usr/share/man/man8/systemd-tmpfiles.8.gz
# using Deroffing man parser
complete -c systemd-tmpfiles -l create --description 'If this option is passed, all files and directo… [See Man Page]'
complete -c systemd-tmpfiles -l clean --description 'If this option is passed, all files and directo… [See Man Page]'
complete -c systemd-tmpfiles -l remove --description 'If this option is passed, all files and directo… [See Man Page]'
complete -c systemd-tmpfiles -l boot --description 'Also execute lines with an exclamation mark.'
complete -c systemd-tmpfiles -l prefix --description 'Only apply rules that apply to paths with the specified prefix.'
complete -c systemd-tmpfiles -l exclude-prefix --description 'Ignore rules that apply to paths with the specified prefix.'
complete -c systemd-tmpfiles -s h -l help --description 'Print a short help text and exit.'
complete -c systemd-tmpfiles -l version --description 'Print a short version string and exit.'

