# tabs
# Autogenerated from man page /usr/share/man/man1/tabs.1p.gz
# using Deroffing man parser
complete -c tabs -o '8.' --description '.'
complete -c tabs -s 0 --description 'is used, the tab stops shall be cleared and no new ones set.'
complete -c tabs -s t --description 'tablist option was added for consistency with e… [See Man Page]'

