# tdbbackup
# Autogenerated from man page /usr/share/man/man8/tdbbackup.8.gz
# using Deroffing man parser
complete -c tdbbackup -s h --description 'Get help information.'
complete -c tdbbackup -s s --description 'The -s option allows the adminisistrator to spe… [See Man Page]'
complete -c tdbbackup -s v --description 'The -v will check the database for damages (cur… [See Man Page]'

