# text2pcap
# Autogenerated from man page /usr/share/man/man1/text2pcap.1.gz
# using Type1
complete -c text2pcap -s a --description 'Enables \\s-1ASCII\\s0 text dump identification.'
complete -c text2pcap -s d --description 'Displays debugging information during the process.'
complete -c text2pcap -s D --description 'The text before the packet starts either with a… [See Man Page]'
complete -c text2pcap -s e --description 'Include a dummy Ethernet header before each packet.'
complete -c text2pcap -s h --description 'Displays a help message.'
complete -c text2pcap -s i --description 'Include dummy \\s-1IP\\s0 headers before each packet.'
complete -c text2pcap -s l --description 'Specify the link-layer header type of this packet.'
complete -c text2pcap -s m --description 'Set the maximum packet length, default is 65535.'
complete -c text2pcap -s n --description 'Write PCAP-NG file instead of a \\s-1PCAP. \\s0.'
complete -c text2pcap -s o --description 'Specify the radix for the offsets (hex, octal or decimal).'
complete -c text2pcap -s q --description 'Be completely quiet during the process.'
complete -c text2pcap -s s --description 'Include dummy \\s-1SCTP\\s0 headers before each packet.'
complete -c text2pcap -s S --description 'Include dummy \\s-1SCTP\\s0 headers before each packet.'
complete -c text2pcap -s t --description 'Treats the text before the packet as a date/tim… [See Man Page]'
complete -c text2pcap -s T --description 'Include dummy \\s-1TCP\\s0 headers before each packet.'

