# tr
# Autogenerated from man page /usr/share/man/man1/tr.1p.gz
# using Deroffing man parser
complete -c tr -s n --description 'was added to disable the historical behavior of… [See Man Page]'
complete -c tr -o cd --description '(which would delete all bytes with the top bit … [See Man Page]'

