# tsk_loaddb
# Autogenerated from man page /usr/share/man/man1/tsk_loaddb.1.gz
# using Deroffing man parser
complete -c tsk_loaddb -s a --description 'Adds image to an existing database instead of c… [See Man Page]'
complete -c tsk_loaddb -s d --description 'Path for the database (default is the same dire… [See Man Page]'
complete -c tsk_loaddb -s v --description 'verbose output to stderr.'
complete -c tsk_loaddb -s V --description 'Print version.'
complete -c tsk_loaddb -s k --description 'Don\'t create block data table.'
complete -c tsk_loaddb -s h --description 'Calculate MD5 hash value for each file and store it in table.'
complete -c tsk_loaddb -s i --description 'The format of the image file, such as raw.'
complete -c tsk_loaddb -s b --description 'The size (in bytes) of the device sectors.'

