# tsk_comparedir
# Autogenerated from man page /usr/share/man/man1/tsk_comparedir.1.gz
# using Deroffing man parser
complete -c tsk_comparedir -s o --description 'Sector offset for a partition in the image or d… [See Man Page]'
complete -c tsk_comparedir -s n --description 'Starting inum for a directory in the image to s… [See Man Page]'
complete -c tsk_comparedir -s v --description 'verbose output to stderr.'
complete -c tsk_comparedir -s V --description 'Print version.'
complete -c tsk_comparedir -s f --description 'Specify the file system type.'
complete -c tsk_comparedir -s i --description 'The format of the image file, such as raw.'
complete -c tsk_comparedir -s b --description 'The size (in bytes) of the device sectors.'

