# tsk_recover
# Autogenerated from man page /usr/share/man/man1/tsk_recover.1.gz
# using Deroffing man parser
complete -c tsk_recover -s v --description 'verbose output to stderr.'
complete -c tsk_recover -s V --description 'Print version.'
complete -c tsk_recover -s a --description 'Recover allocated files only.'
complete -c tsk_recover -s e --description 'Recover all files (allocated and unallocated).'
complete -c tsk_recover -s f --description 'Specify the file system type.'
complete -c tsk_recover -s i --description 'The format of the image file, such as raw.'
complete -c tsk_recover -s b --description 'The size (in bytes) of the device sectors.'
complete -c tsk_recover -s o --description 'Sector offset for a volume to recover (recovers… [See Man Page]'
complete -c tsk_recover -s d --description 'Directory inum to recover from (must also speci… [See Man Page]'

