# tsk_gettimes
# Autogenerated from man page /usr/share/man/man1/tsk_gettimes.1.gz
# using Deroffing man parser
complete -c tsk_gettimes -s v --description 'verbose output to stderr.'
complete -c tsk_gettimes -s V --description 'Print version.'
complete -c tsk_gettimes -s f --description 'Specify the file system type.'
complete -c tsk_gettimes -s i --description 'The format of the image file, such as raw.'
complete -c tsk_gettimes -s b --description 'The size (in bytes) of the device sectors.'
complete -c tsk_gettimes -s o --description 'Sector offset for a volume to recover (recovers… [See Man Page]'
complete -c tsk_gettimes -s s --description 'The time skew of the original system in seconds.'
complete -c tsk_gettimes -s z --description 'The ASCII string of the time zone of the original system.'

