# udisks
# Autogenerated from man page /usr/share/man/man8/udisks.8.gz
# using Deroffing man parser
complete -c udisks -s S --description 'option in hdparm(8).  APMLevel.'
complete -c udisks -s B --description 'option in hdparm(8).  AAMLevel.'
complete -c udisks -s M --description 'option in hdparm(8).  WriteCacheEnabled.'
complete -c udisks -s W --description 'option in hdparm(8).  This key was added in 2. 1.'

