# udiskie
# Autogenerated from man page /usr/share/man/man8/udiskie.8.gz
# using Deroffing man parser
complete -c udiskie -s h -l help --description 'Show help message and exit.'
complete -c udiskie -s v -l verbose --description 'Verbose output.'
complete -c udiskie -s 1 -l use-udisks1 --description 'Use UDisks1 as DBus backend (default).'
complete -c udiskie -s 2 -l use-udisks2 --description 'Use UDisks2 as DBus backend (experimental).'
complete -c udiskie -s f -l filters --description 'Alternate filter configuration.'
complete -c udiskie -s P -l password-prompt --description 'Password prompt to use for unlocking.  Default is zenity.'
complete -c udiskie -s r -l recursive --description 'Recursively mount cleartext partitions after un… [See Man Page]'
complete -c udiskie -s s -l suppress --description 'Suppress pop-up notifications.'
complete -c udiskie -s t -l tray --description 'Show tray icon.'
complete -c udiskie -s a -l all --description 'Mount or unmount all external devices.'
complete -c udiskie -s e -l eject --description 'Eject media from the drive.'
complete -c udiskie -s d -l detach --description 'Detach drive by e. g.  powering down its physical port.'

