# udisksctl
# Autogenerated from man page /usr/share/man/man1/udisksctl.1.gz
# using Deroffing man parser
complete -c udisksctl -l 'options.' --description 'suid or dev that would allow the caller to gain… [See Man Page]'
complete -c udisksctl -l force --description 'can be used to request that the device is unmou… [See Man Page]'
complete -c udisksctl -l no-user-interaction --description 'can be used to request that no interaction (suc… [See Man Page]'

