# ul
# Autogenerated from man page /usr/share/man/man1/ul.1.gz
# using Darwin man parser
complete -c ul -s i -l indicated --description 'Underlining is indicated by a separate line con… [See Man Page]'
complete -c ul -s t -s T -l terminal --description 't Fl t Ar terminal Overrides the  terminal type… [See Man Page]'
complete -c ul -s V -l version --description 'Display version information and exit.'

