# ulimit
# Autogenerated from man page /usr/share/man/man1/ulimit.1p.gz
# using Deroffing man parser
complete -c ulimit -s f --description 'Set (or report, if no blocks operand is present… [See Man Page]'

