# umask
# Autogenerated from man page /usr/share/man/man1/umask.1p.gz
# using Deroffing man parser
complete -c umask -s S --description 'Produce symbolic output.'
complete -c umask -s r --description '.'
complete -c umask -s w --description '.'
complete -c umask -s x --description 'or anything beginning with a <hyphen>, must be … [See Man Page]'
complete -c umask -s s --description 'option used in early proposals was changed to.'
complete -c umask -s o --description 'flag to force octal mode output was omitted bec… [See Man Page]'

