# umount
# Autogenerated from man page /usr/share/man/man8/umount.8.gz
# using Deroffing man parser
complete -c umount -s a -l all --description 'All of the file systems described in  /etc/mtab are unmounted.'
complete -c umount -s A -l all-targets --description 'Unmount all mountpoints in the current namespac… [See Man Page]'
complete -c umount -s c -l no-canonicalize --description 'Do not canonicalize paths.'
complete -c umount -s d -l detach-loop --description 'In case the unmounted device was a loop device,… [See Man Page]'
complete -c umount -l fake --description 'Causes everything to be done except for the act… [See Man Page]'
complete -c umount -s f -l force --description 'Force unmount (in case of an unreachable NFS system).'
complete -c umount -s i -l internal-only --description 'Do not call the /sbin/umount.'
complete -c umount -s n -l no-mtab --description 'Unmount without writing in R /etc/mtab .'
complete -c umount -s l -l lazy --description 'Lazy unmount.'
complete -c umount -s O -l test-opts --description 'Indicate that the actions should only be taken … [See Man Page]'
complete -c umount -s R -l recursive --description 'Recursively unmount each directory specified.'
complete -c umount -s r -l read-only --description 'In case unmounting fails, try to remount read-only.'
complete -c umount -s t -l types --description 'Indicate that the actions should only be taken … [See Man Page]'
complete -c umount -s v -l verbose --description 'Verbose mode.'
complete -c umount -s h -l help --description 'Display help text and exit.'
complete -c umount -s V -l version --description 'Display version information and exit.'

