# unalias
# Autogenerated from man page /usr/share/man/man1/unalias.1p.gz
# using Deroffing man parser
complete -c unalias -s a --description 'Remove all alias definitions from the current s… [See Man Page]'

