# unget
# Autogenerated from man page /usr/share/man/man1/unget.1p.gz
# using Deroffing man parser
complete -c unget -s e --description 'done prior to creating the intended new delta.'
complete -c unget -s r --description 'Uniquely identify which delta is no longer intended.'
complete -c unget -s s --description 'Suppress the writing to standard output of the … [See Man Page]'
complete -c unget -s n --description 'Retain the file that was obtained by get , whic… [See Man Page]'

