# unset
# Autogenerated from man page /usr/share/man/man1/unset.1p.gz
# using Deroffing man parser
complete -c unset -s v --description 'is specified, name refers to a variable name an… [See Man Page]'
complete -c unset -s f --description 'is specified, name refers to a function and the… [See Man Page]'

