# unshare
# Autogenerated from man page /usr/share/man/man1/unshare.1.gz
# using Deroffing man parser
complete -c unshare -s h -l help --description 'Display help text and exit.'
complete -c unshare -s i -l ipc --description 'Unshare the IPC namespace.'
complete -c unshare -s m -l mount --description 'Unshare the mount namespace.'
complete -c unshare -s n -l net --description 'Unshare the network namespace.'
complete -c unshare -s p -l pid --description 'Unshare the pid namespace.'
complete -c unshare -s u -l uts --description 'Unshare the UTS namespace.'
complete -c unshare -s U -l user --description 'Unshare the user namespace.'
complete -c unshare -s f -l fork --description 'Fork the specified program as a child process o… [See Man Page]'
complete -c unshare -l mount-proc --description 'Just before running the program, mount the proc… [See Man Page]'

