# usbredirserver
# Autogenerated from man page /usr/share/man/man1/usbredirserver.1.gz
# using Deroffing man parser
complete -c usbredirserver -s p -l port --description 'Set the TCP port to listen on to PORT.'
complete -c usbredirserver -s v -l verbose --description 'Set usbredirserver\'s verbosity level to VERBOSE… [See Man Page]'

