# uuencode
# Autogenerated from man page /usr/share/man/man1/uuencode.1p.gz
# using Deroffing man parser
complete -c uuencode -s m --description 'Encode the output using the MIME Base64 algorit… [See Man Page]'
complete -c uuencode -s b --description '(for Base64), but it was renamed to reflect its… [See Man Page]'
complete -c uuencode -s u --description 'was also present to invoke the default algorith… [See Man Page]'

