# uustat
# Autogenerated from man page /usr/share/man/man1/uustat.1p.gz
# using Deroffing man parser
complete -c uustat -s q --description 'Write the jobs queued for each machine.'
complete -c uustat -s k --description 'Kill the uucp request whose job identification is jobid .'
complete -c uustat -s r --description 'Rejuvenate jobid .'
complete -c uustat -s s --description 'Write the status of all uucp requests for remot… [See Man Page]'
complete -c uustat -s u --description 'Write the status of all uucp requests issued by user .'

