# val
# Autogenerated from man page /usr/share/man/man1/val.1p.gz
# using Deroffing man parser
complete -c val -s m --description 'Specify a name , which is compared with the SCC… [See Man Page]'
complete -c val -s r --description 'Specify a SID (SCCS Identification String), an … [See Man Page]'
complete -c val -s s --description 'Silence the diagnostic message normally written… [See Man Page]'
complete -c val -s y --description 'Specify a type , which shall be compared with t… [See Man Page]'

