# valgrind-listener
# Autogenerated from man page /usr/share/man/man1/valgrind-listener.1.gz
# using Deroffing man parser
complete -c valgrind-listener -s e -l exit-at-zero --description 'When the number of connected processes falls ba… [See Man Page]'
complete -c valgrind-listener -l log-socket --description 'option on the specified port and copies the com… [See Man Page]'

