# vde_over_ns
# Autogenerated from man page /usr/share/man/man1/vde_over_ns.1.gz
# using Deroffing man parser
complete -c vde_over_ns -s s --description 'If specified, the vde_over_ns will connect to t… [See Man Page]'
complete -c vde_over_ns -s D --description 'Detach console and send the process to background.'
complete -c vde_over_ns -s b --description 'The NS server will bind only to the specified i… [See Man Page]'
complete -c vde_over_ns -s c --description 'If specified, client mode is enabled.'

