# vde_switch
# Autogenerated from man page /usr/share/man/man1/vde_switch.1.gz
# using Deroffing man parser
complete -c vde_switch -o hub --description 'turn off the switch engine.  It operates as a hub.'
complete -c vde_switch -o sock --description 'specify the directory when comm socket are created.'
complete -c vde_switch -o mod --description 'specify the octal permissions for the comm sockets.'
complete -c vde_switch -o group --description 'specify the group owner for the comm socket.'
complete -c vde_switch -o tap --description 'connect the specified tuntap interface to this … [See Man Page]'
complete -c vde_switch -o daemon --description 'Run as a daemon.  Use syslog for logging.'
complete -c vde_switch -s f --description 'rc file to set the initial switch configuration.'
complete -c vde_switch -s h --description 'help.  Please use it for a more complete list of options.'

