# vde_l3
# Autogenerated from man page /usr/share/man/man1/vde_l3.1.gz
# using Deroffing man parser
complete -c vde_l3 -s v --description 'Creates a virtual network interfaces on the vde… [See Man Page]'
complete -c vde_l3 -s r --description 'Specify a static route through gateway to reach… [See Man Page]'
complete -c vde_l3 -s G --description 'Specify a default gateway, to be used whenever … [See Man Page]'
complete -c vde_l3 -s M --description 'the unix socket where the parameters (interface… [See Man Page]'

