# vde_plug2tap
# Autogenerated from man page /usr/share/man/man1/vde_plug2tap.1.gz
# using Deroffing man parser
complete -c vde_plug2tap -s p -l port --description 'It is possible to decide which port of the switch to use.'
complete -c vde_plug2tap -s g -l group --description 'group ownership of the communication socket.'
complete -c vde_plug2tap -s m -l mod --description 'octal chmod like permissions for the comm sockets.'
complete -c vde_plug2tap -s s -l sock --description 'specify the UNIX socket to be used by local pro… [See Man Page]'
complete -c vde_plug2tap -s d -l daemon --description 'start vde_plug2tap as a background process.'
complete -c vde_plug2tap -s P -l pidfile --description 'put the process ID of vde_plug2tap in pidfile.'
complete -c vde_plug2tap -s h -l help --description 'show a brief help.'

