# vde_autolink
# Autogenerated from man page /usr/share/man/man1/vde_autolink.1.gz
# using Deroffing man parser
complete -c vde_autolink -s h -l help --description 'Display this help.'
complete -c vde_autolink -s f -l rcfile --description 'Configuration file (overrides /etc/vde_autolink. rc and ~/.'
complete -c vde_autolink -s d -l daemon --description 'Daemonize vde_autolink once run.'
complete -c vde_autolink -s p -l pidfile --description 'Write pid of daemon to PIDFILE.'
complete -c vde_autolink -s M -l mgmt --description 'Path of the management UNIX socket.'
complete -c vde_autolink -l mgmtmode --description 'Management UNIX socket access mode (octal).'
complete -c vde_autolink -s s -l sock --description '[*] Attach to this vde_switch socket.'
complete -c vde_autolink -s S -l switchmgmt --description '[*] Attach to this vde_switch management socket… [See Man Page]'

