# vdecmd
# Autogenerated from man page /usr/share/man/man1/vdecmd.1.gz
# using Deroffing man parser
complete -c vdecmd -s s --description 'management socket path (default is /var/run/unixcmd).'
complete -c vdecmd -s f --description 'configuration path (default is /etc/unixcmd).'
complete -c vdecmd -s v --description 'run parse machine in debug mode.'

