# vdekvm
# Autogenerated from man page /usr/share/man/man1/vdekvm.1.gz
# using Deroffing man parser
complete -c vdekvm -l mod --description 'octalmode,  specify the mode for comm socket. br.'
complete -c vdekvm -o sock --description 'socketpath,  specify the UNIX socket to be used… [See Man Page]'
complete -c vdekvm -s h -o help -l help --description 'print a Usage help.'

