# vdeqemu
# Autogenerated from man page /usr/share/man/man1/vdeqemu.1.gz
# using Deroffing man parser
complete -c vdeqemu -l mod --description 'octalmode,  specify the mode for comm socket. br.'
complete -c vdeqemu -o sock --description 'socketpath,  specify the UNIX socket to be used… [See Man Page]'
complete -c vdeqemu -s h -o help -l help --description 'print a Usage help.'

