# vdeq
# Autogenerated from man page /usr/share/man/man1/vdeq.1.gz
# using Deroffing man parser
complete -c vdeq -l mod --description 'octalmode,  specify the mode for comm socket. br.'
complete -c vdeq -o sock --description 'socketpath,  specify the UNIX socket to be used… [See Man Page]'
complete -c vdeq -s h -o help -l help --description 'print a Usage help.'

