# vercmp
# Autogenerated from man page /usr/share/man/man8/vercmp.8.gz
# using Deroffing man parser
complete -c vercmp -s h -l help --description 'Display syntax for the given operation.'
complete -c vercmp -s 1 --description '$ vercmp 2 1 1 $ vercmp 2. 0-1 1. 7-6 1 $ vercmp 2. 0 2.'

