# vfstest
# Autogenerated from man page /usr/share/man/man1/vfstest.1.gz
# using Deroffing man parser
complete -c vfstest -s c -l command --description 'Execute the specified (semicolon-separated) commands.'
complete -c vfstest -s '?' -l help --description 'Print a summary of command line options.'
complete -c vfstest -s l -l logfile --description 'File name for log/debug files.  The extension \\*(Aq.'
complete -c vfstest -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c vfstest -s V -l version --description 'Prints the program version number.'
complete -c vfstest -s s -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c vfstest -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c vfstest -l option --description 'Set the smb.'

