# vgcfgrestore
# Autogenerated from man page /usr/share/man/man8/vgcfgrestore.8.gz
# using Deroffing man parser
complete -c vgcfgrestore -s l -l list --description 'List files pertaining to VolumeGroupName List m… [See Man Page]'
complete -c vgcfgrestore -s f -l file --description 'Name of LVM metadata backup file Specifies a me… [See Man Page]'
complete -c vgcfgrestore -l force --description 'Necessary to restore metadata with thin pool volumes.'

