# vgchange
# Autogenerated from man page /usr/share/man/man8/vgchange.8.gz
# using Deroffing man parser
complete -c vgchange -s A -l autobackup --description 'Controls automatic backup of metadata after the change.'
complete -c vgchange -s a -l activate --description 'Controls the availability of the logical volume… [See Man Page]'
complete -c vgchange -s K -l ignoreactivationskip --description 'Ignore the flag to skip Logical Volumes during activation.'
complete -c vgchange -s c -l clustered --description 'If clustered locking is enabled, this indicates… [See Man Page]'
complete -c vgchange -l detachprofile --description 'Detach any configuration profiles attached to g… [See Man Page]'
complete -c vgchange -s u -l uuid --description 'Generate new random UUID for specified Volume Groups.'
complete -c vgchange -l monitor --description 'Start or stop monitoring a mirrored or snapshot… [See Man Page]'
complete -c vgchange -l poll --description 'Without polling a logical volume\'s backgrounded… [See Man Page]'
complete -c vgchange -l sysinit --description 'Indicates that vgchange(8) is being invoked fro… [See Man Page]'
complete -c vgchange -l noudevsync --description 'Disable udev synchronisation.'
complete -c vgchange -l ignoremonitoring --description 'Make no attempt to interact with dmeventd unles… [See Man Page]'
complete -c vgchange -s l -l logicalvolume --description 'Changes the maximum logical volume number of an… [See Man Page]'
complete -c vgchange -s p -l maxphysicalvolumes --description 'Changes the maximum number of physical volumes … [See Man Page]'
complete -c vgchange -s s -l physicalextentsize --description 'Changes the physical extent size on physical vo… [See Man Page]'
complete -c vgchange -l refresh --description 'If any logical volume in the volume group is ac… [See Man Page]'
complete -c vgchange -l ignorelockingfailure --description '.'
complete -c vgchange -s x -l resizeable --description 'Enables or disables the extension/reduction of … [See Man Page]'

