# vgcreate
# Autogenerated from man page /usr/share/man/man8/vgcreate.8.gz
# using Deroffing man parser
complete -c vgcreate -s c -l clustered --description 'If clustered locking is enabled, this defaults … [See Man Page]'
complete -c vgcreate -s l -l maxlogicalvolumes --description 'Sets the maximum number of logical volumes allo… [See Man Page]'
complete -c vgcreate -s p -l maxphysicalvolumes --description 'Sets the maximum number of physical volumes tha… [See Man Page]'
complete -c vgcreate -l restorefile -l uuid -l physicalvolumesize --description 'are not available.'
complete -c vgcreate -s s -l physicalextentsize --description 'Sets the physical extent size on physical volum… [See Man Page]'
complete -c vgcreate -s f -l force --description '.'
complete -c vgcreate -s y -l yes --description '.'
complete -c vgcreate -s Z -l zero --description '.'
complete -c vgcreate -l labelsector --description '.'
complete -c vgcreate -l metadatasize --description '.'
complete -c vgcreate -l pvmetadatacopies --description '.'
complete -c vgcreate -l dataalignment --description '.'
complete -c vgcreate -l dataalignmentoffset --description 'Examples Creates a volume group named "test_vg"… [See Man Page]'

