# vgdb
# Autogenerated from man page /usr/share/man/man1/vgdb.1.gz
# using Deroffing man parser
complete -c vgdb -l pid --description 'Specifies the PID of the process to which vgdb must connect to.'
complete -c vgdb -l vgdb-prefix --description 'Must be given to both Valgrind and vgdb if you … [See Man Page]'
complete -c vgdb -l wait --description 'Instructs vgdb to search for available Valgrind… [See Man Page]'
complete -c vgdb -l max-invoke-ms --description 'Gives the number of milliseconds after which vg… [See Man Page]'
complete -c vgdb -l cmd-time-out --description 'Instructs a standalone vgdb to exit if the Valg… [See Man Page]'
complete -c vgdb -l port --description 'Instructs vgdb to use tcp/ip and listen for GDB… [See Man Page]'
complete -c vgdb -s c --description 'To give more than one command to a standalone v… [See Man Page]'
complete -c vgdb -s l --description 'Instructs a standalone vgdb to report the list … [See Man Page]'
complete -c vgdb -s D --description 'Instructs a standalone vgdb to show the state o… [See Man Page]'
complete -c vgdb -s d --description 'Instructs vgdb to produce debugging output.'
complete -c vgdb -o 'c.' --description 'vgdb v. set log_output -c leak_check any.'

