# vgimportclone
# Autogenerated from man page /usr/share/man/man8/vgimportclone.8.gz
# using Deroffing man parser
complete -c vgimportclone -s n -l basevgname --description 'By default the snapshot VG will be renamed to t… [See Man Page]'
complete -c vgimportclone -s i -l import --description 'Import exported Volume Groups.'

