# vgreduce
# Autogenerated from man page /usr/share/man/man8/vgreduce.8.gz
# using Deroffing man parser
complete -c vgreduce -s a -l all --description 'Removes all empty physical volumes if none are … [See Man Page]'
complete -c vgreduce -l removemissing --description 'Removes all missing physical volumes from the v… [See Man Page]'

