# vgremove
# Autogenerated from man page /usr/share/man/man8/vgremove.8.gz
# using Deroffing man parser
complete -c vgremove -s f -l force --description 'Force the removal of any logical volumes on the… [See Man Page]'
complete -c vgremove -l noudevsync --description 'Disable udev synchronisation.'

