# vgs
# Autogenerated from man page /usr/share/man/man8/vgs.8.gz
# using Deroffing man parser
complete -c vgs -l all --description 'List all volume groups.'
complete -c vgs -l aligned --description 'Use with --separator to align the output columns.'
complete -c vgs -l nameprefixes --description 'Add an "LVM2_" prefix plus the field name to the output.'
complete -c vgs -l noheadings --description 'Suppress the headings line that is normally the… [See Man Page]'
complete -c vgs -l nosuffix --description 'Suppress the suffix on output sizes.'
complete -c vgs -s o -l options --description 'Comma-separated ordered list of columns.'
complete -c vgs -s O -l sort --description 'Comma-separated ordered list of columns to sort by.'
complete -c vgs -l rows --description 'Output columns as rows.'
complete -c vgs -l separator --description 'String to use to separate each column.'
complete -c vgs -l unbuffered --description 'Produce output immediately without sorting or a… [See Man Page]'
complete -c vgs -l units --description 'All sizes are output in these units: (h)uman-re… [See Man Page]'
complete -c vgs -l unquoted --description 'When used with --nameprefixes, output values in… [See Man Page]'

