# vgscan
# Autogenerated from man page /usr/share/man/man8/vgscan.8.gz
# using Deroffing man parser
complete -c vgscan -l mknodes --description 'Also checks the LVM special files in /dev that … [See Man Page]'
complete -c vgscan -l cache --description 'Scan devices for LVM physical volumes and volum… [See Man Page]'

