# vi
# Autogenerated from man page /usr/share/man/man1/vi.1p.gz
# using Deroffing man parser
complete -c vi -s c --description 'See the ex command description of the.'
complete -c vi -s r --description 'See the ex command description of the.'
complete -c vi -s R --description 'See the ex command description of the.'
complete -c vi -s t --description 'See the ex command description of the.'
complete -c vi -s w --description 'See the ex command description of the.'
complete -c vi -s 1 --description 'error.   b.'
complete -c vi -o '1)' --description '.'
complete -c vi -o '1.' --description '.'
complete -c vi -o '1).' --description ' 3.  4 Any text copied to a buffer shall be in line mode.'
complete -c vi -o '1)).' --description ' 3.  4 Any text copied to a buffer shall be in line mode.'
complete -c vi -s 2 --description 'follows, and the window edit option shall not be affected.'
complete -c vi -s D --description 'can result in a completely changed screen, without any overlap.'

