# virtlockd
# Autogenerated from man page /usr/share/man/man8/virtlockd.8.gz
# using Type1
complete -c virtlockd -s h -l help --description 'Display command line help usage then exit.'
complete -c virtlockd -s d -l daemon --description 'Run as a daemon and write \\s-1PID\\s0 file.'
complete -c virtlockd -s f -l config --description 'Use this configuration file, overriding the default value.'
complete -c virtlockd -s p -l pid-file --description 'Use this name for the \\s-1PID\\s0 file, overridi… [See Man Page]'
complete -c virtlockd -s v -l verbose --description 'Enable output of verbose messages.'

