# virt-login-shell
# Autogenerated from man page /usr/share/man/man1/virt-login-shell.1.gz
# using Type1
complete -c virt-login-shell -s h -l help --description 'Display command line help usage then exit.'

