# virt-host-validate
# Autogenerated from man page /usr/share/man/man1/virt-host-validate.1.gz
# using Type1
complete -c virt-host-validate -s v -l version --description 'el.'
complete -c virt-host-validate -s h -l help --description 'el.'
complete -c virt-host-validate -s q -l quiet --description 'el.'

