# virt-xml-validate
# Autogenerated from man page /usr/share/man/man1/virt-xml-validate.1.gz
# using Type1
complete -c virt-xml-validate -s h -l help --description 'Display command line help usage then exit.'

