# vmstat
# Autogenerated from man page /usr/share/man/man8/vmstat.8.gz
# using Deroffing man parser
complete -c vmstat -s a -l active --description 'Display active and  inactive memory, given a 2. 5.'
complete -c vmstat -s f -l forks --description 'The  -f switch displays the number of forks since boot.'
complete -c vmstat -s m -l slabs --description 'Displays slabinfo.'
complete -c vmstat -s n -l one-header --description 'Display the header only once rather than periodically.'
complete -c vmstat -s s -l stats --description 'Displays a table of various event counters and … [See Man Page]'
complete -c vmstat -s d -l disk --description 'Report disk statistics (2. 5. 70 or above required).'
complete -c vmstat -s D -l disk-sum --description 'Report some summary statistics about disk activity.'
complete -c vmstat -s p -l partition --description 'Detailed statistics about partition (2. 5.'
complete -c vmstat -s S -l unit --description 'Switches outputs between 1000 . RI ( k ), 1024 .'
complete -c vmstat -s w -l wide --description 'Wide output mode (useful for systems with highe… [See Man Page]'
complete -c vmstat -s V -l version --description 'Display version information and exit.'
complete -c vmstat -s h -l help --description 'Display help and exit.'

