# vncconfig
# Autogenerated from man page /usr/share/man/man1/vncconfig.1.gz
# using Deroffing man parser
complete -c vncconfig -o connect --description 'Tells an Xvnc server to make a "reverse" connec… [See Man Page]'
complete -c vncconfig -o disconnect --description 'This causes Xvnc to disconnect from all viewers… [See Man Page]'
complete -c vncconfig -o list --description 'Lists all the parameters supported by Xvnc.'
complete -c vncconfig -o get --description 'Prints the current value of the given Xvnc parameter.'
complete -c vncconfig -o nowin --description 'wish to clutter the desktop with this window - … [See Man Page]'
complete -c vncconfig -o desc --description 'Prints a short description of the given Xvnc parameter.'
complete -c vncconfig -o set --description '.'
complete -c vncconfig -l param --description '.'
complete -c vncconfig -o display --description 'Specifies the Xvnc server to control.'
complete -c vncconfig -o iconic --description 'When run as a "helper" app, make the window ico… [See Man Page]'

