# vncpasswd
# Autogenerated from man page /usr/share/man/man1/vncpasswd.1.gz
# using Deroffing man parser
complete -c vncpasswd -o rfbauth --description 'use via the -passwd option.'
complete -c vncpasswd -s f --description 'Filter mode.'

