# vncserver
# Autogenerated from man page /usr/share/man/man1/vncserver.1.gz
# using Deroffing man parser
complete -c vncserver -o name --description 'Each VNC desktop has a name which may be displa… [See Man Page]'
complete -c vncserver -o geometry --description 'Specify the size of the VNC desktop to be created.'
complete -c vncserver -o depth --description 'Specify the pixel depth (in bits) of the VNC de… [See Man Page]'
complete -c vncserver -o pixelformat --description 'Specify pixel format for Xvnc to use (BGRnnn or RGBnnn).'
complete -c vncserver -o cc --description 'As an alternative to the default TrueColor visu… [See Man Page]'
complete -c vncserver -o kill --description 'This kills a VNC desktop previously started with vncserver.'
complete -c vncserver -o fp --description 'If the vncserver script detects that the X Font… [See Man Page]'
complete -c vncserver -o fg --description 'Runs Xvnc as a foreground process.'
complete -c vncserver -o autokill --description 'Automatically kill Xvnc whenever the xstartup script exits.'

