# wdctl
# Autogenerated from man page /usr/share/man/man8/wdctl.8.gz
# using Deroffing man parser
complete -c wdctl -s f -l flags --description 'Print selected flags only.'
complete -c wdctl -s F -l noflags --description 'Do not print information about flags.'
complete -c wdctl -s n -l noheadings --description 'Do not print a header line for flags table.'
complete -c wdctl -s I -l noident --description 'Do not print watchdog identity information.'
complete -c wdctl -s T -l notimeouts --description 'Do not print watchdog timeouts.'
complete -c wdctl -s s -l settimeout --description 'Set the watchdog timeout in seconds.'
complete -c wdctl -s o -l output --description 'Define the output columns to use in table of watchdog flags.'
complete -c wdctl -s O -l oneline --description 'Print all wanted information on one line in key… [See Man Page]'
complete -c wdctl -s r -l raw --description 'Use the raw output format.'
complete -c wdctl -s x -l flags-only --description 'Same as -I -T.'
complete -c wdctl -s h -l help --description 'Display help text and exit.'
complete -c wdctl -s V -l version --description 'Display version information and exit.  AUTHORS.'

