# webpmux
# Autogenerated from man page /usr/share/man/man1/webpmux.1.gz
# using Deroffing man parser
complete -c webpmux -o loop --description 'Loop the frames n number of times.'
complete -c webpmux -o bgcolor --description 'Background color of the canvas.'

