# weechat
# Autogenerated from man page /usr/share/man/man1/weechat.1.gz
# using Deroffing man parser
complete -c weechat -s a -l no-connect --description 'Disable auto-connect to servers when WeeChat is starting.'
complete -c weechat -s c -l colors --description 'Display default colors in terminal.'
complete -c weechat -s d -l dir --description 'Set path as home for WeeChat (used for configur… [See Man Page]'
complete -c weechat -s h -l help --description 'Display help.'
complete -c weechat -s l -l license --description 'Display WeeChat license.'
complete -c weechat -s p -l no-plugin --description 'Disable plugins auto-load.'
complete -c weechat -s r -l run-command --description 'Run command(s) after startup (many commands can… [See Man Page]'
complete -c weechat -s s -l no-script --description 'Disable scripts auto-load.'
complete -c weechat -l upgrade --description 'Upgrade WeeChat using session files generated w… [See Man Page]'
complete -c weechat -s v -l version --description 'Display WeeChat version.'

