# wesside-ng
# Autogenerated from man page /usr/share/man/man1/wesside-ng.1.gz
# using Deroffing man parser
complete -c wesside-ng -s h --description 'Shows the help screen.'
complete -c wesside-ng -s i --description 'Wireless interface name.  (Mandatory).'
complete -c wesside-ng -s n --description 'Network IP as in \'who has destination IP (netip… [See Man Page]'
complete -c wesside-ng -s m --description '\'who has destination IP (netip) tell source IP (myip)\'.'
complete -c wesside-ng -s a --description 'Source MAC address (Optional).'
complete -c wesside-ng -s c --description 'Do not crack the key.'
complete -c wesside-ng -s p --description 'Determines the minimum number of bytes of PRGA … [See Man Page]'
complete -c wesside-ng -s v --description 'Wireless access point MAC address (Optional).'
complete -c wesside-ng -s t --description 'For each number of IVs specified, restart the a… [See Man Page]'
complete -c wesside-ng -s f --description 'Allows the highest channel for scanning to be defined.'

