# what
# Autogenerated from man page /usr/share/man/man1/what.1p.gz
# using Deroffing man parser
complete -c what -s s --description 'Quit after finding the first occurrence of the … [See Man Page]'

