# whereis
# Autogenerated from man page /usr/share/man/man1/whereis.1.gz
# using Deroffing man parser
complete -c whereis -s b --description 'Search only for binaries.'
complete -c whereis -s m --description 'Search only for manuals.'
complete -c whereis -s s --description 'Search only for sources.'
complete -c whereis -s u --description 'Only show the command names that have unusual entries.'
complete -c whereis -s B --description 'Limit the places where  whereis searches for bi… [See Man Page]'
complete -c whereis -s M --description 'Limit the places where  whereis searches for ma… [See Man Page]'
complete -c whereis -s S --description 'Limit the places where  whereis searches for so… [See Man Page]'
complete -c whereis -s f --description 'Terminates the directory list and signals the s… [See Man Page]'
complete -c whereis -s l --description 'Output list of effective lookup paths the whereis is using.'

