# winbindd
# Autogenerated from man page /usr/share/man/man8/winbindd.8.gz
# using Deroffing man parser
complete -c winbindd -s D -l daemon --description 'If specified, this parameter causes the server … [See Man Page]'
complete -c winbindd -s F -l foreground --description 'If specified, this parameter causes the main wi… [See Man Page]'
complete -c winbindd -s S -l stdout --description 'If specified, this parameter causes winbindd to… [See Man Page]'
complete -c winbindd -s d -l debuglevel --description 'level is an integer from 0 to 10.'
complete -c winbindd -s V -l version --description 'Prints the program version number.'
complete -c winbindd -s s -l configfile --description 'The file specified contains the configuration d… [See Man Page]'
complete -c winbindd -s l -l log-basename --description 'Base directory name for log/debug files.  The extension ".'
complete -c winbindd -l option --description 'Set the smb.'
complete -c winbindd -s '?' -l help --description 'Print a summary of command line options.'
complete -c winbindd -l usage --description 'Display brief usage message.'
complete -c winbindd -s i -l interactive --description 'Tells winbindd to not become a daemon and detac… [See Man Page]'
complete -c winbindd -s n -l no-caching --description 'Disable some caching.'
complete -c winbindd -l no-process-group --description 'Do not create a new process group for winbindd.'
complete -c winbindd -s U --description 'can be any Domain user that has administrator p… [See Man Page]'
complete -c winbindd -l with-lockdir --description 'option.'

