# wipefs
# Autogenerated from man page /usr/share/man/man8/wipefs.8.gz
# using Deroffing man parser
complete -c wipefs -s a -l all --description 'Erase all available signatures.'
complete -c wipefs -s b -l backup --description 'Create a signature backup to the file $HOME/wip… [See Man Page]'
complete -c wipefs -s f -l force --description 'Force erasure, even if the filesystem is mounted.'
complete -c wipefs -s h -l help --description 'Display help text and exit.'
complete -c wipefs -s n -l no-act --description 'Causes everything to be done except for the write() call.'
complete -c wipefs -s o -l offset --description 'Specify the location (in bytes) of the signatur… [See Man Page]'
complete -c wipefs -s p -l parsable --description 'Print out in parsable instead of printable format.'
complete -c wipefs -s q -l quiet --description 'Suppress output messages after successful signature wipe.'
complete -c wipefs -s t -l types --description 'Limit the set of printed or erased signatures.'
complete -c wipefs -s V -l version --description 'Display version information and exit.  EXAMPLES.'

