# wirefilter
# Autogenerated from man page /usr/share/man/man1/wirefilter.1.gz
# using Deroffing man parser
complete -c wirefilter -s f --description 'use a startup configuration file.'
complete -c wirefilter -s l --description 'percentage of loss as a floating point number.'
complete -c wirefilter -s L --description 'when this is not zero, wirefilter uses the Gilb… [See Man Page]'
complete -c wirefilter -s d --description 'Extra delay (in milliseconds).'
complete -c wirefilter -s D --description 'percentage of dup packet.  It has the same syntax of -l.'
complete -c wirefilter -s b --description 'Channel bandwidth in Bytes/sec.  It has the same syntax of -d.'
complete -c wirefilter -s s --description 'Interface speed in Bytes/sec.  It has the same syntax of -b.'
complete -c wirefilter -s c --description 'Channel buffer size (in Bytes): maximum size of… [See Man Page]'
complete -c wirefilter -s n --description 'Number of bits damaged/one megabyte.'
complete -c wirefilter -s m --description 'Packets longer than mtu_size are discarded.'
complete -c wirefilter -s N --description 'nofifo.  with -N packets can be reordered.'
complete -c wirefilter -s M --description 'the unix socket where the parameters (loss perc… [See Man Page]'
complete -c wirefilter -s v --description 'If this option is used, the two local vde_plugs… [See Man Page]'
complete -c wirefilter -l mgmtmode --description 'this option sets the access mode of the mgmt socket.'
complete -c wirefilter -l daemon --description 'wirefilter becomes a daemon.'
complete -c wirefilter -l pidfile --description 'wirefilter saves its pid into the  file.'
complete -c wirefilter -l blinkid --description 'This option defines the id sent for each packet… [See Man Page]'
complete -c wirefilter -l blink --description 'wirefilter sends a log message to the specified… [See Man Page]'

