# x0vncserver
# Autogenerated from man page /usr/share/man/man1/x0vncserver.1.gz
# using Deroffing man parser
complete -c x0vncserver -o SomeParameter --description 'Enable the parameter, turn the feature on.'

