# x86_64-w64-mingw32-ar
# Autogenerated from man page /usr/share/man/man1/x86_64-w64-mingw32-ar.1.gz
# using Type1
complete -c x86_64-w64-mingw32-ar -l help --description 'Displays the list of command line options suppo… [See Man Page]'
complete -c x86_64-w64-mingw32-ar -l version --description 'Displays the version information of ar and then exits.'

