# xapian-progsrv
# Autogenerated from man page /usr/share/man/man1/xapian-progsrv.1.gz
# using Deroffing man parser
complete -c xapian-progsrv -l timeout --description 'set timeout.'
complete -c xapian-progsrv -l writable --description 'allow updates (only one database directory allowed).'
complete -c xapian-progsrv -l help --description 'display this help and exit.'
complete -c xapian-progsrv -l version --description 'output version information and exit.'

