# xapian-replicate-server
# Autogenerated from man page /usr/share/man/man1/xapian-replicate-server.1.gz
# using Deroffing man parser
complete -c xapian-replicate-server -s I -l interface --description 'listen on interface ADDR.'
complete -c xapian-replicate-server -s p -l port --description 'port to listen on.'
complete -c xapian-replicate-server -s o -l one-shot --description 'serve a single connection and exit.'
complete -c xapian-replicate-server -l help --description 'display this help and exit.'
complete -c xapian-replicate-server -l version --description 'output version information and exit.'

