# xapian-compact
# Autogenerated from man page /usr/share/man/man1/xapian-compact.1.gz
# using Deroffing man parser
complete -c xapian-compact -s b -l blocksize --description 'Set the blocksize in bytes (e. g.  4096) or K (e. g.'
complete -c xapian-compact -s n -l no-full --description 'Disable full compaction.'
complete -c xapian-compact -s F -l fuller --description 'Enable fuller compaction (not recommended if yo… [See Man Page]'
complete -c xapian-compact -s m -l multipass --description 'If merging more than 3 databases, merge the pos… [See Man Page]'
complete -c xapian-compact -l no-renumber --description 'external references to them, or have set them t… [See Man Page]'
complete -c xapian-compact -l help --description 'display this help and exit.'
complete -c xapian-compact -l version --description 'output version information and exit.'

