# xapian-tcpsrv
# Autogenerated from man page /usr/share/man/man1/xapian-tcpsrv.1.gz
# using Deroffing man parser
complete -c xapian-tcpsrv -l port --description 'listen on port PORTNUM for connections (no default).'
complete -c xapian-tcpsrv -l interface --description 'listen on the interface associated with name or… [See Man Page]'
complete -c xapian-tcpsrv -l idle-timeout --description 'set timeout for idle connections (default 60000ms).'
complete -c xapian-tcpsrv -l active-timeout --description 'set timeout for active connections (default 15000ms).'
complete -c xapian-tcpsrv -l timeout --description 'set both timeout values.'
complete -c xapian-tcpsrv -l one-shot --description 'serve a single connection and exit.'
complete -c xapian-tcpsrv -l quiet --description 'disable information messages to stdout.'
complete -c xapian-tcpsrv -l writable --description 'allow updates (only one database directory allowed).'
complete -c xapian-tcpsrv -l help --description 'display this help and exit.'
complete -c xapian-tcpsrv -l version --description 'output version information and exit.'

