# xapian-config
# Autogenerated from man page /usr/share/man/man1/xapian-config.1.gz
# using Deroffing man parser
complete -c xapian-config -l cxxflags --description 'output all preprocessor and C++ compiler flags.'
complete -c xapian-config -l libs --description 'output all linker flags.'
complete -c xapian-config -l ltlibs --description 'output linker flags for linking using GNU libtool.'
complete -c xapian-config -l static --description 'make other options report values for static linking.'
complete -c xapian-config -l swigflags --description 'output preprocessor flags for use with SWIG.'
complete -c xapian-config -l help --description 'output this help and exit.'
complete -c xapian-config -l version --description 'output version information and exit REPORTING B… [See Man Page]'

