# xargs
# Autogenerated from man page /usr/share/man/man1/xargs.1p.gz
# using Deroffing man parser
complete -c xargs -o print --description 'or ls into commands to be executed, unexpected … [See Man Page]'
complete -c xargs -o exec --description 'with a \'+\'  terminator instead of \';\' .'

