# xfs_logprint
# Autogenerated from man page /usr/share/man/man8/xfs_logprint.8.gz
# using Deroffing man parser
complete -c xfs_logprint -s b --description 'Extract and print buffer information.'
complete -c xfs_logprint -s c --description 'Attempt to continue when an error is detected.'
complete -c xfs_logprint -s C --description 'Copy the log from the filesystem to the file R filename .'
complete -c xfs_logprint -s d --description 'Dump the log from front to end, printing where … [See Man Page]'
complete -c xfs_logprint -s D --description 'Do not decode anything; just print data.'
complete -c xfs_logprint -s e --description 'Exit when an error is found in the log.'
complete -c xfs_logprint -s f --description 'Specifies that the filesystem image to be proce… [See Man Page]'
complete -c xfs_logprint -s l --description 'External log device.'
complete -c xfs_logprint -s i --description 'Extract and print inode information.'
complete -c xfs_logprint -s q --description 'Extract and print quota information.'
complete -c xfs_logprint -s n --description 'Do not try and interpret log data; just interpr… [See Man Page]'
complete -c xfs_logprint -s o --description 'Also print buffer data in hex.'
complete -c xfs_logprint -s s --description 'Override any notion of where to start printing.'
complete -c xfs_logprint -s t --description 'Print out the transactional view.'
complete -c xfs_logprint -s v --description 'Print "overwrite" data.'
complete -c xfs_logprint -s V --description 'Prints the version number and exits.  SEE ALSO mkfs.'

