# xfs_fsr
# Autogenerated from man page /usr/share/man/man8/xfs_fsr.8.gz
# using Deroffing man parser
complete -c xfs_fsr -s t --description 'How long to reorganize.  The default is 7200 seconds (2 hours).'
complete -c xfs_fsr -s p --description 'Number of passes before terminating global re-org.'
complete -c xfs_fsr -s f --description 'Use this file instead of  /var/tmp/.'
complete -c xfs_fsr -s v --description 'Verbose.'
complete -c xfs_fsr -s d --description 'Debug.   Print even more cryptic information.'
complete -c xfs_fsr -s g --description 'Print to syslog (default if stdout not a tty).'
complete -c xfs_fsr -s m --description '.'
complete -c xfs_fsr -s V --description 'Prints the version number and exits.'

