# xfs_metadump
# Autogenerated from man page /usr/share/man/man8/xfs_metadump.8.gz
# using Deroffing man parser
complete -c xfs_metadump -s e --description 'Stops the dump on a read error.'
complete -c xfs_metadump -s f --description 'Specifies that the filesystem image to be proce… [See Man Page]'
complete -c xfs_metadump -s g --description 'Shows dump progress.'
complete -c xfs_metadump -s l --description 'For filesystems which use an external log, this… [See Man Page]'
complete -c xfs_metadump -s m --description 'Set the maximum size of an allowed metadata extent.'
complete -c xfs_metadump -s o --description 'Disables obfuscation of file names and extended attributes.'
complete -c xfs_metadump -s w --description 'Prints warnings of inconsistent metadata encountered to stderr.'
complete -c xfs_metadump -s n --description 'size >.'
complete -c xfs_metadump -s b --description 'size ) are not obfuscated.'
complete -c xfs_metadump -s V --description 'Prints the version number and exits.'

