# xfs_freeze
# Autogenerated from man page /usr/share/man/man8/xfs_freeze.8.gz
# using Deroffing man parser
complete -c xfs_freeze -s f --description 'flag requests the specified XFS filesystem to b… [See Man Page]'
complete -c xfs_freeze -s u --description 'flag is used to un-freeze the filesystem and al… [See Man Page]'
complete -c xfs_freeze -s V --description 'flag prints the version number and exits.'

