# xfs_copy
# Autogenerated from man page /usr/share/man/man8/xfs_copy.8.gz
# using Deroffing man parser
complete -c xfs_copy -s d --description 'Create a duplicate (true clone) filesystem.'
complete -c xfs_copy -s b --description 'The buffered option can be used to ensure direc… [See Man Page]'
complete -c xfs_copy -s L --description 'Specifies the location of the  log if the defau… [See Man Page]'
complete -c xfs_copy -s V --description 'Prints the version number and exits.'

