# xfs_ncheck
# Autogenerated from man page /usr/share/man/man8/xfs_ncheck.8.gz
# using Deroffing man parser
complete -c xfs_ncheck -s f --description 'Specifies that the filesystem image to be proce… [See Man Page]'
complete -c xfs_ncheck -s l --description 'Specifies the device where the filesystem\'s ext… [See Man Page]'
complete -c xfs_ncheck -s s --description 'Limits the report to special files and files wi… [See Man Page]'
complete -c xfs_ncheck -s i --description 'Limits the report to only those files whose ino… [See Man Page]'
complete -c xfs_ncheck -s V --description 'Prints the version number and exits.'

