# xfs_bmap
# Autogenerated from man page /usr/share/man/man8/xfs_bmap.8.gz
# using Deroffing man parser
complete -c xfs_bmap -s a --description 'If this option is specified, information about … [See Man Page]'
complete -c xfs_bmap -s d --description 'If portions of the file have been migrated offl… [See Man Page]'
complete -c xfs_bmap -s l --description 'If this option is used, then.'
complete -c xfs_bmap -s n --description 'If this option is given,  xfs_bmap obtains the … [See Man Page]'
complete -c xfs_bmap -s p --description 'If this option is used,  xfs_bmap obtains all u… [See Man Page]'
complete -c xfs_bmap -s v --description 'Shows verbose information.'
complete -c xfs_bmap -s V --description 'Prints the version number and exits.'

