# xfs_check
# Autogenerated from man page /usr/share/man/man8/xfs_check.8.gz
# using Deroffing man parser
complete -c xfs_check -s f --description 'flag.'
complete -c xfs_check -s l --description 'Specifies the device where the filesystem\'s ext… [See Man Page]'
complete -c xfs_check -s s --description 'Specifies that only serious errors should be reported.'
complete -c xfs_check -s v --description 'Specifies verbose output; it is impossibly long… [See Man Page]'
complete -c xfs_check -s i --description 'Specifies verbose behavior for the specified inode ino .'
complete -c xfs_check -s b --description 'Specifies verbose behavior for the specific fil… [See Man Page]'
complete -c xfs_check -s V --description 'Prints the version number and exits.'

