# xmode2
# Autogenerated from man page /usr/share/man/man1/xmode2.1.gz
# using Deroffing man parser
complete -c xmode2 -s h -l help --description 'display usage summary.'
complete -c xmode2 -s v -l version --description 'display version.'
complete -c xmode2 -s d -l device --description 'read from given device.'
complete -c xmode2 -s H -l driver --description 'use given driver . HP -g --geometry=geometry window geometry.'
complete -c xmode2 -s t -l timediv --description 'ms per unit.'
complete -c xmode2 -s m -l mode --description 'enable alternative display mode.'
complete -c xmode2 -s g -l geometry --description '.'
complete -c xmode2 -s r -l raw --description 'access device directly SEE ALSO mode2(1), smode2(1), xmode2(1).'

