# yacc
# Autogenerated from man page /usr/share/man/man1/yacc.1p.gz
# using Deroffing man parser
complete -c yacc -s b --description 'Use file_prefix instead of y as the prefix for … [See Man Page]'
complete -c yacc -s d --description 'is specified), and the description file y.'
complete -c yacc -s v --description 'is specified), shall be changed to file_prefix c . tab.'
complete -c yacc -s l --description 'Produce a code file that does not contain any #line constructs.'
complete -c yacc -s p --description '.'
complete -c yacc -s t --description 'Modify conditional compilation directives to pe… [See Man Page]'
complete -c yacc -s D --description 'YYDEBUG option, for example), YYDEBUG shall be … [See Man Page]'

