# zdump
# Autogenerated from man page /usr/share/man/man8/zdump.8.gz
# using Deroffing man parser
complete -c zdump -l version --description 'Output version information and exit.'
complete -c zdump -l help --description 'Output short usage and exit.'
complete -c zdump -s v --description 'For each  zonename on the command line, print t… [See Man Page]'
complete -c zdump -s c --description 'Cut off the verbose output near the start of the given year(s).'

