# zenmap
# Autogenerated from man page /usr/share/man/man1/zenmap.1.gz
# using Deroffing man parser
complete -c zenmap -s f -l file --description '.'
complete -c zenmap -s h -l help --description '.'
complete -c zenmap -s n -l nmap --description '.'
complete -c zenmap -s p -l profile --description '.'
complete -c zenmap -s t --description '.'
complete -c zenmap -l target --description '.'
complete -c zenmap -s v -l verbose --description '.'

