# zvbid
# Autogenerated from man page /usr/share/man/man1/zvbid.1.gz
# using Deroffing man parser
complete -c zvbid -o dev --description 'Path of a device from which to read data.'
complete -c zvbid -o buffers --description 'Number of buffers to allocate for capturing VBI… [See Man Page]'
complete -c zvbid -o nodetach --description 'Daemon process remains connected to the termina… [See Man Page]'
complete -c zvbid -o kill --description 'Terminates a proxy daemon running for the given device.'
complete -c zvbid -o debug --description 'Enables debug output: 0= off(default); 1= gener… [See Man Page]'
complete -c zvbid -o syslog --description 'Enables syslog output.'
complete -c zvbid -o loglevel --description 'Log file level.'
complete -c zvbid -o logfile --description 'Path to the log file.'
complete -c zvbid -o maxclients --description 'Max.'
complete -c zvbid -o help --description 'Print a short description of all command line options.'

