# zvbi-chains
# Autogenerated from man page /usr/share/man/man1/zvbi-chains.1.gz
# using Deroffing man parser
complete -c zvbi-chains -o dev --description 'Path of a VBI device from which to read data.'
complete -c zvbi-chains -o debug --description 'Enables debug output: 0 = off (default); 1 = wa… [See Man Page]'
complete -c zvbi-chains -o help --description 'Print a short description of all command line options.'

